/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlFactory = ({ IDL }) => {
  const TokenId = IDL.Variant({
    'ICP' : IDL.Null,
    'SOL' : IDL.Null,
    'SolUSDC' : IDL.Null,
    'SolUSDT' : IDL.Null,
    'ckETH' : IDL.Null,
    'ckUSDC' : IDL.Null,
    'ckUSDT' : IDL.Null,
    'BaseUSDC' : IDL.Null,
    'BaseUSDT' : IDL.Null,
    'BaseETH' : IDL.Null,
  });
  const AssetLocator = IDL.Variant({
    'Contract' : IDL.Text,
    'Mint' : IDL.Text,
    'Native' : IDL.Null,
  });
  const SupportedAsset = IDL.Record({
    'decimals' : IDL.Nat8,
    'tokenId' : TokenId,
    'locator' : AssetLocator,
    'symbol' : IDL.Text,
  });
  const EvmChainConfig = IDL.Record({
    'evmRpcCanisterId' : IDL.Text,
    'assets' : IDL.Vec(SupportedAsset),
    'rpcUrls' : IDL.Vec(IDL.Text),
    'chainId' : IDL.Nat,
    'networkId' : IDL.Text,
  });
  const SolanaChainConfig = IDL.Record({
    'solRpcCanisterId' : IDL.Text,
    'assets' : IDL.Vec(SupportedAsset),
    'rpcUrl' : IDL.Opt(IDL.Text),
    'networkId' : IDL.Text,
  });
  const ChainConfig = IDL.Variant({
    'Evm' : EvmChainConfig,
    'Solana' : SolanaChainConfig,
  });
  const TreasuryInitArgsV1 = IDL.Record({
    'chains' : IDL.Opt(IDL.Vec(ChainConfig)),
  });
  const InitArgsV1 = IDL.Record({
    'icpaySecretKey' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'treasury' : IDL.Opt(TreasuryInitArgsV1),
  });
  const InitArgs = IDL.Variant({ 'v1' : InitArgsV1 });
  const ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result_9 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const Plan = IDL.Variant({ 'Pro' : IDL.Null, 'Free' : IDL.Null });
  const AddStorageError = IDL.Variant({
    'NotController' : IDL.Null,
    'CanisterAlreadyUsed' : IDL.Record({ 'canisterId' : IDL.Principal }),
    'InvalidWasm' : IDL.Text,
  });
  const Result_8 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : AddStorageError });
  const UserSettings = IDL.Record({
    'spendingPriority' : IDL.Vec(TokenId),
    'topUpAmountCycles' : IDL.Nat,
    'autoRenew' : IDL.Bool,
    'autoTopUp' : IDL.Bool,
  });
  const SortDirection = IDL.Variant({
    'Descending' : IDL.Null,
    'Ascending' : IDL.Null,
  });
  const Time = IDL.Int;
  const TimeRangeFilter = IDL.Record({
    'max' : IDL.Opt(Time),
    'min' : IDL.Opt(Time),
  });
  const Role = IDL.Variant({
    'admin' : IDL.Null,
    'moderator' : IDL.Null,
    'user' : IDL.Null,
  });
  const AdminUserListOptions = IDL.Record({
    'pagination' : IDL.Record({ 'offset' : IDL.Nat, 'limit' : IDL.Nat }),
    'count' : IDL.Bool,
    'sort' : IDL.Vec(IDL.Tuple(IDL.Text, SortDirection)),
    'filter' : IDL.Record({
      'id' : IDL.Opt(IDL.Vec(IDL.Principal)),
      'referralAppliedAt' : IDL.Opt(TimeRangeFilter),
      'identityProvider' : IDL.Opt(IDL.Text),
      'lastLoginAt' : IDL.Opt(TimeRangeFilter),
      'inviter' : IDL.Opt(IDL.Vec(IDL.Principal)),
      'verifiedEmail' : IDL.Opt(IDL.Bool),
      'createdAt' : IDL.Opt(TimeRangeFilter),
      'role' : IDL.Opt(Role),
      'search' : IDL.Opt(IDL.Text),
      'updatedAt' : IDL.Opt(TimeRangeFilter),
      'identitySyncedAt' : IDL.Opt(TimeRangeFilter),
    }),
  });
  const UserIdentityAttributes = IDL.Record({
    'provider' : IDL.Opt(IDL.Text),
    'verifiedEmail' : IDL.Opt(IDL.Bool),
    'name' : IDL.Opt(IDL.Text),
    'email' : IDL.Opt(IDL.Text),
    'syncedAt' : IDL.Opt(Time),
  });
  const AvatarRef = IDL.Record({
    'sha256' : IDL.Vec(IDL.Nat8),
    'contentType' : IDL.Text,
    'size' : IDL.Nat,
    'updatedAt' : Time,
    'blobId' : IDL.Vec(IDL.Nat8),
    'rootHash' : IDL.Text,
  });
  const PublicProfileSummary = IDL.Record({
    'username' : IDL.Text,
    'displayName' : IDL.Opt(IDL.Text),
    'avatarRef' : IDL.Opt(AvatarRef),
  });
  const AdminUserListItem = IDL.Record({
    'id' : IDL.Principal,
    'referralAppliedAt' : IDL.Opt(Time),
    'roleText' : IDL.Text,
    'lastLoginAt' : IDL.Opt(Time),
    'inviter' : IDL.Opt(IDL.Principal),
    'createdAt' : Time,
    'role' : Role,
    'updatedAt' : Time,
    'identity' : UserIdentityAttributes,
    'profile' : IDL.Opt(PublicProfileSummary),
  });
  const AdminUsersPage = IDL.Record({
    'total' : IDL.Opt(IDL.Nat),
    'data' : IDL.Vec(AdminUserListItem),
  });
  const ApplyReferralCodeResult = IDL.Variant({
    'ok' : IDL.Null,
    'storageError' : IDL.Text,
    'userNotFound' : IDL.Null,
    'selfReferral' : IDL.Null,
    'referralCodeNotFound' : IDL.Null,
    'alreadyApplied' : IDL.Null,
  });
  const LicenseStorageLimits = IDL.Record({
    'includedBytes' : IDL.Nat,
    'maxFileBytes' : IDL.Nat,
  });
  const SubscriptionCheckResult = IDL.Variant({
    'active' : IDL.Record({ 'plan' : Plan }),
    'expired' : IDL.Null,
    'licensed' : LicenseStorageLimits,
    'free' : IDL.Null,
    'unknownCanister' : IDL.Null,
    'invalidWasm' : IDL.Null,
  });
  const IdentityAttributesSyncError = IDL.Variant({
    'expired' : IDL.Null,
    'malformedPayload' : IDL.Null,
    'verifiedEmailRequired' : IDL.Null,
    'attributesNotFound' : IDL.Null,
  });
  const IdentityAttributesSyncResult = IDL.Variant({
    'ok' : IDL.Null,
    'err' : IdentityAttributesSyncError,
  });
  const CreateProfileArgs = IDL.Record({
    'username' : IDL.Text,
    'displayName' : IDL.Opt(IDL.Text),
  });
  const DeleteStorageError = IDL.Variant({
    'NotFailed' : IDL.Null,
    'NotFound' : IDL.Null,
    'NotOwner' : IDL.Null,
  });
  const Result_7 = IDL.Variant({ 'ok' : IDL.Null, 'err' : DeleteStorageError });
  const EnsureStorageCyclesForUploadRequest = IDL.Record({
    'activeUploadedBytes' : IDL.Nat,
    'currentBalance' : IDL.Nat,
    'projectedCapacityBytes' : IDL.Nat,
    'postWriteFreezingReserve' : IDL.Nat,
    'remainingUploadBytes' : IDL.Nat,
    'requiredBalance' : IDL.Nat,
  });
  const Result_6 = IDL.Variant({
    'ok' : IDL.Record({
      'cyclesAdded' : IDL.Opt(IDL.Nat),
      'requiredBalance' : IDL.Nat,
    }),
    'err' : IDL.Text,
  });
  const AmbassadorChain = IDL.Record({
    'l1' : IDL.Opt(IDL.Principal),
    'l2' : IDL.Opt(IDL.Principal),
  });
  const StatsView = IDL.Record({
    'totalResolved' : IDL.Nat,
    'totalRefunded' : IDL.Nat,
    'totalDismissed' : IDL.Nat,
    'totalCreated' : IDL.Nat,
  });
  const Progress = IDL.Record({ 'total' : IDL.Nat, 'processed' : IDL.Nat });
  const PaymentPhase = IDL.Variant({
    'CheckingBalances' : IDL.Null,
    'Starting' : IDL.Null,
    'Queueing' : IDL.Null,
    'FetchingRates' : IDL.Null,
    'Charging' : IDL.Record({ 'tokenId' : TokenId, 'amount' : IDL.Nat }),
    'RecordingLicense' : IDL.Null,
  });
  const CreationStatus = IDL.Variant({
    'Failed' : IDL.Text,
    'UpdatingControllers' : IDL.Record({ 'canisterId' : IDL.Principal }),
    'UpgradingWasm' : IDL.Record({
      'progress' : Progress,
      'canisterId' : IDL.Principal,
    }),
    'CanisterCreated' : IDL.Record({ 'canisterId' : IDL.Principal }),
    'RevokingInstallerPermission' : IDL.Record({
      'canisterId' : IDL.Principal,
    }),
    'CheckingBalance' : IDL.Null,
    'UploadingFrontend' : IDL.Record({
      'progress' : Progress,
      'canisterId' : IDL.Principal,
    }),
    'TransferringICP' : IDL.Record({ 'amount' : IDL.Nat }),
    'NotifyingCMC' : IDL.Record({ 'blockIndex' : IDL.Nat }),
    'ProcessingPayment' : PaymentPhase,
    'ReinstallingWasm' : IDL.Record({
      'progress' : Progress,
      'canisterId' : IDL.Principal,
    }),
    'UpgradingFrontend' : IDL.Record({
      'progress' : Progress,
      'canisterId' : IDL.Principal,
    }),
    'Completed' : IDL.Record({ 'canisterId' : IDL.Principal }),
    'InstallingWasm' : IDL.Record({
      'progress' : Progress,
      'canisterId' : IDL.Principal,
    }),
    'Pending' : IDL.Null,
  });
  const AmbassadorPayoutStatus = IDL.Variant({
    'pending' : IDL.Null,
    'skipped' : IDL.Null,
    'completed' : IDL.Null,
    'failed' : IDL.Text,
  });
  const StatusEvent = IDL.Record({
    'status' : CreationStatus,
    'timestamp' : Time,
  });
  const FrontendInstallDiagnostics = IDL.Record({
    'totalFiles' : IDL.Nat,
    'completedAt' : IDL.Opt(Time),
    'startedAt' : Time,
    'changedDeletedFiles' : IDL.Nat,
    'batchesProcessed' : IDL.Nat,
    'skippedBytes' : IDL.Nat,
    'uploadedBytes' : IDL.Nat,
    'error' : IDL.Opt(IDL.Text),
    'updatedAt' : Time,
    'stage' : IDL.Text,
    'skippedFiles' : IDL.Nat,
    'processedBytes' : IDL.Nat,
    'uploadedFiles' : IDL.Nat,
    'staleDeletedFiles' : IDL.Nat,
    'totalBytes' : IDL.Nat,
    'processedFiles' : IDL.Nat,
    'batchesTotal' : IDL.Nat,
  });
  const EnvPair = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const StorageCreationRecord = IDL.Record({
    'id' : IDL.Nat,
    'status' : CreationStatus,
    'completedAt' : IDL.Opt(Time),
    'licensePaymentId' : IDL.Opt(IDL.Text),
    'owner' : IDL.Principal,
    'wasmHash' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'createdAt' : Time,
    'ambassadorPayoutStatus' : AmbassadorPayoutStatus,
    'lastUpgradeError' : IDL.Opt(IDL.Text),
    'isUpgrade' : IDL.Bool,
    'statusTag' : IDL.Text,
    'subnetId' : IDL.Opt(IDL.Principal),
    'upgradeIncludesFrontend' : IDL.Bool,
    'ambassadorPayoutStatusTag' : IDL.Text,
    'events' : IDL.Vec(StatusEvent),
    'releaseTag' : IDL.Text,
    'frontendHash' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'frontendInstallDiagnostics' : IDL.Opt(FrontendInstallDiagnostics),
    'initArg' : IDL.Vec(IDL.Nat8),
    'envPairs' : IDL.Opt(IDL.Vec(EnvPair)),
    'installedReleaseTag' : IDL.Opt(IDL.Text),
    'canisterId' : IDL.Opt(IDL.Principal),
  });
  const DistributionLogOptions = IDL.Record({
    'offset' : IDL.Nat,
    'limit' : IDL.Nat,
  });
  const DistributionStatus = IDL.Variant({
    'completed' : IDL.Null,
    'partial' : IDL.Null,
  });
  const TransferRecord = IDL.Record({
    'tokenId' : TokenId,
    'solSignature' : IDL.Opt(IDL.Text),
    'subaccount' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'recipient' : IDL.Principal,
    'solAddress' : IDL.Opt(IDL.Text),
    'error' : IDL.Opt(IDL.Text),
    'blockIndex' : IDL.Opt(IDL.Nat),
    'txHash' : IDL.Opt(IDL.Text),
    'amount' : IDL.Nat,
    'evmAddress' : IDL.Opt(IDL.Text),
  });
  const DistributionRecord = IDL.Record({
    'id' : IDL.Nat,
    'status' : DistributionStatus,
    'tokenId' : TokenId,
    'l1Amount' : IDL.Nat,
    'transfers' : IDL.Vec(TransferRecord),
    'l2Amount' : IDL.Nat,
    'ambassadorL1' : IDL.Opt(IDL.Principal),
    'ambassadorL2' : IDL.Opt(IDL.Principal),
    'totalAmount' : IDL.Nat,
    'paymentId' : IDL.Text,
    'timestamp' : IDL.Int,
    'payer' : IDL.Principal,
    'treasuryAmount' : IDL.Nat,
  });
  const PendingRefund = IDL.Record({
    'tokenId' : TokenId,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'amount' : IDL.Nat,
    'reason' : IDL.Text,
  });
  const Profile = IDL.Record({
    'id' : IDL.Principal,
    'referralCode' : IDL.Opt(IDL.Text),
    'username' : IDL.Text,
    'displayName' : IDL.Opt(IDL.Text),
    'createdAt' : Time,
    'updatedAt' : Time,
    'avatarRef' : IDL.Opt(AvatarRef),
  });
  const PublicProfileLookup = IDL.Record({
    'principal' : IDL.Principal,
    'profile' : IDL.Opt(PublicProfileSummary),
  });
  const StorageFundingStatus = IDL.Record({
    'spendingPriority' : IDL.Vec(TokenId),
    'paidAutoTopUpEnabled' : IDL.Bool,
    'periodEnd' : IDL.Opt(Time),
    'includedCyclesRemaining' : IDL.Nat,
    'includedCyclesUsed' : IDL.Nat,
    'includedCyclesLimit' : IDL.Nat,
    'periodStart' : IDL.Opt(Time),
    'managedFundingEligible' : IDL.Bool,
    'paidTopUpAmountCycles' : IDL.Nat,
  });
  const AssetDownloadStatus = IDL.Variant({
    'Error' : IDL.Text,
    'Downloading' : IDL.Record({
      'chunksCompleted' : IDL.Nat,
      'chunksError' : IDL.Nat,
      'chunksTotal' : IDL.Nat,
    }),
    'Completed' : IDL.Record({ 'size' : IDL.Nat }),
    'NotStarted' : IDL.Null,
  });
  const FileMetadata = IDL.Record({
    'key' : IDL.Text,
    'sha256' : IDL.Vec(IDL.Nat8),
    'contentType' : IDL.Text,
    'size' : IDL.Nat,
  });
  const ExtractionStatus = IDL.Variant({
    'Idle' : IDL.Null,
    'Complete' : IDL.Vec(FileMetadata),
    'Decoding' : IDL.Record({ 'total' : IDL.Nat, 'processed' : IDL.Nat }),
  });
  const AssetFullStatus = IDL.Record({
    'sha256' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'contentType' : IDL.Text,
    'name' : IDL.Text,
    'size' : IDL.Nat,
    'downloadStatus' : AssetDownloadStatus,
    'extractionStatus' : IDL.Opt(ExtractionStatus),
  });
  const ReleaseArtifactManifest = IDL.Record({
    'sha256' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'size' : IDL.Opt(IDL.Nat),
  });
  const ReleaseUpgradeManifest = IDL.Record({
    'compatibleFrom' : IDL.Vec(IDL.Text),
    'argStrategy' : IDL.Text,
  });
  const ReleaseNoteSection = IDL.Record({
    'title' : IDL.Text,
    'items' : IDL.Vec(IDL.Text),
  });
  const ReleaseNotes = IDL.Record({
    'source' : IDL.Text,
    'summary' : IDL.Text,
    'sections' : IDL.Vec(ReleaseNoteSection),
  });
  const StorageReleaseManifest = IDL.Record({
    'did' : IDL.Opt(ReleaseArtifactManifest),
    'frontendAssetTreeHash' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'tagName' : IDL.Text,
    'wasm' : IDL.Opt(ReleaseArtifactManifest),
    'frontend' : IDL.Opt(ReleaseArtifactManifest),
    'upgrade' : ReleaseUpgradeManifest,
    'releaseNotes' : IDL.Opt(ReleaseNotes),
    'version' : IDL.Text,
    'stableSignature' : IDL.Opt(ReleaseArtifactManifest),
    'schemaVersion' : IDL.Nat,
    'commit' : IDL.Text,
  });
  const ReleaseFullStatus = IDL.Record({
    'tagName' : IDL.Text,
    'isDownloaded' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : Time,
    'assets' : IDL.Vec(AssetFullStatus),
    'htmlUrl' : IDL.Text,
    'publishedAt' : IDL.Opt(Time),
    'manifestError' : IDL.Opt(IDL.Text),
    'isDeploymentReady' : IDL.Bool,
    'manifest' : IDL.Opt(StorageReleaseManifest),
    'draft' : IDL.Bool,
    'prerelease' : IDL.Bool,
  });
  const ReleasesFullStatus = IDL.Record({
    'releasesCount' : IDL.Nat,
    'pendingDownloads' : IDL.Nat,
    'hasDeploymentReadyRelease' : IDL.Bool,
    'hasDownloadedRelease' : IDL.Bool,
    'releases' : IDL.Vec(ReleaseFullStatus),
    'completedDownloads' : IDL.Nat,
  });
  const StorageReleaseState = IDL.Record({
    'frontendAssetTreeHash' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'manifestHash' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'wasmHash' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'installedAt' : IDL.Opt(Time),
    'releaseTag' : IDL.Opt(IDL.Text),
    'schemaVersion' : IDL.Nat,
  });
  const UpdateInfo = IDL.Record({
    'currentWasmHash' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'wasmUpdateAvailable' : IDL.Bool,
    'availableReleaseTag' : IDL.Opt(IDL.Text),
    'currentReleaseTag' : IDL.Opt(IDL.Text),
    'frontendUpdateAvailable' : IDL.Bool,
    'availableWasmHash' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  });
  const StorageReleaseOption = IDL.Record({
    'releaseNotesSummary' : IDL.Opt(IDL.Text),
    'wasmUpdateAvailable' : IDL.Bool,
    'tagName' : IDL.Text,
    'compatibleFrom' : IDL.Vec(IDL.Text),
    'disabled' : IDL.Bool,
    'version' : IDL.Text,
    'releaseNotesSections' : IDL.Vec(ReleaseNoteSection),
    'disabledReason' : IDL.Opt(IDL.Text),
    'releaseUrl' : IDL.Text,
    'frontendUpdateAvailable' : IDL.Bool,
    'updateInfo' : IDL.Opt(UpdateInfo),
  });
  const StorageReleaseOptionsResult = IDL.Record({
    'stateInSync' : IDL.Bool,
    'options' : IDL.Vec(StorageReleaseOption),
  });
  const UpgradeStorageError = IDL.Variant({
    'StorageStateDrift' : IDL.Text,
    'AlreadyUpgrading' : IDL.Null,
    'NoUpdateAvailable' : IDL.Null,
    'NotFound' : IDL.Null,
    'NotOwner' : IDL.Null,
    'ReleaseNotReady' : IDL.Null,
    'ReleaseNotCompatible' : IDL.Null,
    'NotCompleted' : IDL.Null,
  });
  const Result_5 = IDL.Variant({
    'ok' : StorageReleaseOptionsResult,
    'err' : UpgradeStorageError,
  });
  const Status = IDL.Variant({
    'Active' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Expired' : IDL.Null,
  });
  const Subscription = IDL.Record({
    'status' : Status,
    'expiresAt' : IDL.Opt(Time),
    'activatedAt' : Time,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'plan' : Plan,
    'updatedAt' : Time,
    'autoRenew' : IDL.Bool,
  });
  const BalanceEntry = IDL.Record({ 'tokenId' : TokenId, 'balance' : IDL.Nat });
  const UserProfile = IDL.Record({
    'referralCode' : IDL.Opt(IDL.Text),
    'username' : IDL.Text,
    'displayName' : IDL.Opt(IDL.Text),
    'createdAt' : Time,
    'updatedAt' : Time,
    'avatarRef' : IDL.Opt(AvatarRef),
  });
  const User = IDL.Record({
    'id' : IDL.Principal,
    'referralAppliedAt' : IDL.Opt(Time),
    'roleText' : IDL.Text,
    'lastLoginAt' : IDL.Opt(Time),
    'inviter' : IDL.Opt(IDL.Principal),
    'inviterText' : IDL.Text,
    'createdAt' : Time,
    'role' : Role,
    'updatedAt' : Time,
    'identity' : UserIdentityAttributes,
    'profile' : IDL.Opt(UserProfile),
  });
  const Header = IDL.Tuple(IDL.Text, IDL.Text);
  const RawQueryHttpRequest = IDL.Record({
    'url' : IDL.Text,
    'method' : IDL.Text,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(Header),
    'certificate_version' : IDL.Opt(IDL.Nat16),
  });
  const StreamingToken = IDL.Vec(IDL.Nat8);
  const StreamingCallbackResponse = IDL.Record({
    'token' : IDL.Opt(StreamingToken),
    'body' : IDL.Vec(IDL.Nat8),
  });
  const StreamingCallback = IDL.Func(
      [StreamingToken],
      [StreamingCallbackResponse],
      ['query'],
    );
  const CallbackStreamingStrategy = IDL.Record({
    'token' : StreamingToken,
    'callback' : StreamingCallback,
  });
  const StreamingStrategy = IDL.Variant({
    'Callback' : CallbackStreamingStrategy,
  });
  const RawQueryHttpResponse = IDL.Record({
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(Header),
    'upgrade' : IDL.Opt(IDL.Bool),
    'streaming_strategy' : IDL.Opt(StreamingStrategy),
    'status_code' : IDL.Nat16,
  });
  const RawUpdateHttpRequest = IDL.Record({
    'url' : IDL.Text,
    'method' : IDL.Text,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(Header),
  });
  const RawUpdateHttpResponse = IDL.Record({
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(Header),
    'streaming_strategy' : IDL.Opt(StreamingStrategy),
    'status_code' : IDL.Nat16,
  });
  const ListCreationsOptions = IDL.Record({
    'pagination' : IDL.Record({ 'offset' : IDL.Nat, 'limit' : IDL.Nat }),
    'count' : IDL.Bool,
    'sort' : IDL.Vec(IDL.Tuple(IDL.Text, SortDirection)),
    'filter' : IDL.Record({
      'id' : IDL.Opt(IDL.Vec(IDL.Nat)),
      'completedAt' : IDL.Opt(TimeRangeFilter),
      'owner' : IDL.Opt(IDL.Vec(IDL.Principal)),
      'createdAt' : IDL.Opt(TimeRangeFilter),
      'ambassadorPayoutStatus' : IDL.Opt(IDL.Vec(IDL.Text)),
      'hasLicense' : IDL.Opt(IDL.Bool),
      'hasCanister' : IDL.Opt(IDL.Bool),
      'statusTag' : IDL.Opt(IDL.Vec(IDL.Text)),
      'releaseTag' : IDL.Opt(IDL.Text),
      'canisterId' : IDL.Opt(IDL.Vec(IDL.Principal)),
    }),
  });
  const CreationListItem = IDL.Record({
    'id' : IDL.Nat,
    'status' : CreationStatus,
    'completedAt' : IDL.Opt(Time),
    'licensePaymentId' : IDL.Opt(IDL.Text),
    'owner' : IDL.Principal,
    'createdAt' : Time,
    'lastUpgradeError' : IDL.Opt(IDL.Text),
    'isUpgrade' : IDL.Bool,
    'statusTag' : IDL.Text,
    'subnetId' : IDL.Opt(IDL.Principal),
    'upgradeIncludesFrontend' : IDL.Bool,
    'hasFrontendInstallDiagnostics' : IDL.Bool,
    'ambassadorPayoutStatusTag' : IDL.Text,
    'releaseTag' : IDL.Text,
    'lastEventAt' : IDL.Opt(Time),
    'hasEvents' : IDL.Bool,
    'installedReleaseTag' : IDL.Opt(IDL.Text),
    'canisterId' : IDL.Opt(IDL.Principal),
  });
  const GetCreationsResponse = IDL.Record({
    'total' : IDL.Opt(IDL.Nat),
    'data' : IDL.Vec(CreationListItem),
    'instructions' : IDL.Nat,
  });
  const KnownWasmHash = IDL.Record({
    'hash' : IDL.Vec(IDL.Nat8),
    'releaseTag' : IDL.Text,
    'registeredAt' : Time,
  });
  const ListLicensesOptions = IDL.Record({
    'pagination' : IDL.Record({ 'offset' : IDL.Nat, 'limit' : IDL.Nat }),
    'count' : IDL.Bool,
    'sort' : IDL.Vec(IDL.Tuple(IDL.Text, SortDirection)),
    'filter' : IDL.Record({
      'id' : IDL.Opt(IDL.Vec(IDL.Nat)),
      'owner' : IDL.Opt(IDL.Vec(IDL.Principal)),
      'createdAt' : IDL.Opt(TimeRangeFilter),
      'hasCanister' : IDL.Opt(IDL.Bool),
      'statusTag' : IDL.Opt(IDL.Vec(IDL.Text)),
      'paymentId' : IDL.Opt(IDL.Text),
      'paidAt' : IDL.Opt(TimeRangeFilter),
      'canisterId' : IDL.Opt(IDL.Vec(IDL.Principal)),
    }),
  });
  const PaymentStatus = IDL.Variant({
    'completed' : IDL.Null,
    'refunded' : IDL.Record({
      'at' : Time,
      'blockIndex' : IDL.Opt(IDL.Nat),
      'reason' : IDL.Text,
    }),
  });
  const PaymentReceipt = IDL.Record({
    'status' : PaymentStatus,
    'tokenId' : TokenId,
    'paymentId' : IDL.Text,
    'amount' : IDL.Nat,
    'paidAt' : Time,
  });
  const StorageLicenseEntitlement = IDL.Record({
    'includedBytes' : IDL.Nat,
    'maxFileBytes' : IDL.Nat,
  });
  const License = IDL.Record({
    'receipt' : PaymentReceipt,
    'owner' : IDL.Principal,
    'createdAt' : Time,
    'statusTag' : IDL.Text,
    'storageEntitlement' : StorageLicenseEntitlement,
    'canisterId' : IDL.Opt(IDL.Principal),
  });
  const GetLicensesResponse = IDL.Record({
    'total' : IDL.Opt(IDL.Nat),
    'data' : IDL.Vec(License),
    'instructions' : IDL.Nat,
  });
  const ListNotificationsArgs = IDL.Record({
    'limit' : IDL.Nat,
    'afterId' : IDL.Opt(IDL.Nat),
    'unreadOnly' : IDL.Bool,
  });
  const NotificationSource = IDL.Variant({
    'storage' : IDL.Null,
    'backend' : IDL.Null,
  });
  const SourceEventRef = IDL.Variant({
    'storage' : IDL.Record({
      'storageEventId' : IDL.Nat,
      'canisterId' : IDL.Principal,
    }),
    'backend' : IDL.Record({ 'kind' : IDL.Text }),
  });
  const NotificationSeverity = IDL.Variant({
    'warning' : IDL.Null,
    'info' : IDL.Null,
    'critical' : IDL.Null,
    'success' : IDL.Null,
  });
  const AccessClass = IDL.Variant({
    'ordinary' : IDL.Null,
    'ownerEquivalent' : IDL.Null,
    'durable' : IDL.Null,
  });
  const AccessSource = IDL.Variant({
    'durablePolicy' : IDL.Nat,
    'accessRequest' : IDL.Nat,
    'directGrant' : IDL.Null,
    'ordinaryInvite' : IDL.Nat,
    'recoverySetup' : IDL.Null,
  });
  const AccessRequestStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const NotificationPayload = IDL.Variant({
    'storageAccessRevoked' : IDL.Record({
      'accessClass' : IDL.Opt(AccessClass),
      'canisterId' : IDL.Principal,
    }),
    'backendLowCycles' : IDL.Record({
      'threshold' : IDL.Nat,
      'current' : IDL.Nat,
    }),
    'topUpCompleted' : IDL.Record({
      'canisterId' : IDL.Principal,
      'cyclesAmount' : IDL.Nat,
    }),
    'depositReceived' : IDL.Record({
      'tokenId' : IDL.Text,
      'amount' : IDL.Nat,
    }),
    'cmcNotifyStuck' : IDL.Record({
      'id' : IDL.Nat,
      'blockIndex' : IDL.Nat,
      'caller' : IDL.Principal,
      'canisterId' : IDL.Principal,
      'reason' : IDL.Text,
    }),
    'storageAccessRequestCancelled' : IDL.Record({
      'requestId' : IDL.Nat,
      'requester' : IDL.Principal,
      'canisterId' : IDL.Principal,
    }),
    'ambassadorPayoutFailed' : IDL.Record({
      'owner' : IDL.Principal,
      'creationId' : IDL.Nat,
      'reason' : IDL.Text,
    }),
    'subscriptionExpired' : IDL.Null,
    'storageInviteCreated' : IDL.Record({
      'source' : AccessSource,
      'grantId' : IDL.Nat,
      'accessClass' : AccessClass,
      'canisterId' : IDL.Principal,
    }),
    'autoRenewFailed' : IDL.Record({ 'reason' : IDL.Text }),
    'storageAccessGranted' : IDL.Record({
      'source' : AccessSource,
      'grantId' : IDL.Opt(IDL.Nat),
      'accessClass' : AccessClass,
      'canisterId' : IDL.Principal,
    }),
    'topUpFailed' : IDL.Record({
      'canisterId' : IDL.Principal,
      'reason' : IDL.Text,
    }),
    'storageInviteCancelled' : IDL.Record({
      'grantId' : IDL.Nat,
      'canisterId' : IDL.Principal,
    }),
    'storageRecoveryOwnerAdded' : IDL.Record({ 'canisterId' : IDL.Principal }),
    'autoTopUpCompleted' : IDL.Record({
      'canisterId' : IDL.Principal,
      'cyclesAmount' : IDL.Nat,
    }),
    'creationRefunded' : IDL.Record({
      'tokenId' : IDL.Text,
      'owner' : IDL.Principal,
      'creationId' : IDL.Nat,
      'amount' : IDL.Nat,
    }),
    'treasuryIcpLow' : IDL.Record({
      'currentBalance' : IDL.Nat,
      'reserve' : IDL.Nat,
      'required' : IDL.Nat,
    }),
    'storageRecoveryOwnerRemoved' : IDL.Record({
      'canisterId' : IDL.Principal,
    }),
    'storageInviteClaimed' : IDL.Record({
      'principal' : IDL.Principal,
      'source' : AccessSource,
      'grantId' : IDL.Nat,
      'accessClass' : AccessClass,
      'canisterId' : IDL.Principal,
    }),
    'subscriptionRenewed' : IDL.Record({
      'expiresAt' : IDL.Opt(IDL.Int),
      'plan' : IDL.Variant({ 'Pro' : IDL.Null, 'Free' : IDL.Null }),
    }),
    'storageAccessRequestCreated' : IDL.Record({
      'requestId' : IDL.Nat,
      'requester' : IDL.Principal,
      'canisterId' : IDL.Principal,
    }),
    'balanceLow' : IDL.Record({ 'requiredAmount' : IDL.Nat }),
    'paymentReceived' : IDL.Record({
      'tokenId' : IDL.Text,
      'amount' : IDL.Nat,
      'purpose' : IDL.Text,
    }),
    'subscriptionActivated' : IDL.Record({
      'plan' : IDL.Variant({ 'Pro' : IDL.Null, 'Free' : IDL.Null }),
    }),
    'storageAccessRequestResolved' : IDL.Record({
      'status' : AccessRequestStatus,
      'requestId' : IDL.Nat,
      'canisterId' : IDL.Principal,
    }),
    'updateAvailable' : IDL.Record({
      'releaseTag' : IDL.Text,
      'canisterId' : IDL.Principal,
    }),
    'autoTopUpFailed' : IDL.Record({
      'canisterId' : IDL.Principal,
      'reason' : IDL.Text,
    }),
    'lowCycles' : IDL.Record({
      'estimatedDaysLeft' : IDL.Nat,
      'severity' : IDL.Variant({ 'warning' : IDL.Null, 'critical' : IDL.Null }),
      'remaining' : IDL.Nat,
      'canisterId' : IDL.Principal,
    }),
    'backendSelfTopUpFailed' : IDL.Record({ 'reason' : IDL.Text }),
  });
  const StoredNotification = IDL.Record({
    'id' : IDL.Nat,
    'source' : NotificationSource,
    'createdAt' : Time,
    'read' : IDL.Bool,
    'sourceEvent' : IDL.Opt(SourceEventRef),
    'severity' : NotificationSeverity,
    'correlationId' : IDL.Opt(IDL.Text),
    'payload' : NotificationPayload,
  });
  const NotificationsPage = IDL.Record({
    'data' : IDL.Vec(StoredNotification),
    'unreadCount' : IDL.Nat,
  });
  const CmcOpSource = IDL.Variant({
    'storageCreation' : IDL.Record({ 'creationId' : IDL.Nat }),
    'selfTopUp' : IDL.Null,
    'userTopUp' : IDL.Record({ 'canisterId' : IDL.Principal }),
    'autoTopUp' : IDL.Record({ 'canisterId' : IDL.Principal }),
  });
  const CmcOpKind = IDL.Variant({
    'CreateCanister' : IDL.Null,
    'TopUp' : IDL.Null,
  });
  const RefundContext = IDL.Record({
    'tokenId' : TokenId,
    'payer' : IDL.Principal,
    'amount' : IDL.Nat,
  });
  const PendingCmcOp = IDL.Record({
    'id' : IDL.Nat,
    'lastAttemptAt' : IDL.Opt(Time),
    'source' : CmcOpSource,
    'kind' : CmcOpKind,
    'createdAt' : Time,
    'attempts' : IDL.Nat,
    'blockIndex' : IDL.Nat,
    'lastError' : IDL.Text,
    'refund' : IDL.Opt(RefundContext),
  });
  const SharedStorageAccess = IDL.Record({
    'storageCanisterId' : IDL.Principal,
    'activeAccessClasses' : IDL.Vec(AccessClass),
    'lastStorageEventId' : IDL.Nat,
    'firstSeenAt' : Time,
    'pendingAccessClasses' : IDL.Vec(AccessClass),
    'updatedAt' : Time,
    'accountOwner' : IDL.Principal,
    'pendingGrantIds' : IDL.Vec(IDL.Nat),
    'lastCorrelationId' : IDL.Opt(IDL.Text),
    'lastSource' : IDL.Opt(AccessSource),
  });
  const SharedStorageAccessView = IDL.Record({
    'access' : SharedStorageAccess,
    'storageStatus' : IDL.Opt(CreationStatus),
    'updateAvailable' : IDL.Opt(UpdateInfo),
  });
  const StorageInfo = IDL.Record({
    'id' : IDL.Nat,
    'status' : CreationStatus,
    'completedAt' : IDL.Opt(Time),
    'createdAt' : Time,
    'lastUpgradeError' : IDL.Opt(IDL.Text),
    'releaseTag' : IDL.Text,
    'frontendInstallDiagnostics' : IDL.Opt(FrontendInstallDiagnostics),
    'updateAvailable' : IDL.Opt(UpdateInfo),
    'canisterId' : IDL.Opt(IDL.Principal),
  });
  const ListOptions = IDL.Record({
    'pagination' : IDL.Record({ 'offset' : IDL.Nat, 'limit' : IDL.Nat }),
    'count' : IDL.Bool,
    'sort' : IDL.Vec(IDL.Tuple(IDL.Text, SortDirection)),
    'filter' : IDL.Record({
      'status' : IDL.Opt(IDL.Vec(Status)),
      'expiresAt' : IDL.Opt(
        IDL.Record({ 'max' : IDL.Opt(IDL.Int), 'min' : IDL.Opt(IDL.Int) })
      ),
      'userId' : IDL.Opt(IDL.Vec(IDL.Principal)),
      'plan' : IDL.Opt(IDL.Vec(Plan)),
    }),
  });
  const GetSubscriptionsResponse = IDL.Record({
    'total' : IDL.Opt(IDL.Nat),
    'data' : IDL.Vec(Subscription),
    'instructions' : IDL.Nat,
  });
  const DurablePolicyStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'armed' : IDL.Null,
    'released' : IDL.Null,
    'matured' : IDL.Null,
    'grace' : IDL.Null,
  });
  const DurablePolicyTrigger = IDL.Variant({
    'manualRelease' : IDL.Null,
    'date' : IDL.Record({ 'releaseAt' : Time }),
    'inactivity' : IDL.Record({
      'inactiveForNs' : IDL.Nat,
      'gracePeriodNs' : IDL.Opt(IDL.Nat),
    }),
  });
  const OwnerActivityOrigin = IDL.Variant({
    'storage' : IDL.Null,
    'rabbithole' : IDL.Null,
    'backend' : IDL.Null,
  });
  const OwnerActivityRole = IDL.Variant({
    'recoveryOwner' : IDL.Null,
    'accountOwner' : IDL.Null,
  });
  const EmailClaimOrigin = IDL.Variant({
    'storage' : IDL.Null,
    'rabbithole' : IDL.Null,
  });
  const EmailClaim = IDL.Record({
    'principalGrantId' : IDL.Nat,
    'principal' : IDL.Principal,
    'origin' : EmailClaimOrigin,
    'claimedAt' : Time,
  });
  const EmailClaimState = IDL.Record({
    'storage' : IDL.Opt(EmailClaim),
    'rabbithole' : IDL.Opt(EmailClaim),
  });
  const StorageAccessLifecycleEvent = IDL.Variant({
    'accessRequestResolved' : IDL.Record({
      'status' : AccessRequestStatus,
      'requestId' : IDL.Nat,
      'requester' : IDL.Principal,
    }),
    'durablePolicyCreated' : IDL.Record({
      'status' : DurablePolicyStatus,
      'trigger' : DurablePolicyTrigger,
      'policyId' : IDL.Nat,
    }),
    'accessRequestCreated' : IDL.Record({
      'requestId' : IDL.Nat,
      'requester' : IDL.Principal,
    }),
    'recoveryControllerRegistered' : IDL.Record({
      'principal' : IDL.Principal,
      'previous' : IDL.Opt(IDL.Principal),
    }),
    'pendingGrantCreated' : IDL.Record({
      'source' : AccessSource,
      'recipient' : IDL.Opt(IDL.Principal),
      'emailCommitment' : IDL.Opt(IDL.Vec(IDL.Nat8)),
      'grantId' : IDL.Nat,
      'accessClass' : AccessClass,
    }),
    'ownerActivityRecorded' : IDL.Record({
      'principal' : IDL.Principal,
      'origin' : OwnerActivityOrigin,
      'role' : OwnerActivityRole,
    }),
    'durablePolicyReleased' : IDL.Record({ 'policyId' : IDL.Nat }),
    'recoveryControllerCleared' : IDL.Record({ 'principal' : IDL.Principal }),
    'durablePolicyMatured' : IDL.Record({ 'policyId' : IDL.Nat }),
    'recoveryOwnerAdded' : IDL.Record({ 'principal' : IDL.Principal }),
    'pendingGrantClaimed' : IDL.Record({
      'principal' : IDL.Principal,
      'emailClaimState' : IDL.Opt(EmailClaimState),
      'source' : AccessSource,
      'grantId' : IDL.Nat,
      'claimOrigin' : IDL.Opt(EmailClaimOrigin),
      'accessClass' : AccessClass,
    }),
    'durablePolicyCancelled' : IDL.Record({ 'policyId' : IDL.Nat }),
    'accessRequestCancelled' : IDL.Record({
      'requestId' : IDL.Nat,
      'requester' : IDL.Principal,
    }),
    'principalGrantCreated' : IDL.Record({
      'principal' : IDL.Principal,
      'source' : AccessSource,
      'grantId' : IDL.Opt(IDL.Nat),
      'accessClass' : AccessClass,
    }),
    'pendingGrantCancelled' : IDL.Record({
      'recipient' : IDL.Opt(IDL.Principal),
      'emailCommitment' : IDL.Opt(IDL.Vec(IDL.Nat8)),
      'grantId' : IDL.Nat,
    }),
    'durablePolicyGraceStarted' : IDL.Record({ 'policyId' : IDL.Nat }),
    'principalGrantRevoked' : IDL.Record({
      'principal' : IDL.Principal,
      'accessClass' : IDL.Opt(AccessClass),
    }),
    'recoveryOwnerRemoved' : IDL.Record({ 'principal' : IDL.Principal }),
  });
  const CorrelationId = IDL.Text;
  const StorageAccessChanged = IDL.Record({
    'storageCanisterId' : IDL.Principal,
    'storageEventId' : IDL.Nat,
    'event' : StorageAccessLifecycleEvent,
    'correlationId' : IDL.Opt(CorrelationId),
    'accountOwner' : IDL.Principal,
  });
  const PrepareAvatarUploadArgs = IDL.Record({
    'content' : IDL.Vec(IDL.Nat8),
    'contentType' : IDL.Text,
  });
  const PrepareAvatarUploadResult = IDL.Record({
    'sha256' : IDL.Vec(IDL.Nat8),
    'contentType' : IDL.Text,
    'size' : IDL.Nat,
    'updatedAt' : Time,
    'blobId' : IDL.Vec(IDL.Nat8),
    'rootHash' : IDL.Text,
  });
  const Result_2 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const StorageBackendType = IDL.Variant({
    'OnChain' : IDL.Null,
    'BlobStorage' : IDL.Null,
  });
  const StorageVetKeyLevel = IDL.Variant({
    'highReplication' : IDL.Null,
    'standard' : IDL.Null,
  });
  const PurchaseError = IDL.Variant({
    'ActivationFailed' : IDL.Text,
    'InvalidPlan' : IDL.Text,
    'ChargeFailed' : IDL.Text,
    'AlreadyActive' : IDL.Null,
    'InsufficientFunds' : IDL.Record({ 'required' : IDL.Nat }),
  });
  const Result_4 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : PurchaseError });
  const Result_3 = IDL.Variant({ 'ok' : IDL.Null, 'err' : PurchaseError });
  const RecoveryStrategy = IDL.Variant({
    'resume' : IDL.Null,
    'refund' : IDL.Null,
  });
  const RefundNetwork = IDL.Variant({
    'ic' : IDL.Null,
    'evm' : IDL.Null,
    'solana' : IDL.Null,
  });
  const RefundReference = IDL.Variant({
    'signature' : IDL.Text,
    'blockIndex' : IDL.Nat,
    'txHash' : IDL.Text,
  });
  const RefundReceipt = IDL.Record({
    'at' : Time,
    'tokenId' : TokenId,
    'recipient' : IDL.Principal,
    'network' : RefundNetwork,
    'reference' : RefundReference,
    'amount' : IDL.Nat,
  });
  const CmcOpRetryResult = IDL.Variant({
    'scheduled' : IDL.Record({ 'canisterId' : IDL.Principal }),
    'resolved' : IDL.Null,
    'refunded' : IDL.Record({ 'receipt' : IDL.Opt(RefundReceipt) }),
    'blockedByRefund' : IDL.Null,
    'notFound' : IDL.Null,
    'stillAmbiguous' : IDL.Record({ 'attempts' : IDL.Nat }),
  });
  const UserDirectoryMatch = IDL.Variant({
    'principalExact' : IDL.Null,
    'emailExact' : IDL.Null,
    'profile' : IDL.Null,
  });
  const UserDirectoryItem = IDL.Record({
    'id' : IDL.Principal,
    'match' : UserDirectoryMatch,
    'profile' : IDL.Opt(PublicProfileSummary),
  });
  const Result_1 = IDL.Variant({
    'ok' : IDL.Null,
    'err' : UpgradeStorageError,
  });
  const Result = IDL.Variant({
    'ok' : IDL.Record({ 'cyclesAdded' : IDL.Nat }),
    'err' : IDL.Text,
  });
  const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const HttpRequestResult = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  const TransformArg = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : HttpRequestResult,
  });
  const UpdateProfileArgs = IDL.Record({ 'displayName' : IDL.Opt(IDL.Text) });
  const WithdrawDestination = IDL.Variant({
    'IC' : IDL.Record({
      'owner' : IDL.Principal,
      'subaccount' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    }),
    'EVM' : IDL.Record({ 'address' : IDL.Text }),
    'SOL' : IDL.Record({ 'address' : IDL.Text }),
  });
  const WithdrawArgs = IDL.Record({
    'to' : WithdrawDestination,
    'tokenId' : TokenId,
    'amount' : IDL.Nat,
  });
  const WithdrawError = IDL.Variant({
    'BelowMinimum' : IDL.Record({ 'minimum' : IDL.Nat }),
    'InsufficientBalance' : IDL.Record({ 'available' : IDL.Nat }),
    'TransferFailed' : IDL.Text,
    'EvmNotConfigured' : IDL.Null,
    'SolNotConfigured' : IDL.Null,
  });
  const WithdrawResult = IDL.Variant({ 'ok' : IDL.Nat, 'err' : WithdrawError });
  const Rabbithole = IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(ImmutableObjectStorageRefillInformation)],
        [ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result_9], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'activateSubscription' : IDL.Func(
        [IDL.Principal, Plan, IDL.Opt(IDL.Int)],
        [],
        [],
      ),
    'addStorage' : IDL.Func([IDL.Principal, IDL.Vec(IDL.Nat8)], [Result_8], []),
    'adminGetUserWalletMeta' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Record({
            'walletAddresses' : IDL.Record({
              'icSubaccount' : IDL.Vec(IDL.Nat8),
              'solAddress' : IDL.Opt(IDL.Text),
              'evmAddress' : IDL.Opt(IDL.Text),
            }),
            'settings' : UserSettings,
          }),
        ],
        ['query'],
      ),
    'adminListUsers' : IDL.Func(
        [AdminUserListOptions],
        [AdminUsersPage],
        ['query'],
      ),
    'adminRebuildKnownWasmHashesFromDownloadedReleases' : IDL.Func(
        [],
        [IDL.Nat],
        [],
      ),
    'adminRegisterWasmHash' : IDL.Func([IDL.Vec(IDL.Nat8), IDL.Text], [], []),
    'adminSyncBlobStorageCashierAdminAccess' : IDL.Func([], [], []),
    'applyReferralCode' : IDL.Func([IDL.Text], [ApplyReferralCodeResult], []),
    'checkSubscription' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [SubscriptionCheckResult],
        [],
      ),
    'claimVerifiedEmailAccess' : IDL.Func(
        [],
        [IdentityAttributesSyncResult],
        [],
      ),
    'clearAvatar' : IDL.Func([], [], []),
    'commitAvatarUpload' : IDL.Func([IDL.Text], [AvatarRef], []),
    'createProfile' : IDL.Func([CreateProfileArgs], [IDL.Vec(IDL.Nat8)], []),
    'deleteProfile' : IDL.Func([], [], []),
    'deleteStorage' : IDL.Func([IDL.Nat], [Result_7], []),
    'dismissPendingCmcOp' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'notFound' : IDL.Null })],
        [],
      ),
    'ensureStorageCyclesForUpload' : IDL.Func(
        [EnsureStorageCyclesForUploadRequest],
        [Result_6],
        [],
      ),
    'ensureUser' : IDL.Func([IDL.Opt(IDL.Text)], [], []),
    'flushPaymentQueue' : IDL.Func([], [], []),
    'getAmbassadorChainQuery' : IDL.Func([], [AmbassadorChain], ['query']),
    'getBackendCyclesBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getCmcRecoveryStats' : IDL.Func([], [StatsView], ['query']),
    'getCreationDetail' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(StorageCreationRecord)],
        ['query'],
      ),
    'getDistributionLog' : IDL.Func(
        [DistributionLogOptions],
        [IDL.Vec(DistributionRecord)],
        ['query'],
      ),
    'getEvmAddress' : IDL.Func([], [IDL.Opt(IDL.Text)], []),
    'getMyWalletAddresses' : IDL.Func(
        [],
        [
          IDL.Record({
            'icSubaccount' : IDL.Vec(IDL.Nat8),
            'solAddress' : IDL.Opt(IDL.Text),
            'evmAddress' : IDL.Opt(IDL.Text),
          }),
        ],
        ['query'],
      ),
    'getPendingRefunds' : IDL.Func([], [IDL.Vec(PendingRefund)], ['query']),
    'getProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getPublicProfiles' : IDL.Func(
        [IDL.Vec(IDL.Principal)],
        [IDL.Vec(PublicProfileLookup)],
        ['query'],
      ),
    'getSettings' : IDL.Func([], [UserSettings], ['query']),
    'getSolAddress' : IDL.Func([], [IDL.Opt(IDL.Text)], []),
    'getStorageFundingStatus' : IDL.Func([], [StorageFundingStatus], ['query']),
    'getStorageReleaseAdminStatus' : IDL.Func(
        [],
        [ReleasesFullStatus],
        ['query'],
      ),
    'getStorageUpgradePlan' : IDL.Func(
        [IDL.Principal, StorageReleaseState],
        [Result_5],
        ['query'],
      ),
    'getSubscription' : IDL.Func([], [IDL.Opt(Subscription)], ['query']),
    'getTreasuryBalances' : IDL.Func([], [IDL.Vec(BalanceEntry)], []),
    'getTreasuryWalletAddresses' : IDL.Func(
        [],
        [
          IDL.Record({
            'icSubaccount' : IDL.Vec(IDL.Nat8),
            'solAddress' : IDL.Opt(IDL.Text),
            'evmAddress' : IDL.Opt(IDL.Text),
          }),
        ],
        [],
      ),
    'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUser' : IDL.Func([], [IDL.Opt(User)], ['query']),
    'http_request' : IDL.Func(
        [RawQueryHttpRequest],
        [RawQueryHttpResponse],
        ['query'],
      ),
    'http_request_update' : IDL.Func(
        [RawUpdateHttpRequest],
        [RawUpdateHttpResponse],
        [],
      ),
    'isAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isKnownWasmHash' : IDL.Func([IDL.Vec(IDL.Nat8)], [IDL.Bool], ['query']),
    'isStorageDeployerRunning' : IDL.Func([], [IDL.Bool], ['query']),
    'listCreations' : IDL.Func(
        [IDL.Opt(ListCreationsOptions)],
        [GetCreationsResponse],
        ['query'],
      ),
    'listKnownWasmHashes' : IDL.Func([], [IDL.Vec(KnownWasmHash)], ['query']),
    'listLicenses' : IDL.Func(
        [IDL.Opt(ListLicensesOptions)],
        [GetLicensesResponse],
        ['query'],
      ),
    'listNotifications' : IDL.Func(
        [ListNotificationsArgs],
        [NotificationsPage],
        ['query'],
      ),
    'listPendingCmcOps' : IDL.Func(
        [
          IDL.Record({
            'limit' : IDL.Opt(IDL.Nat),
            'afterId' : IDL.Opt(IDL.Nat),
          }),
        ],
        [IDL.Vec(PendingCmcOp)],
        ['query'],
      ),
    'listSharedWithMeStorageViews' : IDL.Func(
        [],
        [IDL.Vec(SharedStorageAccessView)],
        ['query'],
      ),
    'listSharedWithMeStorages' : IDL.Func(
        [],
        [IDL.Vec(SharedStorageAccess)],
        ['query'],
      ),
    'listStorages' : IDL.Func([], [IDL.Vec(StorageInfo)], ['query']),
    'listSubscriptions' : IDL.Func(
        [ListOptions],
        [GetSubscriptionsResponse],
        ['query'],
      ),
    'listUsersByRole' : IDL.Func([Role], [IDL.Vec(IDL.Principal)], ['query']),
    'markAllNotificationsRead' : IDL.Func([], [], []),
    'markNotificationsRead' : IDL.Func([IDL.Vec(IDL.Nat)], [], []),
    'markNotificationsReadUpTo' : IDL.Func([IDL.Nat], [], []),
    'onStorageAccessChanged' : IDL.Func([StorageAccessChanged], [], []),
    'onStorageLowCycles' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Variant({ 'warning' : IDL.Null, 'critical' : IDL.Null }),
        ],
        [],
        [],
      ),
    'prepareAvatarUpload' : IDL.Func(
        [PrepareAvatarUploadArgs],
        [PrepareAvatarUploadResult],
        [],
      ),
    'prepareStorageRelease' : IDL.Func([IDL.Text], [Result_2], []),
    'processPendingRefunds' : IDL.Func([], [IDL.Nat], []),
    'purchaseLicenseAndCreateStorage' : IDL.Func(
        [StorageBackendType, StorageVetKeyLevel],
        [Result_4],
        [],
      ),
    'purchaseSubscription' : IDL.Func([Plan], [Result_3], []),
    'queryExpiredSubscriptions' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, Subscription))],
        ['query'],
      ),
    'queryExpiringSubscriptions' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Principal, Subscription))],
        ['query'],
      ),
    'recoverFailedStorage' : IDL.Func(
        [IDL.Nat, RecoveryStrategy],
        [Result_2],
        [],
      ),
    'recoverStuckCreation' : IDL.Func([IDL.Nat], [Result_2], []),
    'refreshStorageReleaseIndex' : IDL.Func([], [], []),
    'reinstallFailedStorageWasm' : IDL.Func([IDL.Nat], [Result_2], []),
    'renewSubscription' : IDL.Func(
        [IDL.Principal, Plan, IDL.Opt(IDL.Int)],
        [],
        [],
      ),
    'retryAmbassadorPayout' : IDL.Func([IDL.Nat], [Result_2], []),
    'retryPendingCmcOp' : IDL.Func([IDL.Nat], [CmcOpRetryResult], []),
    'searchUserDirectory' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(UserDirectoryItem)],
        ['query'],
      ),
    'setUserRole' : IDL.Func([IDL.Principal, Role], [], []),
    'startStorageDeployer' : IDL.Func([], [], []),
    'startStorageUpgrade' : IDL.Func(
        [IDL.Principal, IDL.Text, StorageReleaseState],
        [Result_1],
        [],
      ),
    'stopStorageDeployer' : IDL.Func([], [], []),
    'topUpFromBalance' : IDL.Func([IDL.Principal, IDL.Nat], [Result], []),
    'transformGitHubReleaseResponse' : IDL.Func(
        [TransformArg],
        [HttpRequestResult],
        ['query'],
      ),
    'triggerAutoRenewals' : IDL.Func([], [], []),
    'triggerExpireOverdue' : IDL.Func([], [IDL.Vec(IDL.Principal)], []),
    'triggerSelfTopUp' : IDL.Func([], [], []),
    'updateProfile' : IDL.Func([UpdateProfileArgs], [], []),
    'updateSettings' : IDL.Func([UserSettings], [], []),
    'usernameExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'withdraw' : IDL.Func([WithdrawArgs], [WithdrawResult], []),
    'withdrawFromTreasury' : IDL.Func([WithdrawArgs], [WithdrawResult], []),
  });
  
  return Rabbithole;
};

export const init = ({ IDL }) => {
  const TokenId = IDL.Variant({
    'ICP' : IDL.Null,
    'SOL' : IDL.Null,
    'SolUSDC' : IDL.Null,
    'SolUSDT' : IDL.Null,
    'ckETH' : IDL.Null,
    'ckUSDC' : IDL.Null,
    'ckUSDT' : IDL.Null,
    'BaseUSDC' : IDL.Null,
    'BaseUSDT' : IDL.Null,
    'BaseETH' : IDL.Null,
  });
  const AssetLocator = IDL.Variant({
    'Contract' : IDL.Text,
    'Mint' : IDL.Text,
    'Native' : IDL.Null,
  });
  const SupportedAsset = IDL.Record({
    'decimals' : IDL.Nat8,
    'tokenId' : TokenId,
    'locator' : AssetLocator,
    'symbol' : IDL.Text,
  });
  const EvmChainConfig = IDL.Record({
    'evmRpcCanisterId' : IDL.Text,
    'assets' : IDL.Vec(SupportedAsset),
    'rpcUrls' : IDL.Vec(IDL.Text),
    'chainId' : IDL.Nat,
    'networkId' : IDL.Text,
  });
  const SolanaChainConfig = IDL.Record({
    'solRpcCanisterId' : IDL.Text,
    'assets' : IDL.Vec(SupportedAsset),
    'rpcUrl' : IDL.Opt(IDL.Text),
    'networkId' : IDL.Text,
  });
  const ChainConfig = IDL.Variant({
    'Evm' : EvmChainConfig,
    'Solana' : SolanaChainConfig,
  });
  const TreasuryInitArgsV1 = IDL.Record({
    'chains' : IDL.Opt(IDL.Vec(ChainConfig)),
  });
  const InitArgsV1 = IDL.Record({
    'icpaySecretKey' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'treasury' : IDL.Opt(TreasuryInitArgsV1),
  });
  const InitArgs = IDL.Variant({ 'v1' : InitArgsV1 });
  
  return [InitArgs];
};