/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AccessClass = { 'ordinary' : null } |
  { 'ownerEquivalent' : null } |
  { 'durable' : null };
export type AccessRequestStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type AccessSource = { 'durablePolicy' : bigint } |
  { 'accessRequest' : bigint } |
  { 'directGrant' : null } |
  { 'ordinaryInvite' : bigint } |
  { 'recoverySetup' : null };
export type AddStorageError = { 'NotController' : null } |
  { 'CanisterAlreadyUsed' : { 'canisterId' : Principal } } |
  { 'InvalidWasm' : string };
export interface AdminUserListItem {
  'id' : Principal,
  'referralAppliedAt' : [] | [Time],
  'roleText' : string,
  'lastLoginAt' : [] | [Time],
  'inviter' : [] | [Principal],
  'createdAt' : Time,
  'role' : Role,
  'updatedAt' : Time,
  'identity' : UserIdentityAttributes,
  'profile' : [] | [PublicProfileSummary],
}
export interface AdminUserListOptions {
  'pagination' : { 'offset' : bigint, 'limit' : bigint },
  'count' : boolean,
  'sort' : Array<[string, SortDirection]>,
  'filter' : {
    'id' : [] | [Array<Principal>],
    'referralAppliedAt' : [] | [TimeRangeFilter],
    'identityProvider' : [] | [string],
    'lastLoginAt' : [] | [TimeRangeFilter],
    'inviter' : [] | [Array<Principal>],
    'verifiedEmail' : [] | [boolean],
    'createdAt' : [] | [TimeRangeFilter],
    'role' : [] | [Role],
    'search' : [] | [string],
    'updatedAt' : [] | [TimeRangeFilter],
    'identitySyncedAt' : [] | [TimeRangeFilter],
  },
}
export interface AdminUsersPage {
  'total' : [] | [bigint],
  'data' : Array<AdminUserListItem>,
}
export interface AmbassadorChain {
  'l1' : [] | [Principal],
  'l2' : [] | [Principal],
}
export type AmbassadorPayoutStatus = { 'pending' : null } |
  { 'skipped' : null } |
  { 'completed' : null } |
  { 'failed' : string };
export type ApplyReferralCodeResult = { 'ok' : null } |
  { 'storageError' : string } |
  { 'userNotFound' : null } |
  { 'selfReferral' : null } |
  { 'referralCodeNotFound' : null } |
  { 'alreadyApplied' : null };
export type AssetDownloadStatus = { 'Error' : string } |
  {
    'Downloading' : {
      'chunksCompleted' : bigint,
      'chunksError' : bigint,
      'chunksTotal' : bigint,
    }
  } |
  { 'Completed' : { 'size' : bigint } } |
  { 'NotStarted' : null };
export interface AssetFullStatus {
  'sha256' : [] | [Uint8Array],
  'contentType' : string,
  'name' : string,
  'size' : bigint,
  'downloadStatus' : AssetDownloadStatus,
  'extractionStatus' : [] | [ExtractionStatus],
}
export type AssetLocator = { 'Contract' : string } |
  { 'Mint' : string } |
  { 'Native' : null };
export interface AvatarRef {
  'sha256' : Uint8Array,
  'contentType' : string,
  'size' : bigint,
  'updatedAt' : Time,
  'blobId' : Uint8Array,
  'rootHash' : string,
}
export interface BalanceEntry { 'tokenId' : TokenId, 'balance' : bigint }
export interface CallbackStreamingStrategy {
  'token' : StreamingToken,
  'callback' : [Principal, string],
}
export type ChainConfig = { 'Evm' : EvmChainConfig } |
  { 'Solana' : SolanaChainConfig };
export type CmcOpKind = { 'CreateCanister' : null } |
  { 'TopUp' : null };
export type CmcOpRetryResult = { 'scheduled' : { 'canisterId' : Principal } } |
  { 'resolved' : null } |
  { 'refunded' : { 'receipt' : [] | [RefundReceipt] } } |
  { 'blockedByRefund' : null } |
  { 'notFound' : null } |
  { 'stillAmbiguous' : { 'attempts' : bigint } };
export type CmcOpSource = { 'storageCreation' : { 'creationId' : bigint } } |
  { 'selfTopUp' : null } |
  { 'userTopUp' : { 'canisterId' : Principal } } |
  { 'autoTopUp' : { 'canisterId' : Principal } };
export type CorrelationId = string;
export interface CreateProfileArgs {
  'username' : string,
  'displayName' : [] | [string],
}
export interface CreationListItem {
  'id' : bigint,
  'status' : CreationStatus,
  'completedAt' : [] | [Time],
  'licensePaymentId' : [] | [string],
  'owner' : Principal,
  'createdAt' : Time,
  'lastUpgradeError' : [] | [string],
  'isUpgrade' : boolean,
  'statusTag' : string,
  'subnetId' : [] | [Principal],
  'upgradeIncludesFrontend' : boolean,
  'hasFrontendInstallDiagnostics' : boolean,
  'ambassadorPayoutStatusTag' : string,
  'releaseTag' : string,
  'lastEventAt' : [] | [Time],
  'hasEvents' : boolean,
  'installedReleaseTag' : [] | [string],
  'canisterId' : [] | [Principal],
}
export type CreationStatus = { 'Failed' : string } |
  { 'UpdatingControllers' : { 'canisterId' : Principal } } |
  { 'UpgradingWasm' : { 'progress' : Progress, 'canisterId' : Principal } } |
  { 'CanisterCreated' : { 'canisterId' : Principal } } |
  { 'RevokingInstallerPermission' : { 'canisterId' : Principal } } |
  { 'CheckingBalance' : null } |
  {
    'UploadingFrontend' : { 'progress' : Progress, 'canisterId' : Principal }
  } |
  { 'TransferringICP' : { 'amount' : bigint } } |
  { 'NotifyingCMC' : { 'blockIndex' : bigint } } |
  { 'ProcessingPayment' : PaymentPhase } |
  { 'ReinstallingWasm' : { 'progress' : Progress, 'canisterId' : Principal } } |
  {
    'UpgradingFrontend' : { 'progress' : Progress, 'canisterId' : Principal }
  } |
  { 'Completed' : { 'canisterId' : Principal } } |
  { 'InstallingWasm' : { 'progress' : Progress, 'canisterId' : Principal } } |
  { 'Pending' : null };
export type DeleteStorageError = { 'NotFailed' : null } |
  { 'NotFound' : null } |
  { 'NotOwner' : null };
export interface DistributionLogOptions { 'offset' : bigint, 'limit' : bigint }
export interface DistributionRecord {
  'id' : bigint,
  'status' : DistributionStatus,
  'tokenId' : TokenId,
  'l1Amount' : bigint,
  'transfers' : Array<TransferRecord>,
  'l2Amount' : bigint,
  'ambassadorL1' : [] | [Principal],
  'ambassadorL2' : [] | [Principal],
  'totalAmount' : bigint,
  'paymentId' : string,
  'timestamp' : bigint,
  'payer' : Principal,
  'treasuryAmount' : bigint,
}
export type DistributionStatus = { 'completed' : null } |
  { 'partial' : null };
export type DurablePolicyStatus = { 'cancelled' : null } |
  { 'armed' : null } |
  { 'released' : null } |
  { 'matured' : null } |
  { 'grace' : null };
export type DurablePolicyTrigger = { 'manualRelease' : null } |
  { 'date' : { 'releaseAt' : Time } } |
  {
    'inactivity' : { 'inactiveForNs' : bigint, 'gracePeriodNs' : [] | [bigint] }
  };
export interface EmailClaim {
  'principalGrantId' : bigint,
  'principal' : Principal,
  'origin' : EmailClaimOrigin,
  'claimedAt' : Time,
}
export type EmailClaimOrigin = { 'storage' : null } |
  { 'rabbithole' : null };
export interface EmailClaimState {
  'storage' : [] | [EmailClaim],
  'rabbithole' : [] | [EmailClaim],
}
export interface EnsureStorageCyclesForUploadRequest {
  'activeUploadedBytes' : bigint,
  'currentBalance' : bigint,
  'projectedCapacityBytes' : bigint,
  'postWriteFreezingReserve' : bigint,
  'remainingUploadBytes' : bigint,
  'requiredBalance' : bigint,
}
export interface EnvPair { 'value' : string, 'name' : string }
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface EvmChainConfig {
  'evmRpcCanisterId' : string,
  'assets' : Array<SupportedAsset>,
  'rpcUrls' : Array<string>,
  'chainId' : bigint,
  'networkId' : string,
}
export type ExtractionStatus = { 'Idle' : null } |
  { 'Complete' : Array<FileMetadata> } |
  { 'Decoding' : { 'total' : bigint, 'processed' : bigint } };
export interface FileMetadata {
  'key' : string,
  'sha256' : Uint8Array,
  'contentType' : string,
  'size' : bigint,
}
export interface FrontendInstallDiagnostics {
  'totalFiles' : bigint,
  'completedAt' : [] | [Time],
  'startedAt' : Time,
  'changedDeletedFiles' : bigint,
  'batchesProcessed' : bigint,
  'skippedBytes' : bigint,
  'uploadedBytes' : bigint,
  'error' : [] | [string],
  'updatedAt' : Time,
  'stage' : string,
  'skippedFiles' : bigint,
  'processedBytes' : bigint,
  'uploadedFiles' : bigint,
  'staleDeletedFiles' : bigint,
  'totalBytes' : bigint,
  'processedFiles' : bigint,
  'batchesTotal' : bigint,
}
export interface GetCreationsResponse {
  'total' : [] | [bigint],
  'data' : Array<CreationListItem>,
  'instructions' : bigint,
}
export interface GetLicensesResponse {
  'total' : [] | [bigint],
  'data' : Array<License>,
  'instructions' : bigint,
}
export interface GetSubscriptionsResponse {
  'total' : [] | [bigint],
  'data' : Array<Subscription>,
  'instructions' : bigint,
}
export type Header = [string, string];
export interface HttpHeader { 'value' : string, 'name' : string }
export interface HttpRequestResult {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export type IdentityAttributesSyncError = { 'expired' : null } |
  { 'malformedPayload' : null } |
  { 'verifiedEmailRequired' : null } |
  { 'attributesNotFound' : null };
export type IdentityAttributesSyncResult = { 'ok' : null } |
  { 'err' : IdentityAttributesSyncError };
export interface ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export type InitArgs = { 'v1' : InitArgsV1 };
export interface InitArgsV1 {
  'icpaySecretKey' : [] | [Uint8Array],
  'treasury' : [] | [TreasuryInitArgsV1],
}
export interface KnownWasmHash {
  'hash' : Uint8Array,
  'releaseTag' : string,
  'registeredAt' : Time,
}
export interface License {
  'receipt' : PaymentReceipt,
  'owner' : Principal,
  'createdAt' : Time,
  'statusTag' : string,
  'storageEntitlement' : StorageLicenseEntitlement,
  'canisterId' : [] | [Principal],
}
export interface LicenseStorageLimits {
  'includedBytes' : bigint,
  'maxFileBytes' : bigint,
}
export interface ListCreationsOptions {
  'pagination' : { 'offset' : bigint, 'limit' : bigint },
  'count' : boolean,
  'sort' : Array<[string, SortDirection]>,
  'filter' : {
    'id' : [] | [Array<bigint>],
    'completedAt' : [] | [TimeRangeFilter],
    'owner' : [] | [Array<Principal>],
    'createdAt' : [] | [TimeRangeFilter],
    'ambassadorPayoutStatus' : [] | [Array<string>],
    'hasLicense' : [] | [boolean],
    'hasCanister' : [] | [boolean],
    'statusTag' : [] | [Array<string>],
    'releaseTag' : [] | [string],
    'canisterId' : [] | [Array<Principal>],
  },
}
export interface ListLicensesOptions {
  'pagination' : { 'offset' : bigint, 'limit' : bigint },
  'count' : boolean,
  'sort' : Array<[string, SortDirection]>,
  'filter' : {
    'id' : [] | [Array<bigint>],
    'owner' : [] | [Array<Principal>],
    'createdAt' : [] | [TimeRangeFilter],
    'hasCanister' : [] | [boolean],
    'statusTag' : [] | [Array<string>],
    'paymentId' : [] | [string],
    'paidAt' : [] | [TimeRangeFilter],
    'canisterId' : [] | [Array<Principal>],
  },
}
export interface ListNotificationsArgs {
  'limit' : bigint,
  'afterId' : [] | [bigint],
  'unreadOnly' : boolean,
}
export interface ListOptions {
  'pagination' : { 'offset' : bigint, 'limit' : bigint },
  'count' : boolean,
  'sort' : Array<[string, SortDirection]>,
  'filter' : {
    'status' : [] | [Array<Status>],
    'expiresAt' : [] | [{ 'max' : [] | [bigint], 'min' : [] | [bigint] }],
    'userId' : [] | [Array<Principal>],
    'plan' : [] | [Array<Plan>],
  },
}
export type NotificationPayload = {
    'storageAccessRevoked' : {
      'accessClass' : [] | [AccessClass],
      'canisterId' : Principal,
    }
  } |
  { 'backendLowCycles' : { 'threshold' : bigint, 'current' : bigint } } |
  { 'topUpCompleted' : { 'canisterId' : Principal, 'cyclesAmount' : bigint } } |
  { 'depositReceived' : { 'tokenId' : string, 'amount' : bigint } } |
  {
    'cmcNotifyStuck' : {
      'id' : bigint,
      'blockIndex' : bigint,
      'caller' : Principal,
      'canisterId' : Principal,
      'reason' : string,
    }
  } |
  {
    'storageAccessRequestCancelled' : {
      'requestId' : bigint,
      'requester' : Principal,
      'canisterId' : Principal,
    }
  } |
  {
    'ambassadorPayoutFailed' : {
      'owner' : Principal,
      'creationId' : bigint,
      'reason' : string,
    }
  } |
  { 'subscriptionExpired' : null } |
  {
    'storageInviteCreated' : {
      'source' : AccessSource,
      'grantId' : bigint,
      'accessClass' : AccessClass,
      'canisterId' : Principal,
    }
  } |
  { 'autoRenewFailed' : { 'reason' : string } } |
  {
    'storageAccessGranted' : {
      'source' : AccessSource,
      'grantId' : [] | [bigint],
      'accessClass' : AccessClass,
      'canisterId' : Principal,
    }
  } |
  { 'topUpFailed' : { 'canisterId' : Principal, 'reason' : string } } |
  {
    'storageInviteCancelled' : { 'grantId' : bigint, 'canisterId' : Principal }
  } |
  { 'storageRecoveryOwnerAdded' : { 'canisterId' : Principal } } |
  {
    'autoTopUpCompleted' : { 'canisterId' : Principal, 'cyclesAmount' : bigint }
  } |
  {
    'creationRefunded' : {
      'tokenId' : string,
      'owner' : Principal,
      'creationId' : bigint,
      'amount' : bigint,
    }
  } |
  {
    'treasuryIcpLow' : {
      'currentBalance' : bigint,
      'reserve' : bigint,
      'required' : bigint,
    }
  } |
  { 'storageRecoveryOwnerRemoved' : { 'canisterId' : Principal } } |
  {
    'storageInviteClaimed' : {
      'principal' : Principal,
      'source' : AccessSource,
      'grantId' : bigint,
      'accessClass' : AccessClass,
      'canisterId' : Principal,
    }
  } |
  {
    'subscriptionRenewed' : {
      'expiresAt' : [] | [bigint],
      'plan' : { 'Pro' : null } |
        { 'Free' : null },
    }
  } |
  {
    'storageAccessRequestCreated' : {
      'requestId' : bigint,
      'requester' : Principal,
      'canisterId' : Principal,
    }
  } |
  { 'balanceLow' : { 'requiredAmount' : bigint } } |
  {
    'paymentReceived' : {
      'tokenId' : string,
      'amount' : bigint,
      'purpose' : string,
    }
  } |
  {
    'subscriptionActivated' : { 'plan' : { 'Pro' : null } | { 'Free' : null } }
  } |
  {
    'storageAccessRequestResolved' : {
      'status' : AccessRequestStatus,
      'requestId' : bigint,
      'canisterId' : Principal,
    }
  } |
  { 'updateAvailable' : { 'releaseTag' : string, 'canisterId' : Principal } } |
  { 'autoTopUpFailed' : { 'canisterId' : Principal, 'reason' : string } } |
  {
    'lowCycles' : {
      'estimatedDaysLeft' : bigint,
      'severity' : { 'warning' : null } |
        { 'critical' : null },
      'remaining' : bigint,
      'canisterId' : Principal,
    }
  } |
  { 'backendSelfTopUpFailed' : { 'reason' : string } };
export type NotificationSeverity = { 'warning' : null } |
  { 'info' : null } |
  { 'critical' : null } |
  { 'success' : null };
export type NotificationSource = { 'storage' : null } |
  { 'backend' : null };
export interface NotificationsPage {
  'data' : Array<StoredNotification>,
  'unreadCount' : bigint,
}
export type OwnerActivityOrigin = { 'storage' : null } |
  { 'rabbithole' : null } |
  { 'backend' : null };
export type OwnerActivityRole = { 'recoveryOwner' : null } |
  { 'accountOwner' : null };
export type PaymentPhase = { 'CheckingBalances' : null } |
  { 'Starting' : null } |
  { 'Queueing' : null } |
  { 'FetchingRates' : null } |
  { 'Charging' : { 'tokenId' : TokenId, 'amount' : bigint } } |
  { 'RecordingLicense' : null };
export interface PaymentReceipt {
  'status' : PaymentStatus,
  'tokenId' : TokenId,
  'paymentId' : string,
  'amount' : bigint,
  'paidAt' : Time,
}
export type PaymentStatus = { 'completed' : null } |
  {
    'refunded' : {
      'at' : Time,
      'blockIndex' : [] | [bigint],
      'reason' : string,
    }
  };
export interface PendingCmcOp {
  'id' : bigint,
  'lastAttemptAt' : [] | [Time],
  'source' : CmcOpSource,
  'kind' : CmcOpKind,
  'createdAt' : Time,
  'attempts' : bigint,
  'blockIndex' : bigint,
  'lastError' : string,
  'refund' : [] | [RefundContext],
}
export interface PendingRefund {
  'tokenId' : TokenId,
  'userId' : Principal,
  'createdAt' : bigint,
  'amount' : bigint,
  'reason' : string,
}
export type Plan = { 'Pro' : null } |
  { 'Free' : null };
export interface PrepareAvatarUploadArgs {
  'content' : Uint8Array,
  'contentType' : string,
}
export interface PrepareAvatarUploadResult {
  'sha256' : Uint8Array,
  'contentType' : string,
  'size' : bigint,
  'updatedAt' : Time,
  'blobId' : Uint8Array,
  'rootHash' : string,
}
export interface Profile {
  'id' : Principal,
  'referralCode' : [] | [string],
  'username' : string,
  'displayName' : [] | [string],
  'createdAt' : Time,
  'updatedAt' : Time,
  'avatarRef' : [] | [AvatarRef],
}
export interface Progress { 'total' : bigint, 'processed' : bigint }
export interface PublicProfileLookup {
  'principal' : Principal,
  'profile' : [] | [PublicProfileSummary],
}
export interface PublicProfileSummary {
  'username' : string,
  'displayName' : [] | [string],
  'avatarRef' : [] | [AvatarRef],
}
export type PurchaseError = { 'ActivationFailed' : string } |
  { 'InvalidPlan' : string } |
  { 'ChargeFailed' : string } |
  { 'AlreadyActive' : null } |
  { 'InsufficientFunds' : { 'required' : bigint } };
export interface Rabbithole {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [ImmutableObjectStorageRefillInformation]],
    ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result_9>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'activateSubscription' : ActorMethod<
    [Principal, Plan, [] | [bigint]],
    undefined
  >,
  /**
   * / Register an externally-deployed storage canister with this backend.
   * /
   * / Required: caller must be a controller of `canisterId`, and the
   * / canister's `module_hash` must match one of the known Rabbithole
   * / storage WASM releases.
   * /
   * / Ownership semantics — important:
   * /   - `record.owner = caller` (the controller who registered it).
   * /     This is the *billing owner* in our backend — who pays for
   * /     managed services (auto-topup, notifications, listStorages).
   * /   - The storage canister's internal `initArgs.owner` (who holds
   * /     VetKey root permissions, data access) can be a DIFFERENT
   * /     principal — controller ≠ data owner on IC.
   * /   - That divergence is intentional. A controller registers the
   * /     canister for managed services; data access stays gated by
   * /     the storage canister's permission rules (see
   * /     `createAccessBatch` / `revokeAccessBatch`).
   * /
   * / Backend id trust — not verified:
   * /   - Caller could have set `PUBLIC_CANISTER_ID:rabbithole-backend`
   * /     env var to a different backend, in which case the canister's
   * /     subscription gates and auto-topup calls would route elsewhere.
   * /     That's self-sabotage (controller loses Pro features), not a
   * /     risk for us — so we don't verify.
   * /
   * / Storage license entitlement is attached only through the paid creation
   * / flow. Imported canisters do not receive included encrypted storage quota.
   */
  'addStorage' : ActorMethod<[Principal, Uint8Array], Result_8>,
  'adminGetUserWalletMeta' : ActorMethod<
    [Principal],
    {
      'walletAddresses' : {
        'icSubaccount' : Uint8Array,
        'solAddress' : [] | [string],
        'evmAddress' : [] | [string],
      },
      'settings' : UserSettings,
    }
  >,
  'adminListUsers' : ActorMethod<[AdminUserListOptions], AdminUsersPage>,
  'adminRebuildKnownWasmHashesFromDownloadedReleases' : ActorMethod<[], bigint>,
  'adminRegisterWasmHash' : ActorMethod<[Uint8Array, string], undefined>,
  'adminSyncBlobStorageCashierAdminAccess' : ActorMethod<[], undefined>,
  'applyReferralCode' : ActorMethod<[string], ApplyReferralCodeResult>,
  'checkSubscription' : ActorMethod<[Uint8Array], SubscriptionCheckResult>,
  'claimVerifiedEmailAccess' : ActorMethod<[], IdentityAttributesSyncResult>,
  'clearAvatar' : ActorMethod<[], undefined>,
  'commitAvatarUpload' : ActorMethod<[string], AvatarRef>,
  'createProfile' : ActorMethod<[CreateProfileArgs], Uint8Array>,
  'deleteProfile' : ActorMethod<[], undefined>,
  'deleteStorage' : ActorMethod<[bigint], Result_7>,
  'dismissPendingCmcOp' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'notFound' : null }
  >,
  'ensureStorageCyclesForUpload' : ActorMethod<
    [EnsureStorageCyclesForUploadRequest],
    Result_6
  >,
  'ensureUser' : ActorMethod<[[] | [string]], undefined>,
  'flushPaymentQueue' : ActorMethod<[], undefined>,
  'getAmbassadorChainQuery' : ActorMethod<[], AmbassadorChain>,
  'getBackendCyclesBalance' : ActorMethod<[], bigint>,
  'getCmcRecoveryStats' : ActorMethod<[], StatsView>,
  /**
   * / Full creation detail with timeline and diagnostics. Non-admin callers can
   * / only read their own records.
   */
  'getCreationDetail' : ActorMethod<[bigint], [] | [StorageCreationRecord]>,
  'getDistributionLog' : ActorMethod<
    [DistributionLogOptions],
    Array<DistributionRecord>
  >,
  'getEvmAddress' : ActorMethod<[], [] | [string]>,
  'getMyWalletAddresses' : ActorMethod<
    [],
    {
      'icSubaccount' : Uint8Array,
      'solAddress' : [] | [string],
      'evmAddress' : [] | [string],
    }
  >,
  'getPendingRefunds' : ActorMethod<[], Array<PendingRefund>>,
  'getProfile' : ActorMethod<[], [] | [Profile]>,
  'getPublicProfiles' : ActorMethod<
    [Array<Principal>],
    Array<PublicProfileLookup>
  >,
  'getSettings' : ActorMethod<[], UserSettings>,
  'getSolAddress' : ActorMethod<[], [] | [string]>,
  /**
   * / Admin-only recovery for non-terminal creations that lost their transient
   * / queue/timer state. Upgrades are reverted to Completed; initial creations
   * / become Failed and can then use the regular recoverFailedStorage flow.
   */
  'getStorageFundingStatus' : ActorMethod<[], StorageFundingStatus>,
  'getStorageReleaseAdminStatus' : ActorMethod<[], ReleasesFullStatus>,
  'getStorageUpgradePlan' : ActorMethod<
    [Principal, StorageReleaseState],
    Result_5
  >,
  'getSubscription' : ActorMethod<[], [] | [Subscription]>,
  'getTreasuryBalances' : ActorMethod<[], Array<BalanceEntry>>,
  'getTreasuryWalletAddresses' : ActorMethod<
    [],
    {
      'icSubaccount' : Uint8Array,
      'solAddress' : [] | [string],
      'evmAddress' : [] | [string],
    }
  >,
  'getUnreadNotificationCount' : ActorMethod<[], bigint>,
  'getUser' : ActorMethod<[], [] | [User]>,
  'http_request' : ActorMethod<[RawQueryHttpRequest], RawQueryHttpResponse>,
  'http_request_update' : ActorMethod<
    [RawUpdateHttpRequest],
    RawUpdateHttpResponse
  >,
  'isAdmin' : ActorMethod<[Principal], boolean>,
  'isKnownWasmHash' : ActorMethod<[Uint8Array], boolean>,
  'isStorageDeployerRunning' : ActorMethod<[], boolean>,
  /**
   * / List creations with optional filter + pagination. Callers omit `options`
   * / (`[]`) to get the caller's own creations with defaults. Non-admins are
   * / pinned to their own `owner` regardless of filter.owner passed in.
   * / Records include current status/progress, but omit full timeline,
   * / diagnostics and recovery payload. Use `getCreationDetail` for a row's
   * / popover/details panel.
   */
  'listCreations' : ActorMethod<
    [[] | [ListCreationsOptions]],
    GetCreationsResponse
  >,
  'listKnownWasmHashes' : ActorMethod<[], Array<KnownWasmHash>>,
  /**
   * / List licenses with optional filter + pagination. Callers omit `options`
   * / (`[]`) to get the caller's own licenses with defaults. Non-admins are
   * / pinned to their own `owner` regardless of filter.owner passed in.
   */
  'listLicenses' : ActorMethod<
    [[] | [ListLicensesOptions]],
    GetLicensesResponse
  >,
  'listNotifications' : ActorMethod<[ListNotificationsArgs], NotificationsPage>,
  'listPendingCmcOps' : ActorMethod<
    [{ 'limit' : [] | [bigint], 'afterId' : [] | [bigint] }],
    Array<PendingCmcOp>
  >,
  'listSharedWithMeStorageViews' : ActorMethod<
    [],
    Array<SharedStorageAccessView>
  >,
  'listSharedWithMeStorages' : ActorMethod<[], Array<SharedStorageAccess>>,
  'listStorages' : ActorMethod<[], Array<StorageInfo>>,
  'listSubscriptions' : ActorMethod<[ListOptions], GetSubscriptionsResponse>,
  'listUsersByRole' : ActorMethod<[Role], Array<Principal>>,
  'markAllNotificationsRead' : ActorMethod<[], undefined>,
  'markNotificationsRead' : ActorMethod<[Array<bigint>], undefined>,
  'markNotificationsReadUpTo' : ActorMethod<[bigint], undefined>,
  'onStorageAccessChanged' : ActorMethod<[StorageAccessChanged], undefined>,
  'onStorageLowCycles' : ActorMethod<
    [bigint, bigint, { 'warning' : null } | { 'critical' : null }],
    undefined
  >,
  'prepareAvatarUpload' : ActorMethod<
    [PrepareAvatarUploadArgs],
    PrepareAvatarUploadResult
  >,
  'prepareStorageRelease' : ActorMethod<[string], Result_2>,
  'processPendingRefunds' : ActorMethod<[], bigint>,
  /**
   * / Purchase a license and kick off storage creation. Returns the creation
   * / id immediately — charge + deploy run asynchronously on the orchestrator
   * / side. Frontend polls `listCreations({filter.id=[id]})` to follow progress.
   * /
   * / The initial record is created with `#ProcessingPayment(#Starting)`. A
   * / detached Timer picks up the flow on the next tick and transitions the
   * / record through all payment phases (`FetchingRates`, `Charging`,
   * / `RecordingLicense`, `Queueing`) before handing off to the
   * / unified deploy queue.
   */
  'purchaseLicenseAndCreateStorage' : ActorMethod<
    [StorageBackendType, StorageVetKeyLevel],
    Result_4
  >,
  'purchaseSubscription' : ActorMethod<[Plan], Result_3>,
  'queryExpiredSubscriptions' : ActorMethod<
    [],
    Array<[Principal, Subscription]>
  >,
  'queryExpiringSubscriptions' : ActorMethod<
    [bigint],
    Array<[Principal, Subscription]>
  >,
  /**
   * / Recover a failed storage creation. Owner OR admin may call.
   * /
   * / Strategies:
   * /   - `#resume`: re-queue the deploy. Checkpoint-aware —
   * /     * `record.canisterId == null`  → `#CreateCanister` (treasury ICP intact)
   * /     * `record.canisterId == ?id`   → `#LinkCanister(id)` (point-of-no-return crossed)
   * /     Preserves original `initArg` + `envPairs`. Refuses if the license was refunded.
   * /   - `#refund`: ICP goes back to the owner, license flips `#refunded`,
   * /     creation record is deleted. Only allowed BEFORE `#CanisterCreated` —
   * /     once the canister exists, cycles can't be recovered.
   * /
   * / Both strategies share the same per-creationId lock (`creationLocks`), so
   * / concurrent recover calls on the same id serialize: the loser sees
   * / "another refund or resume is in progress".
   */
  'recoverFailedStorage' : ActorMethod<[bigint, RecoveryStrategy], Result_2>,
  /**
   * / Admin-only recovery for non-terminal creations that lost their transient
   * / queue/timer state. Upgrades are reverted to Completed; initial creations
   * / become Failed and can then use the regular recoverFailedStorage flow.
   */
  'recoverStuckCreation' : ActorMethod<[bigint], Result_2>,
  'refreshStorageReleaseIndex' : ActorMethod<[], undefined>,
  /**
   * / Owner-or-admin repair for failed initial creations whose canister already
   * / exists but cannot be resumed with a plain install. Reinstalls the latest
   * / storage WASM, so completed storages and failed upgrades are rejected.
   */
  'reinstallFailedStorageWasm' : ActorMethod<[bigint], Result_2>,
  'renewSubscription' : ActorMethod<
    [Principal, Plan, [] | [bigint]],
    undefined
  >,
  /**
   * / Admin-only retry for a creation whose deferred ambassador payout
   * / landed in `#failed`. Re-invokes the payout; on success the record's
   * / `ambassadorPayoutStatus` flips to `#completed` (or back to `#failed`
   * / with the new reason). Idempotent via the treasury dedup set — if
   * / the payout had actually succeeded and only the status-stamp failed,
   * / treasury returns `#AlreadyProcessed` which we translate to `#completed`.
   */
  'retryAmbassadorPayout' : ActorMethod<[bigint], Result_2>,
  'retryPendingCmcOp' : ActorMethod<[bigint], CmcOpRetryResult>,
  'searchUserDirectory' : ActorMethod<
    [string, bigint],
    Array<UserDirectoryItem>
  >,
  'setUserRole' : ActorMethod<[Principal, Role], undefined>,
  'startStorageDeployer' : ActorMethod<[], undefined>,
  'startStorageUpgrade' : ActorMethod<
    [Principal, string, StorageReleaseState],
    Result_1
  >,
  'stopStorageDeployer' : ActorMethod<[], undefined>,
  'topUpFromBalance' : ActorMethod<[Principal, bigint], Result>,
  'transformGitHubReleaseResponse' : ActorMethod<
    [TransformArg],
    HttpRequestResult
  >,
  'triggerAutoRenewals' : ActorMethod<[], undefined>,
  'triggerExpireOverdue' : ActorMethod<[], Array<Principal>>,
  'triggerSelfTopUp' : ActorMethod<[], undefined>,
  'updateProfile' : ActorMethod<[UpdateProfileArgs], undefined>,
  'updateSettings' : ActorMethod<[UserSettings], undefined>,
  'usernameExists' : ActorMethod<[string], boolean>,
  'withdraw' : ActorMethod<[WithdrawArgs], WithdrawResult>,
  'withdrawFromTreasury' : ActorMethod<[WithdrawArgs], WithdrawResult>,
}
export interface RawQueryHttpRequest {
  'url' : string,
  'method' : string,
  'body' : Uint8Array,
  'headers' : Array<Header>,
  'certificate_version' : [] | [number],
}
export interface RawQueryHttpResponse {
  'body' : Uint8Array,
  'headers' : Array<Header>,
  'upgrade' : [] | [boolean],
  'streaming_strategy' : [] | [StreamingStrategy],
  'status_code' : number,
}
export interface RawUpdateHttpRequest {
  'url' : string,
  'method' : string,
  'body' : Uint8Array,
  'headers' : Array<Header>,
}
export interface RawUpdateHttpResponse {
  'body' : Uint8Array,
  'headers' : Array<Header>,
  'streaming_strategy' : [] | [StreamingStrategy],
  'status_code' : number,
}
export type RecoveryStrategy = { 'resume' : null } |
  { 'refund' : null };
export interface RefundContext {
  'tokenId' : TokenId,
  'payer' : Principal,
  'amount' : bigint,
}
export type RefundNetwork = { 'ic' : null } |
  { 'evm' : null } |
  { 'solana' : null };
export interface RefundReceipt {
  'at' : Time,
  'tokenId' : TokenId,
  'recipient' : Principal,
  'network' : RefundNetwork,
  'reference' : RefundReference,
  'amount' : bigint,
}
export type RefundReference = { 'signature' : string } |
  { 'blockIndex' : bigint } |
  { 'txHash' : string };
export interface ReleaseArtifactManifest {
  'sha256' : [] | [string],
  'name' : string,
  'size' : [] | [bigint],
}
export interface ReleaseFullStatus {
  'tagName' : string,
  'isDownloaded' : boolean,
  'name' : string,
  'createdAt' : Time,
  'assets' : Array<AssetFullStatus>,
  'htmlUrl' : string,
  'publishedAt' : [] | [Time],
  'manifestError' : [] | [string],
  'isDeploymentReady' : boolean,
  'manifest' : [] | [StorageReleaseManifest],
  'draft' : boolean,
  'prerelease' : boolean,
}
export interface ReleaseNoteSection {
  'title' : string,
  'items' : Array<string>,
}
export interface ReleaseNotes {
  'source' : string,
  'summary' : string,
  'sections' : Array<ReleaseNoteSection>,
}
export interface ReleaseUpgradeManifest {
  'compatibleFrom' : Array<string>,
  'argStrategy' : string,
}
export interface ReleasesFullStatus {
  'releasesCount' : bigint,
  'pendingDownloads' : bigint,
  'hasDeploymentReadyRelease' : boolean,
  'hasDownloadedRelease' : boolean,
  'releases' : Array<ReleaseFullStatus>,
  'completedDownloads' : bigint,
}
export type Result = { 'ok' : { 'cyclesAdded' : bigint } } |
  { 'err' : string };
export type Result_1 = { 'ok' : null } |
  { 'err' : UpgradeStorageError };
export type Result_2 = { 'ok' : null } |
  { 'err' : string };
export type Result_3 = { 'ok' : null } |
  { 'err' : PurchaseError };
export type Result_4 = { 'ok' : bigint } |
  { 'err' : PurchaseError };
export type Result_5 = { 'ok' : StorageReleaseOptionsResult } |
  { 'err' : UpgradeStorageError };
export type Result_6 = {
    'ok' : { 'cyclesAdded' : [] | [bigint], 'requiredBalance' : bigint }
  } |
  { 'err' : string };
export type Result_7 = { 'ok' : null } |
  { 'err' : DeleteStorageError };
export type Result_8 = { 'ok' : bigint } |
  { 'err' : AddStorageError };
export type Result_9 = { 'ok' : null } |
  { 'err' : Error };
export type Role = { 'admin' : null } |
  { 'moderator' : null } |
  { 'user' : null };
export interface SharedStorageAccess {
  'storageCanisterId' : Principal,
  'activeAccessClasses' : Array<AccessClass>,
  'lastStorageEventId' : bigint,
  'firstSeenAt' : Time,
  'pendingAccessClasses' : Array<AccessClass>,
  'updatedAt' : Time,
  'accountOwner' : Principal,
  'pendingGrantIds' : Array<bigint>,
  'lastCorrelationId' : [] | [string],
  'lastSource' : [] | [AccessSource],
}
export interface SharedStorageAccessView {
  'access' : SharedStorageAccess,
  'storageStatus' : [] | [CreationStatus],
  'updateAvailable' : [] | [UpdateInfo],
}
export interface SolanaChainConfig {
  'solRpcCanisterId' : string,
  'assets' : Array<SupportedAsset>,
  'rpcUrl' : [] | [string],
  'networkId' : string,
}
export type SortDirection = { 'Descending' : null } |
  { 'Ascending' : null };
export type SourceEventRef = {
    'storage' : { 'storageEventId' : bigint, 'canisterId' : Principal }
  } |
  { 'backend' : { 'kind' : string } };
export interface StatsView {
  'totalResolved' : bigint,
  'totalRefunded' : bigint,
  'totalDismissed' : bigint,
  'totalCreated' : bigint,
}
export type Status = { 'Active' : null } |
  { 'Cancelled' : null } |
  { 'Expired' : null };
export interface StatusEvent { 'status' : CreationStatus, 'timestamp' : Time }
export interface StorageAccessChanged {
  'storageCanisterId' : Principal,
  'storageEventId' : bigint,
  'event' : StorageAccessLifecycleEvent,
  'correlationId' : [] | [CorrelationId],
  'accountOwner' : Principal,
}
export type StorageAccessLifecycleEvent = {
    'accessRequestResolved' : {
      'status' : AccessRequestStatus,
      'requestId' : bigint,
      'requester' : Principal,
    }
  } |
  {
    'durablePolicyCreated' : {
      'status' : DurablePolicyStatus,
      'trigger' : DurablePolicyTrigger,
      'policyId' : bigint,
    }
  } |
  {
    'accessRequestCreated' : { 'requestId' : bigint, 'requester' : Principal }
  } |
  {
    'recoveryControllerRegistered' : {
      'principal' : Principal,
      'previous' : [] | [Principal],
    }
  } |
  {
    'pendingGrantCreated' : {
      'source' : AccessSource,
      'recipient' : [] | [Principal],
      'emailCommitment' : [] | [Uint8Array],
      'grantId' : bigint,
      'accessClass' : AccessClass,
    }
  } |
  {
    'ownerActivityRecorded' : {
      'principal' : Principal,
      'origin' : OwnerActivityOrigin,
      'role' : OwnerActivityRole,
    }
  } |
  { 'durablePolicyReleased' : { 'policyId' : bigint } } |
  { 'recoveryControllerCleared' : { 'principal' : Principal } } |
  { 'durablePolicyMatured' : { 'policyId' : bigint } } |
  { 'recoveryOwnerAdded' : { 'principal' : Principal } } |
  {
    'pendingGrantClaimed' : {
      'principal' : Principal,
      'emailClaimState' : [] | [EmailClaimState],
      'source' : AccessSource,
      'grantId' : bigint,
      'claimOrigin' : [] | [EmailClaimOrigin],
      'accessClass' : AccessClass,
    }
  } |
  { 'durablePolicyCancelled' : { 'policyId' : bigint } } |
  {
    'accessRequestCancelled' : { 'requestId' : bigint, 'requester' : Principal }
  } |
  {
    'principalGrantCreated' : {
      'principal' : Principal,
      'source' : AccessSource,
      'grantId' : [] | [bigint],
      'accessClass' : AccessClass,
    }
  } |
  {
    'pendingGrantCancelled' : {
      'recipient' : [] | [Principal],
      'emailCommitment' : [] | [Uint8Array],
      'grantId' : bigint,
    }
  } |
  { 'durablePolicyGraceStarted' : { 'policyId' : bigint } } |
  {
    'principalGrantRevoked' : {
      'principal' : Principal,
      'accessClass' : [] | [AccessClass],
    }
  } |
  { 'recoveryOwnerRemoved' : { 'principal' : Principal } };
export type StorageBackendType = { 'OnChain' : null } |
  { 'BlobStorage' : null };
export interface StorageCreationRecord {
  'id' : bigint,
  'status' : CreationStatus,
  'completedAt' : [] | [Time],
  'licensePaymentId' : [] | [string],
  'owner' : Principal,
  'wasmHash' : [] | [Uint8Array],
  'createdAt' : Time,
  'ambassadorPayoutStatus' : AmbassadorPayoutStatus,
  'lastUpgradeError' : [] | [string],
  'isUpgrade' : boolean,
  'statusTag' : string,
  'subnetId' : [] | [Principal],
  'upgradeIncludesFrontend' : boolean,
  'ambassadorPayoutStatusTag' : string,
  'events' : Array<StatusEvent>,
  'releaseTag' : string,
  'frontendHash' : [] | [Uint8Array],
  'frontendInstallDiagnostics' : [] | [FrontendInstallDiagnostics],
  'initArg' : Uint8Array,
  'envPairs' : [] | [Array<EnvPair>],
  'installedReleaseTag' : [] | [string],
  'canisterId' : [] | [Principal],
}
export interface StorageFundingStatus {
  'spendingPriority' : Array<TokenId>,
  'paidAutoTopUpEnabled' : boolean,
  'periodEnd' : [] | [Time],
  'includedCyclesRemaining' : bigint,
  'includedCyclesUsed' : bigint,
  'includedCyclesLimit' : bigint,
  'periodStart' : [] | [Time],
  'managedFundingEligible' : boolean,
  'paidTopUpAmountCycles' : bigint,
}
export interface StorageInfo {
  'id' : bigint,
  'status' : CreationStatus,
  'completedAt' : [] | [Time],
  'createdAt' : Time,
  'lastUpgradeError' : [] | [string],
  'releaseTag' : string,
  'frontendInstallDiagnostics' : [] | [FrontendInstallDiagnostics],
  'updateAvailable' : [] | [UpdateInfo],
  'canisterId' : [] | [Principal],
}
export interface StorageLicenseEntitlement {
  'includedBytes' : bigint,
  'maxFileBytes' : bigint,
}
export interface StorageReleaseManifest {
  'did' : [] | [ReleaseArtifactManifest],
  'frontendAssetTreeHash' : [] | [Uint8Array],
  'tagName' : string,
  'wasm' : [] | [ReleaseArtifactManifest],
  'frontend' : [] | [ReleaseArtifactManifest],
  'upgrade' : ReleaseUpgradeManifest,
  'releaseNotes' : [] | [ReleaseNotes],
  'version' : string,
  'stableSignature' : [] | [ReleaseArtifactManifest],
  'schemaVersion' : bigint,
  'commit' : string,
}
export interface StorageReleaseOption {
  'releaseNotesSummary' : [] | [string],
  'wasmUpdateAvailable' : boolean,
  'tagName' : string,
  'compatibleFrom' : Array<string>,
  'disabled' : boolean,
  'version' : string,
  'releaseNotesSections' : Array<ReleaseNoteSection>,
  'disabledReason' : [] | [string],
  'releaseUrl' : string,
  'frontendUpdateAvailable' : boolean,
  'updateInfo' : [] | [UpdateInfo],
}
export interface StorageReleaseOptionsResult {
  'stateInSync' : boolean,
  'options' : Array<StorageReleaseOption>,
}
export interface StorageReleaseState {
  'frontendAssetTreeHash' : [] | [Uint8Array],
  'manifestHash' : [] | [Uint8Array],
  'wasmHash' : [] | [Uint8Array],
  'installedAt' : [] | [Time],
  'releaseTag' : [] | [string],
  'schemaVersion' : bigint,
}
export type StorageVetKeyLevel = { 'highReplication' : null } |
  { 'standard' : null };
export interface StoredNotification {
  'id' : bigint,
  'source' : NotificationSource,
  'createdAt' : Time,
  'read' : boolean,
  'sourceEvent' : [] | [SourceEventRef],
  'severity' : NotificationSeverity,
  'correlationId' : [] | [string],
  'payload' : NotificationPayload,
}
export type StreamingCallback = ActorMethod<
  [StreamingToken],
  StreamingCallbackResponse
>;
export interface StreamingCallbackResponse {
  'token' : [] | [StreamingToken],
  'body' : Uint8Array,
}
export type StreamingStrategy = { 'Callback' : CallbackStreamingStrategy };
export type StreamingToken = Uint8Array;
export interface Subscription {
  'status' : Status,
  'expiresAt' : [] | [Time],
  'activatedAt' : Time,
  'userId' : Principal,
  'createdAt' : Time,
  'plan' : Plan,
  'updatedAt' : Time,
  'autoRenew' : boolean,
}
export type SubscriptionCheckResult = { 'active' : { 'plan' : Plan } } |
  { 'expired' : null } |
  { 'licensed' : LicenseStorageLimits } |
  { 'free' : null } |
  { 'unknownCanister' : null } |
  { 'invalidWasm' : null };
export interface SupportedAsset {
  'decimals' : number,
  'tokenId' : TokenId,
  'locator' : AssetLocator,
  'symbol' : string,
}
export type Time = bigint;
export interface TimeRangeFilter { 'max' : [] | [Time], 'min' : [] | [Time] }
export type TokenId = { 'ICP' : null } |
  { 'SOL' : null } |
  { 'SolUSDC' : null } |
  { 'SolUSDT' : null } |
  { 'ckETH' : null } |
  { 'ckUSDC' : null } |
  { 'ckUSDT' : null } |
  { 'BaseUSDC' : null } |
  { 'BaseUSDT' : null } |
  { 'BaseETH' : null };
export interface TransferRecord {
  'tokenId' : TokenId,
  'solSignature' : [] | [string],
  'subaccount' : [] | [Uint8Array],
  'recipient' : Principal,
  'solAddress' : [] | [string],
  'error' : [] | [string],
  'blockIndex' : [] | [bigint],
  'txHash' : [] | [string],
  'amount' : bigint,
  'evmAddress' : [] | [string],
}
export interface TransformArg {
  'context' : Uint8Array,
  'response' : HttpRequestResult,
}
export interface TreasuryInitArgsV1 { 'chains' : [] | [Array<ChainConfig>] }
export interface UpdateInfo {
  'currentWasmHash' : [] | [Uint8Array],
  'wasmUpdateAvailable' : boolean,
  'availableReleaseTag' : [] | [string],
  'currentReleaseTag' : [] | [string],
  'frontendUpdateAvailable' : boolean,
  'availableWasmHash' : [] | [Uint8Array],
}
export interface UpdateProfileArgs { 'displayName' : [] | [string] }
export type UpgradeStorageError = { 'StorageStateDrift' : string } |
  { 'AlreadyUpgrading' : null } |
  { 'NoUpdateAvailable' : null } |
  { 'NotFound' : null } |
  { 'NotOwner' : null } |
  { 'ReleaseNotReady' : null } |
  { 'ReleaseNotCompatible' : null } |
  { 'NotCompleted' : null };
export interface User {
  'id' : Principal,
  'referralAppliedAt' : [] | [Time],
  'roleText' : string,
  'lastLoginAt' : [] | [Time],
  'inviter' : [] | [Principal],
  'inviterText' : string,
  'createdAt' : Time,
  'role' : Role,
  'updatedAt' : Time,
  'identity' : UserIdentityAttributes,
  'profile' : [] | [UserProfile],
}
export interface UserDirectoryItem {
  'id' : Principal,
  'match' : UserDirectoryMatch,
  'profile' : [] | [PublicProfileSummary],
}
export type UserDirectoryMatch = { 'principalExact' : null } |
  { 'emailExact' : null } |
  { 'profile' : null };
export interface UserIdentityAttributes {
  'provider' : [] | [string],
  'verifiedEmail' : [] | [boolean],
  'name' : [] | [string],
  'email' : [] | [string],
  'syncedAt' : [] | [Time],
}
export interface UserProfile {
  'referralCode' : [] | [string],
  'username' : string,
  'displayName' : [] | [string],
  'createdAt' : Time,
  'updatedAt' : Time,
  'avatarRef' : [] | [AvatarRef],
}
export interface UserSettings {
  'spendingPriority' : Array<TokenId>,
  'topUpAmountCycles' : bigint,
  'autoRenew' : boolean,
  'autoTopUp' : boolean,
}
export interface WithdrawArgs {
  'to' : WithdrawDestination,
  'tokenId' : TokenId,
  'amount' : bigint,
}
export type WithdrawDestination = {
    'IC' : { 'owner' : Principal, 'subaccount' : [] | [Uint8Array] }
  } |
  { 'EVM' : { 'address' : string } } |
  { 'SOL' : { 'address' : string } };
export type WithdrawError = { 'BelowMinimum' : { 'minimum' : bigint } } |
  { 'InsufficientBalance' : { 'available' : bigint } } |
  { 'TransferFailed' : string } |
  { 'EvmNotConfigured' : null } |
  { 'SolNotConfigured' : null };
export interface WithdrawReceipt {
  'tx' : WithdrawTx,
  'tokenId' : TokenId,
  'amount' : bigint,
}
export type WithdrawResult = { 'ok' : WithdrawReceipt } |
  { 'err' : WithdrawError };
export type WithdrawTx = { 'IC' : { 'blockIndex' : bigint } } |
  { 'EVM' : { 'txHash' : string } } |
  { 'SOL' : { 'signature' : string } };
export interface _SERVICE extends Rabbithole {}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];