/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AddStorageError = { 'NotController' : null } |
  { 'CanisterAlreadyUsed' : { 'canisterId' : Principal } } |
  { 'InvalidWasm' : string };
export interface AmbassadorChain {
  'l1' : [] | [Principal],
  'l2' : [] | [Principal],
}
export type AmbassadorPayoutStatus = { 'pending' : null } |
  { 'skipped' : null } |
  { 'completed' : null } |
  { 'failed' : string };
export type AssetDownloadStatus = { 'Error' : string } |
  {
    'Downloading' : {
      'chunksCompleted' : bigint,
      'chunksError' : bigint,
      'chunksTotal' : bigint,
    }
  } |
  { 'Completed' : { 'size' : bigint } } |
  { 'NotStarted' : null };
export interface AssetFullStatus {
  'sha256' : [] | [Uint8Array],
  'contentType' : string,
  'name' : string,
  'size' : bigint,
  'downloadStatus' : AssetDownloadStatus,
  'extractionStatus' : [] | [ExtractionStatus],
}
export type AssetLocator = { 'Contract' : string } |
  { 'Mint' : string } |
  { 'Native' : null };
export interface BalanceEntry { 'tokenId' : TokenId, 'balance' : bigint }
export interface CallbackStreamingStrategy {
  'token' : StreamingToken,
  'callback' : [Principal, string],
}
export type ChainConfig = { 'Evm' : EvmChainConfig } |
  { 'Solana' : SolanaChainConfig };
export type CmcOpKind = { 'CreateCanister' : null } |
  { 'TopUp' : null };
export type CmcOpRetryResult = { 'scheduled' : { 'canisterId' : Principal } } |
  { 'resolved' : null } |
  { 'refunded' : null } |
  { 'blockedByRefund' : null } |
  { 'notFound' : null } |
  { 'stillAmbiguous' : { 'attempts' : bigint } };
export type CmcOpSource = { 'storageCreation' : { 'creationId' : bigint } } |
  { 'selfTopUp' : null } |
  { 'userTopUp' : { 'canisterId' : Principal } } |
  { 'autoTopUp' : { 'canisterId' : Principal } };
export interface CreateProfileArgs {
  'username' : string,
  'displayName' : [] | [string],
  'avatarUrl' : [] | [string],
}
export interface CreateProfileAvatarArgs {
  'content' : Uint8Array,
  'contentType' : string,
  'filename' : string,
}
export type CreationStatus = { 'Failed' : string } |
  { 'UpdatingControllers' : { 'canisterId' : Principal } } |
  { 'UpgradingWasm' : { 'progress' : Progress, 'canisterId' : Principal } } |
  { 'CanisterCreated' : { 'canisterId' : Principal } } |
  { 'RevokingInstallerPermission' : { 'canisterId' : Principal } } |
  { 'CheckingBalance' : null } |
  {
    'UploadingFrontend' : { 'progress' : Progress, 'canisterId' : Principal }
  } |
  { 'TransferringICP' : { 'amount' : bigint } } |
  { 'NotifyingCMC' : { 'blockIndex' : bigint } } |
  { 'ProcessingPayment' : PaymentPhase } |
  {
    'UpgradingFrontend' : { 'progress' : Progress, 'canisterId' : Principal }
  } |
  { 'Completed' : { 'canisterId' : Principal } } |
  { 'InstallingWasm' : { 'progress' : Progress, 'canisterId' : Principal } } |
  { 'Pending' : null };
export type DeleteStorageError = { 'NotFailed' : null } |
  { 'NotFound' : null } |
  { 'NotOwner' : null };
export interface DistributionLogOptions { 'offset' : bigint, 'limit' : bigint }
export interface DistributionRecord {
  'id' : bigint,
  'status' : DistributionStatus,
  'tokenId' : TokenId,
  'l1Amount' : bigint,
  'transfers' : Array<TransferRecord>,
  'l2Amount' : bigint,
  'ambassadorL1' : [] | [Principal],
  'ambassadorL2' : [] | [Principal],
  'totalAmount' : bigint,
  'paymentId' : string,
  'timestamp' : bigint,
  'payer' : Principal,
  'treasuryAmount' : bigint,
}
export type DistributionStatus = { 'completed' : null } |
  { 'partial' : null };
export interface EnvPair { 'value' : string, 'name' : string }
export interface EvmChainConfig {
  'evmRpcCanisterId' : string,
  'assets' : Array<SupportedAsset>,
  'rpcUrls' : Array<string>,
  'chainId' : bigint,
  'networkId' : string,
}
export type ExtractionStatus = { 'Idle' : null } |
  { 'Complete' : Array<FileMetadata> } |
  { 'Decoding' : { 'total' : bigint, 'processed' : bigint } };
export interface FileMetadata {
  'key' : string,
  'sha256' : Uint8Array,
  'contentType' : string,
  'size' : bigint,
}
export interface GetCreationsResponse {
  'total' : [] | [bigint],
  'data' : Array<StorageCreationRecord>,
  'instructions' : bigint,
}
export interface GetLicensesResponse {
  'total' : [] | [bigint],
  'data' : Array<License>,
  'instructions' : bigint,
}
export interface GetProfilesResponse {
  'total' : [] | [bigint],
  'data' : Array<Profile>,
  'instructions' : bigint,
}
export interface GetSubscriptionsResponse {
  'total' : [] | [bigint],
  'data' : Array<Subscription>,
  'instructions' : bigint,
}
export type Header = [string, string];
export interface InitArgs {
  'icpaySecretKey' : [] | [Uint8Array],
  'chains' : Array<ChainConfig>,
}
export interface KnownWasmHash {
  'hash' : Uint8Array,
  'releaseTag' : string,
  'registeredAt' : Time,
}
export interface License {
  'receipt' : PaymentReceipt,
  'owner' : Principal,
  'createdAt' : Time,
  'statusTag' : string,
  'canisterId' : [] | [Principal],
}
export interface ListCreationsOptions {
  'pagination' : { 'offset' : bigint, 'limit' : bigint },
  'count' : boolean,
  'sort' : Array<[string, SortDirection]>,
  'filter' : {
    'id' : [] | [Array<bigint>],
    'completedAt' : [] | [TimeRangeFilter],
    'owner' : [] | [Array<Principal>],
    'createdAt' : [] | [TimeRangeFilter],
    'ambassadorPayoutStatus' : [] | [Array<string>],
    'hasLicense' : [] | [boolean],
    'hasCanister' : [] | [boolean],
    'statusTag' : [] | [Array<string>],
    'releaseTag' : [] | [string],
    'canisterId' : [] | [Array<Principal>],
  },
}
export interface ListLicensesOptions {
  'pagination' : { 'offset' : bigint, 'limit' : bigint },
  'count' : boolean,
  'sort' : Array<[string, SortDirection]>,
  'filter' : {
    'id' : [] | [Array<bigint>],
    'owner' : [] | [Array<Principal>],
    'createdAt' : [] | [TimeRangeFilter],
    'hasCanister' : [] | [boolean],
    'statusTag' : [] | [Array<string>],
    'paymentId' : [] | [string],
    'paidAt' : [] | [TimeRangeFilter],
    'canisterId' : [] | [Array<Principal>],
  },
}
export interface ListOptions {
  'pagination' : { 'offset' : bigint, 'limit' : bigint },
  'count' : boolean,
  'sort' : Array<[string, SortDirection]>,
  'filter' : {
    'status' : [] | [Array<Status>],
    'expiresAt' : [] | [{ 'max' : [] | [bigint], 'min' : [] | [bigint] }],
    'userId' : [] | [Array<Principal>],
    'plan' : [] | [Array<Plan>],
  },
}
export interface ListOptions__1 {
  'pagination' : { 'offset' : bigint, 'limit' : bigint },
  'count' : boolean,
  'sort' : Array<[string, SortDirection]>,
  'filter' : {
    'id' : [] | [Array<Principal>],
    'username' : [] | [string],
    'displayName' : [] | [string],
    'createdAt' : [] | [{ 'max' : [] | [bigint], 'min' : [] | [bigint] }],
    'avatarUrl' : [] | [boolean],
  },
}
export interface NotificationsPage {
  'data' : Array<StoredNotification>,
  'unreadCount' : bigint,
}
export type PaymentPhase = { 'CheckingBalances' : null } |
  { 'Starting' : null } |
  { 'Queueing' : null } |
  { 'FetchingRates' : null } |
  { 'Charging' : { 'tokenId' : TokenId, 'amount' : bigint } } |
  { 'Activating' : null } |
  { 'RecordingLicense' : null };
export interface PaymentReceipt {
  'status' : PaymentStatus,
  'tokenId' : TokenId,
  'paymentId' : string,
  'amount' : bigint,
  'paidAt' : Time,
}
export type PaymentStatus = { 'completed' : null } |
  {
    'refunded' : {
      'at' : Time,
      'blockIndex' : [] | [bigint],
      'reason' : string,
    }
  };
export interface PendingCmcOp {
  'id' : bigint,
  'lastAttemptAt' : [] | [Time],
  'source' : CmcOpSource,
  'kind' : CmcOpKind,
  'createdAt' : Time,
  'attempts' : bigint,
  'blockIndex' : bigint,
  'lastError' : string,
  'refund' : [] | [RefundContext],
}
export interface PendingRefund {
  'tokenId' : TokenId,
  'userId' : Principal,
  'createdAt' : bigint,
  'amount' : bigint,
  'reason' : string,
}
export type Plan = { 'Pro' : null } |
  { 'Free' : null } |
  { 'Trial' : null };
export interface Profile {
  'id' : Principal,
  'referralCode' : [] | [string],
  'username' : string,
  'displayName' : [] | [string],
  'createdAt' : Time,
  'updatedAt' : Time,
  'avatarUrl' : [] | [string],
}
export interface Progress { 'total' : bigint, 'processed' : bigint }
export type PurchaseError = { 'ActivationFailed' : string } |
  { 'InvalidPlan' : string } |
  { 'ChargeFailed' : string } |
  { 'AlreadyActive' : null } |
  { 'InsufficientFunds' : { 'required' : bigint } };
export interface Rabbithole {
  'activateSubscription' : ActorMethod<
    [Principal, Plan, [] | [bigint]],
    undefined
  >,
  'activateTrial' : ActorMethod<[], undefined>,
  /**
   * / Register an externally-deployed storage canister with this backend.
   * /
   * / Required: caller must be a controller of `canisterId`, and the
   * / canister's `module_hash` must match one of the known Rabbithole
   * / storage WASM releases.
   * /
   * / Ownership semantics — important:
   * /   - `record.owner = caller` (the controller who registered it).
   * /     This is the *billing owner* in our backend — who pays for
   * /     managed services (auto-topup, notifications, listStorages).
   * /   - The storage canister's internal `initArgs.owner` (who holds
   * /     VetKey root permissions, data access) can be a DIFFERENT
   * /     principal — controller ≠ data owner on IC.
   * /   - That divergence is intentional. A controller registers the
   * /     canister for managed services; data access stays gated by
   * /     the storage canister's permission rules (see
   * /     `grantStoragePermission` / `revokeStoragePermission`).
   * /
   * / Backend id trust — not verified:
   * /   - Caller could have set `PUBLIC_CANISTER_ID:rabbithole-backend`
   * /     env var to a different backend, in which case the canister's
   * /     subscription gates and auto-topup calls would route elsewhere.
   * /     That's self-sabotage (controller loses Pro features), not a
   * /     risk for us — so we don't verify.
   * /
   * / Trial — NOT auto-activated. Trial is part of the License offer
   * / (strategy §3), not a freebie for any account registration.
   * / Controller who wants Trial calls `activateTrial()` separately
   * / (per-account, not per-storage; only once per account).
   */
  'addStorage' : ActorMethod<[Principal, Uint8Array], Result_6>,
  'adminRegisterWasmHash' : ActorMethod<[Uint8Array, string], undefined>,
  'checkStorageUpdate' : ActorMethod<[Principal], [] | [UpdateInfo]>,
  'checkSubscription' : ActorMethod<[Uint8Array], SubscriptionCheckResult>,
  'createProfile' : ActorMethod<[CreateProfileArgs], Uint8Array>,
  'deleteProfile' : ActorMethod<[], undefined>,
  'deleteStorage' : ActorMethod<[bigint], Result_5>,
  'dismissPendingCmcOp' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'notFound' : null }
  >,
  'flushPaymentQueue' : ActorMethod<[], undefined>,
  'getAmbassadorChainQuery' : ActorMethod<[], AmbassadorChain>,
  'getBackendCyclesBalance' : ActorMethod<[], bigint>,
  'getCmcRecoveryStats' : ActorMethod<[], StatsView>,
  'getDistributionLog' : ActorMethod<
    [DistributionLogOptions],
    Array<DistributionRecord>
  >,
  'getEvmAddress' : ActorMethod<[], [] | [string]>,
  'getMyWalletAddresses' : ActorMethod<
    [],
    {
      'icSubaccount' : Uint8Array,
      'solAddress' : [] | [string],
      'evmAddress' : [] | [string],
    }
  >,
  'getNotifications' : ActorMethod<[[] | [Time], bigint], NotificationsPage>,
  'getPendingRefunds' : ActorMethod<[], Array<PendingRefund>>,
  'getProfile' : ActorMethod<[], [] | [Profile]>,
  'getReleasesFullStatus' : ActorMethod<[], ReleasesFullStatus>,
  'getSettings' : ActorMethod<[], UserSettings>,
  'getSolAddress' : ActorMethod<[], [] | [string]>,
  'getSubscription' : ActorMethod<[], [] | [Subscription]>,
  'getTreasuryBalances' : ActorMethod<[], Array<BalanceEntry>>,
  'getUnreadCount' : ActorMethod<[], bigint>,
  'getUser' : ActorMethod<[], [] | [User]>,
  'http_request' : ActorMethod<[RawQueryHttpRequest], RawQueryHttpResponse>,
  'http_request_streaming_callback' : ActorMethod<
    [StreamingToken],
    StreamingCallbackResponse
  >,
  'http_request_update' : ActorMethod<
    [RawUpdateHttpRequest],
    RawUpdateHttpResponse
  >,
  'isAdmin' : ActorMethod<[Principal], boolean>,
  'isKnownWasmHash' : ActorMethod<[Uint8Array], boolean>,
  'isStorageDeployerRunning' : ActorMethod<[], boolean>,
  /**
   * / List creations with optional filter + pagination. Callers omit `options`
   * / (`[]`) to get the caller's own creations with defaults. Non-admins are
   * / pinned to their own `owner` regardless of filter.owner passed in.
   * / Records include the full `events` timeline — no separate history query.
   */
  'listCreations' : ActorMethod<
    [[] | [ListCreationsOptions]],
    GetCreationsResponse
  >,
  'listKnownWasmHashes' : ActorMethod<[], Array<KnownWasmHash>>,
  /**
   * / List licenses with optional filter + pagination. Callers omit `options`
   * / (`[]`) to get the caller's own licenses with defaults. Non-admins are
   * / pinned to their own `owner` regardless of filter.owner passed in.
   */
  'listLicenses' : ActorMethod<
    [[] | [ListLicensesOptions]],
    GetLicensesResponse
  >,
  'listPendingCmcOps' : ActorMethod<
    [{ 'limit' : [] | [bigint], 'afterId' : [] | [bigint] }],
    Array<PendingCmcOp>
  >,
  'listProfiles' : ActorMethod<[ListOptions__1], GetProfilesResponse>,
  'listStorages' : ActorMethod<[], Array<StorageInfo>>,
  'listSubscriptions' : ActorMethod<[ListOptions], GetSubscriptionsResponse>,
  'listUsersByRole' : ActorMethod<[Role], Array<Principal>>,
  'markAllNotificationsAsRead' : ActorMethod<[], undefined>,
  'markNotificationsAsRead' : ActorMethod<[Array<bigint>], undefined>,
  'onStorageLowCycles' : ActorMethod<
    [bigint, bigint, { 'warning' : null } | { 'critical' : null }],
    undefined
  >,
  'processPendingRefunds' : ActorMethod<[], bigint>,
  /**
   * / Purchase a license and kick off storage creation. Returns the creation
   * / id immediately — charge + deploy run asynchronously on the orchestrator
   * / side. Frontend polls `listCreations({filter.id=[id]})` to follow progress.
   * /
   * / The initial record is created with `#ProcessingPayment(#Starting)`. A
   * / detached Timer picks up the flow on the next tick and transitions the
   * / record through all payment phases (`FetchingRates`, `Charging`,
   * / `RecordingLicense`, `Activating`, `Queueing`) before handing off to the
   * / unified deploy queue.
   */
  'purchaseLicenseAndCreateStorage' : ActorMethod<
    [StorageBackendType, [] | [Array<{ 'value' : string, 'name' : string }>]],
    Result_4
  >,
  'purchaseSubscription' : ActorMethod<[Plan], Result_3>,
  'queryExpiredSubscriptions' : ActorMethod<
    [],
    Array<[Principal, Subscription]>
  >,
  'queryExpiringSubscriptions' : ActorMethod<
    [bigint],
    Array<[Principal, Subscription]>
  >,
  /**
   * / Recover a failed storage creation. Owner OR admin may call.
   * /
   * / Strategies:
   * /   - `#resume`: re-queue the deploy. Checkpoint-aware —
   * /     * `record.canisterId == null`  → `#CreateCanister` (treasury ICP intact)
   * /     * `record.canisterId == ?id`   → `#LinkCanister(id)` (point-of-no-return crossed)
   * /     Preserves original `initArg` + `envPairs`. Refuses if the license was refunded.
   * /   - `#refund`: ICP goes back to the owner, license flips `#refunded`,
   * /     creation record is deleted. Only allowed BEFORE `#CanisterCreated` —
   * /     once the canister exists, cycles can't be recovered.
   * /
   * / Both strategies share the same per-creationId lock (`creationLocks`), so
   * / concurrent recover calls on the same id serialize: the loser sees
   * / "another refund or resume is in progress".
   */
  'recoverFailedStorage' : ActorMethod<[bigint, RecoveryStrategy], Result_2>,
  'refreshReleases' : ActorMethod<[], undefined>,
  'register' : ActorMethod<[[] | [string]], undefined>,
  /**
   * / Register the latest downloaded WASM hash as known.
   */
  'registerLatestWasmHash' : ActorMethod<[], undefined>,
  'renewSubscription' : ActorMethod<
    [Principal, Plan, [] | [bigint]],
    undefined
  >,
  'reportTrialBytes' : ActorMethod<[bigint], undefined>,
  /**
   * / Admin-only retry for a creation whose deferred ambassador payout
   * / landed in `#failed`. Re-invokes the payout; on success the record's
   * / `ambassadorPayoutStatus` flips to `#completed` (or back to `#failed`
   * / with the new reason). Idempotent via the treasury dedup set — if
   * / the payout had actually succeeded and only the status-stamp failed,
   * / treasury returns `#AlreadyProcessed` which we translate to `#completed`.
   */
  'retryAmbassadorPayout' : ActorMethod<[bigint], Result_2>,
  'retryPendingCmcOp' : ActorMethod<[bigint], CmcOpRetryResult>,
  'saveAvatar' : ActorMethod<[CreateProfileAvatarArgs], string>,
  'setUserRole' : ActorMethod<[Principal, Role], undefined>,
  'startStorageDeployer' : ActorMethod<[], undefined>,
  'stopStorageDeployer' : ActorMethod<[], undefined>,
  'topUpFromBalance' : ActorMethod<[Principal, bigint], Result_1>,
  'triggerAutoRenewals' : ActorMethod<[], undefined>,
  'triggerExpireOverdue' : ActorMethod<[], Array<Principal>>,
  'triggerSelfTopUp' : ActorMethod<[], undefined>,
  'updateProfile' : ActorMethod<[UpdateProfileArgs], undefined>,
  'updateSettings' : ActorMethod<[UserSettings], undefined>,
  'upgradeStorage' : ActorMethod<[Principal], Result>,
  'usernameExists' : ActorMethod<[string], boolean>,
  'withdraw' : ActorMethod<[WithdrawArgs], WithdrawResult>,
  'withdrawFromTreasury' : ActorMethod<[WithdrawArgs], WithdrawResult>,
}
export interface RawQueryHttpRequest {
  'url' : string,
  'method' : string,
  'body' : Uint8Array,
  'headers' : Array<Header>,
  'certificate_version' : [] | [number],
}
export interface RawQueryHttpResponse {
  'body' : Uint8Array,
  'headers' : Array<Header>,
  'upgrade' : [] | [boolean],
  'streaming_strategy' : [] | [StreamingStrategy],
  'status_code' : number,
}
export interface RawUpdateHttpRequest {
  'url' : string,
  'method' : string,
  'body' : Uint8Array,
  'headers' : Array<Header>,
}
export interface RawUpdateHttpResponse {
  'body' : Uint8Array,
  'headers' : Array<Header>,
  'streaming_strategy' : [] | [StreamingStrategy],
  'status_code' : number,
}
export type RecoveryStrategy = { 'resume' : null } |
  { 'refund' : null };
export interface RefundContext {
  'tokenId' : TokenId,
  'payer' : Principal,
  'amount' : bigint,
}
export interface ReleaseFullStatus {
  'tagName' : string,
  'isDownloaded' : boolean,
  'name' : string,
  'createdAt' : Time,
  'assets' : Array<AssetFullStatus>,
  'publishedAt' : [] | [Time],
  'isDeploymentReady' : boolean,
  'draft' : boolean,
  'prerelease' : boolean,
}
export interface ReleasesFullStatus {
  'defaultVersionKey' : string,
  'releasesCount' : bigint,
  'pendingDownloads' : bigint,
  'hasDeploymentReadyRelease' : boolean,
  'hasDownloadedRelease' : boolean,
  'releases' : Array<ReleaseFullStatus>,
  'completedDownloads' : bigint,
}
export type Result = { 'ok' : null } |
  { 'err' : UpgradeStorageError };
export type Result_1 = { 'ok' : { 'cyclesAdded' : bigint } } |
  { 'err' : string };
export type Result_2 = { 'ok' : null } |
  { 'err' : string };
export type Result_3 = { 'ok' : null } |
  { 'err' : PurchaseError };
export type Result_4 = { 'ok' : bigint } |
  { 'err' : PurchaseError };
export type Result_5 = { 'ok' : null } |
  { 'err' : DeleteStorageError };
export type Result_6 = { 'ok' : bigint } |
  { 'err' : AddStorageError };
export type Role = { 'admin' : null } |
  { 'moderator' : null } |
  { 'user' : null };
export interface SolanaChainConfig {
  'solRpcCanisterId' : string,
  'assets' : Array<SupportedAsset>,
  'rpcUrl' : [] | [string],
  'networkId' : string,
}
export type SortDirection = { 'Descending' : null } |
  { 'Ascending' : null };
export interface StatsView {
  'totalResolved' : bigint,
  'totalRefunded' : bigint,
  'totalDismissed' : bigint,
  'totalCreated' : bigint,
}
export type Status = { 'Active' : null } |
  { 'Cancelled' : null } |
  { 'Expired' : null };
export interface StatusEvent { 'status' : CreationStatus, 'timestamp' : Time }
export type StorageBackendType = { 'OnChain' : null } |
  { 'BlobStorage' : null };
export interface StorageCreationRecord {
  'id' : bigint,
  'status' : CreationStatus,
  'completedAt' : [] | [Time],
  'licensePaymentId' : [] | [string],
  'owner' : Principal,
  'wasmHash' : [] | [Uint8Array],
  'createdAt' : Time,
  'ambassadorPayoutStatus' : AmbassadorPayoutStatus,
  'lastUpgradeError' : [] | [string],
  'isUpgrade' : boolean,
  'statusTag' : string,
  'subnetId' : [] | [Principal],
  'upgradeIncludesFrontend' : boolean,
  'ambassadorPayoutStatusTag' : string,
  'events' : Array<StatusEvent>,
  'releaseTag' : string,
  'frontendHash' : [] | [Uint8Array],
  'initArg' : Uint8Array,
  'envPairs' : [] | [Array<EnvPair>],
  'installedReleaseTag' : [] | [string],
  'canisterId' : [] | [Principal],
}
export interface StorageInfo {
  'id' : bigint,
  'status' : CreationStatus,
  'completedAt' : [] | [Time],
  'createdAt' : Time,
  'lastUpgradeError' : [] | [string],
  'releaseTag' : string,
  'updateAvailable' : [] | [UpdateInfo],
  'canisterId' : [] | [Principal],
}
export interface StoredNotification {
  'id' : bigint,
  'createdAt' : Time,
  'read' : boolean,
  'event' : TypedEvent,
}
export type StreamingCallback = ActorMethod<
  [StreamingToken],
  StreamingCallbackResponse
>;
export interface StreamingCallbackResponse {
  'token' : [] | [StreamingToken],
  'body' : Uint8Array,
}
export type StreamingStrategy = { 'Callback' : CallbackStreamingStrategy };
export type StreamingToken = Uint8Array;
export interface Subscription {
  'status' : Status,
  'expiresAt' : [] | [Time],
  'activatedAt' : Time,
  'userId' : Principal,
  'createdAt' : Time,
  'plan' : Plan,
  'updatedAt' : Time,
  'trialUsedBytes' : bigint,
  'autoRenew' : boolean,
}
export type SubscriptionCheckResult = {
    'trial' : { 'remainingBytes' : bigint }
  } |
  { 'active' : { 'plan' : Plan } } |
  { 'expired' : null } |
  { 'free' : null } |
  { 'unknownCanister' : null } |
  { 'invalidWasm' : null };
export interface SupportedAsset {
  'decimals' : number,
  'tokenId' : TokenId,
  'locator' : AssetLocator,
  'symbol' : string,
}
export type Time = bigint;
export interface TimeRangeFilter { 'max' : [] | [Time], 'min' : [] | [Time] }
export type TokenId = { 'ICP' : null } |
  { 'SOL' : null } |
  { 'SolUSDC' : null } |
  { 'SolUSDT' : null } |
  { 'ckETH' : null } |
  { 'ckUSDC' : null } |
  { 'ckUSDT' : null } |
  { 'BaseUSDC' : null } |
  { 'BaseUSDT' : null } |
  { 'BaseETH' : null };
export interface TransferRecord {
  'tokenId' : TokenId,
  'solSignature' : [] | [string],
  'subaccount' : [] | [Uint8Array],
  'recipient' : Principal,
  'solAddress' : [] | [string],
  'error' : [] | [string],
  'blockIndex' : [] | [bigint],
  'txHash' : [] | [string],
  'amount' : bigint,
  'evmAddress' : [] | [string],
}
export type TypedEvent = {
    'backendLowCycles' : { 'threshold' : bigint, 'current' : bigint }
  } |
  { 'topUpCompleted' : { 'canisterId' : Principal, 'cyclesAmount' : bigint } } |
  { 'depositReceived' : { 'tokenId' : string, 'amount' : bigint } } |
  { 'trialStarted' : { 'limitBytes' : bigint } } |
  {
    'cmcNotifyStuck' : {
      'id' : bigint,
      'blockIndex' : bigint,
      'caller' : Principal,
      'canisterId' : Principal,
      'reason' : string,
    }
  } |
  {
    'ambassadorPayoutFailed' : {
      'owner' : Principal,
      'creationId' : bigint,
      'reason' : string,
    }
  } |
  { 'subscriptionExpired' : null } |
  { 'autoRenewFailed' : { 'reason' : string } } |
  { 'topUpFailed' : { 'canisterId' : Principal, 'reason' : string } } |
  {
    'autoTopUpCompleted' : { 'canisterId' : Principal, 'cyclesAmount' : bigint }
  } |
  {
    'creationRefunded' : {
      'tokenId' : string,
      'owner' : Principal,
      'creationId' : bigint,
      'amount' : bigint,
    }
  } |
  {
    'treasuryIcpLow' : {
      'currentBalance' : bigint,
      'reserve' : bigint,
      'required' : bigint,
    }
  } |
  {
    'subscriptionRenewed' : {
      'expiresAt' : [] | [bigint],
      'plan' : { 'Pro' : null } |
        { 'Free' : null } |
        { 'Trial' : null },
    }
  } |
  { 'balanceLow' : { 'requiredAmount' : bigint } } |
  {
    'paymentReceived' : {
      'tokenId' : string,
      'amount' : bigint,
      'purpose' : string,
    }
  } |
  {
    'subscriptionActivated' : {
      'plan' : { 'Pro' : null } |
        { 'Free' : null } |
        { 'Trial' : null },
    }
  } |
  { 'updateAvailable' : { 'releaseTag' : string, 'canisterId' : Principal } } |
  { 'autoTopUpFailed' : { 'canisterId' : Principal, 'reason' : string } } |
  {
    'lowCycles' : {
      'estimatedDaysLeft' : bigint,
      'severity' : { 'warning' : null } |
        { 'critical' : null },
      'remaining' : bigint,
      'canisterId' : Principal,
    }
  } |
  { 'backendSelfTopUpFailed' : { 'reason' : string } };
export interface UpdateInfo {
  'currentWasmHash' : [] | [Uint8Array],
  'wasmUpdateAvailable' : boolean,
  'availableReleaseTag' : [] | [string],
  'currentReleaseTag' : [] | [string],
  'frontendUpdateAvailable' : boolean,
  'availableWasmHash' : [] | [Uint8Array],
}
export interface UpdateProfileArgs {
  'displayName' : [] | [string],
  'avatarUrl' : [] | [string],
}
export type UpgradeStorageError = { 'AlreadyUpgrading' : null } |
  { 'NoUpdateAvailable' : null } |
  { 'NotFound' : null } |
  { 'NotOwner' : null } |
  { 'ReleaseNotReady' : null } |
  { 'NotCompleted' : null };
export interface User {
  'id' : Principal,
  'inviter' : [] | [Principal],
  'createdAt' : Time,
  'role' : Role,
  'trialUsed' : boolean,
  'updatedAt' : Time,
}
export interface UserSettings {
  'spendingPriority' : Array<TokenId>,
  'topUpAmountCycles' : bigint,
  'autoRenew' : boolean,
  'autoTopUp' : boolean,
}
export interface WithdrawArgs {
  'to' : WithdrawDestination,
  'tokenId' : TokenId,
  'amount' : bigint,
}
export type WithdrawDestination = {
    'IC' : { 'owner' : Principal, 'subaccount' : [] | [Uint8Array] }
  } |
  { 'EVM' : { 'address' : string } } |
  { 'SOL' : { 'address' : string } };
export type WithdrawError = { 'BelowMinimum' : { 'minimum' : bigint } } |
  { 'InsufficientBalance' : { 'available' : bigint } } |
  { 'TransferFailed' : string } |
  { 'EvmNotConfigured' : null } |
  { 'SolNotConfigured' : null };
export type WithdrawResult = { 'ok' : bigint } |
  { 'err' : WithdrawError };
export interface _SERVICE extends Rabbithole {}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];