[dependencies]
caffeineai-object-storage = "0.1.1"
memory-region = "1.5.0"
base = "0.16.0"
ic = "3.2.0"
ic-vetkeys = "0.4.0"
encrypted-storage = "../../libs/motoko/encrypted-storage"
treasury = "../../libs/motoko/treasury"
icpay-webhooks = "../../libs/motoko/icpay-webhooks"
liminal = "3.1.0"
http-assets = "0.2.0"
zendb = "2.0.0"
json = "1.4.0"
compression = "0.3.0"
sha2 = "0.1.14"
hex = "1.0.2"
core = "2.5.0"
datetime = "1.1.0"
tar = "https://github.com/christoph-dfinity/motoko-tar#9dcd0bd79fe26a81cdfa75b5c8104c68a4cd67d9"
vector = "0.4.6"
byte-utils = "0.2.0"

[toolchain]
moc = "1.6.0"
wasmtime = "44.0.0"
