/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AbortUploadSessionArguments { 'batchId' : BatchId }
export type AccessClass = { 'ordinary' : null } |
  { 'ownerEquivalent' : null } |
  { 'durable' : null };
export interface AccessGrantList {
  'pendingGrants' : Array<ListedPendingAccessGrant>,
  'principalGrants' : Array<ListedPrincipalAccessGrant>,
  'mode' : AccessGrantListMode,
  'scope' : AccessScope,
}
export type AccessGrantListMode = { 'effective' : null } |
  { 'exact' : null };
export type AccessRef = { 'principal' : Principal } |
  { 'emailCommitment' : EmailCommitment } |
  { 'email' : { 'emailCommitment' : EmailCommitment, 'email' : string } };
export interface AccessRequest {
  'id' : bigint,
  'status' : AccessRequestStatus,
  'requester' : Principal,
  'createdAt' : Time,
  'emailCommitment' : [] | [EmailCommitment],
  'message' : [] | [string],
  'decidedAt' : [] | [Time],
  'decidedBy' : [] | [Principal],
}
export type AccessRequestDecision = {
    'approved' : { 'permission' : Permission, 'scope' : AccessScope }
  } |
  { 'rejected' : null };
export type AccessRequestStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type AccessScope = { 'root' : null } |
  { 'entry' : Entry } |
  { 'keyId' : KeyId__2 };
export type AccessSource = { 'durablePolicy' : bigint } |
  { 'accessRequest' : bigint } |
  { 'directGrant' : null } |
  { 'ordinaryInvite' : bigint } |
  { 'recoverySetup' : null };
export interface AddRecoveryOwnerOptions { 'controllerRecovery' : boolean }
export interface AppendUploadChunkArguments {
  'content' : Uint8Array,
  'chunkIndex' : [] | [bigint],
  'batchId' : BatchId,
}
export interface AppendUploadChunkResponse { 'chunkId' : bigint }
export type BatchId = bigint;
export interface BeginUploadSessionArguments {
  'declaredUploadBytes' : [] | [bigint],
  'createMode' : CreateMode,
  'totalSize' : bigint,
  'expectedChunkCount' : [] | [bigint],
  'entry' : Entry,
}
export interface BeginUploadSessionResponse {
  'node' : NodeDetails,
  'batchId' : BatchId,
}
export interface BlobLocator {
  'layoutVersion' : bigint,
  'blobKey' : string,
  'treeKey' : string,
}
export type BlobReplicaStatus = { 'Missing' : null } |
  { 'Active' : null } |
  { 'DeletePending' : null } |
  { 'Deleted' : null };
export interface CancelAccessRequestArguments { 'requestId' : bigint }
export interface CancelDurableAccessPolicyArguments { 'policyId' : bigint }
export interface CancelPendingAccessGrantArguments { 'grantId' : bigint }
export interface ChunkContent { 'content' : Uint8Array }
export type ChunkId = bigint;
export interface ClaimPendingAccessByBackendAttestationArguments {
  'principal' : Principal,
  'emailCommitments' : Array<EmailCommitment>,
}
export interface ClaimPendingAccessGrantArguments { 'grantId' : bigint }
export interface CommitExternalBlobUploadArgs {
  'rootHashHex' : string,
  'sha256' : Uint8Array,
  'contentType' : string,
  'size' : bigint,
  'entry' : Entry,
  'targetId' : [] | [ExternalStorageTargetId],
}
export interface CommitExternalThumbnailUploadArgs {
  'rootHashHex' : string,
  'sha256' : Uint8Array,
  'contentType' : string,
  'size' : bigint,
  'encryption' : ThumbnailEncryptionRef,
  'entry' : Entry,
  'targetId' : [] | [ExternalStorageTargetId],
}
export interface CommitThumbnailUploadArguments {
  'sha256' : Uint8Array,
  'contentType' : string,
  'size' : bigint,
  'encryption' : ThumbnailEncryptionRef,
  'entry' : Entry,
  'rootHash' : string,
}
export interface ConfigureExternalStorageTargetArgs {
  'region' : string,
  'displayName' : [] | [string],
  'endpoint' : string,
  'accessKeyId' : string,
  'secretAccessKey' : string,
  'sessionToken' : [] | [string],
  'prefix' : string,
  'bucket' : string,
  'targetId' : [] | [TargetId],
  'forcePathStyle' : boolean,
}
export interface CreateAccessBatchArguments {
  'items' : Array<CreateAccessBatchItem>,
}
export interface CreateAccessBatchItem {
  'ref' : AccessRef,
  'permission' : Permission,
  'expiresAt' : [] | [Time],
  'source' : AccessSource,
  'scope' : AccessScope,
  'accessClass' : AccessClass,
}
export interface CreateAccessBatchResult {
  'pendingGrants' : Array<PendingAccessGrant>,
  'revokedPrincipalGrants' : Array<PrincipalAccessGrant>,
  'principalGrants' : Array<PrincipalAccessGrant>,
  'cancelledPendingGrants' : Array<PendingAccessGrant>,
}
export interface CreateAccessRequestArguments {
  'emailCommitment' : [] | [EmailCommitment],
  'message' : [] | [string],
}
export interface CreateArguments { 'createMode' : CreateMode, 'entry' : Entry }
export interface CreateDurableAccessGrantArguments {
  'permission' : Permission,
  'principal' : Principal,
  'source' : AccessSource,
  'scope' : AccessScope,
}
export interface CreateDurableAccessPolicyArguments {
  'grants' : Array<DurablePolicyGrantTemplate>,
  'trigger' : DurablePolicyTrigger,
  'recipients' : Array<AccessRef>,
}
export type CreateMode = { 'GetOrCreate' : null } |
  { 'CreateNew' : null };
export interface CreatePendingAccessGrantArguments {
  'ref' : AccessRef,
  'permission' : Permission,
  'expiresAt' : [] | [Time],
  'source' : AccessSource,
  'scope' : AccessScope,
  'accessClass' : AccessClass,
}
export interface DeleteArguments { 'recursive' : boolean, 'entry' : Entry }
export type DeleteTaskStatus = { 'Done' : null } |
  { 'Running' : null } |
  { 'Cancelled' : null } |
  { 'Pending' : null };
export type DirectoryColor = { 'blue' : null } |
  { 'gray' : null } |
  { 'orange' : null } |
  { 'pink' : null } |
  { 'purple' : null } |
  { 'green' : null } |
  { 'yellow' : null };
export interface DirectoryMetadata {
  'color' : [] | [DirectoryColor],
  'defaultThumbnailStorageBackend' : StorageBackend,
  'thumbnailStoragePolicy' : ThumbnailStoragePolicy,
}
export interface DisableExternalStorageTargetArgs { 'targetId' : TargetId }
export interface DurableAccessPolicy {
  'id' : bigint,
  'maturedAt' : [] | [Time],
  'status' : DurablePolicyStatus,
  'grants' : Array<DurablePolicyGrantTemplate>,
  'trigger' : DurablePolicyTrigger,
  'createdAt' : Time,
  'createdBy' : Principal,
  'cancelledAt' : [] | [Time],
  'proVerifiedAt' : Time,
  'recipients' : Array<AccessRef>,
  'releasedAt' : [] | [Time],
  'graceStartedAt' : [] | [Time],
  'principalGrantIds' : Array<bigint>,
  'pendingGrantIds' : Array<bigint>,
}
export interface DurablePolicyGrantTemplate {
  'permission' : Permission,
  'scope' : AccessScope,
}
export interface DurablePolicyProcessResult {
  'pendingGrants' : Array<PendingAccessGrant>,
  'principalGrants' : Array<PrincipalAccessGrant>,
  'policy' : DurableAccessPolicy,
}
export type DurablePolicyStatus = { 'cancelled' : null } |
  { 'armed' : null } |
  { 'released' : null } |
  { 'matured' : null } |
  { 'grace' : null };
export type DurablePolicyTrigger = { 'manualRelease' : null } |
  { 'date' : { 'releaseAt' : Time } } |
  {
    'inactivity' : { 'inactiveForNs' : bigint, 'gracePeriodNs' : [] | [bigint] }
  };
export interface EmailClaim {
  'principalGrantId' : bigint,
  'principal' : Principal,
  'origin' : EmailClaimOrigin,
  'claimedAt' : Time,
}
export type EmailClaimOrigin = { 'storage' : null } |
  { 'rabbithole' : null };
export interface EmailClaimState {
  'storage' : [] | [EmailClaim],
  'rabbithole' : [] | [EmailClaim],
}
export type EmailCommitment = Uint8Array;
export interface EncryptedStorageCanister {
  'abortUploadSession' : ActorMethod<[AbortUploadSessionArguments], undefined>,
  'activateRecoveryOwnership' : ActorMethod<
    [Principal],
    OwnerEquivalentPrincipal
  >,
  'addRecoveryOwner' : ActorMethod<
    [Principal, AddRecoveryOwnerOptions],
    OwnerEquivalentPrincipal
  >,
  'appendUploadChunk' : ActorMethod<
    [AppendUploadChunkArguments],
    AppendUploadChunkResponse
  >,
  'beginUploadSession' : ActorMethod<
    [BeginUploadSessionArguments],
    BeginUploadSessionResponse
  >,
  'cancelAccessRequest' : ActorMethod<
    [CancelAccessRequestArguments],
    AccessRequest
  >,
  'cancelDurableAccessPolicy' : ActorMethod<
    [CancelDurableAccessPolicyArguments],
    DurableAccessPolicy
  >,
  'cancelPendingAccessGrant' : ActorMethod<
    [CancelPendingAccessGrantArguments],
    PendingAccessGrant
  >,
  'claimPendingAccessByBackendAttestation' : ActorMethod<
    [ClaimPendingAccessByBackendAttestationArguments],
    Array<PrincipalAccessGrant>
  >,
  'claimPendingAccessGrant' : ActorMethod<
    [ClaimPendingAccessGrantArguments],
    PrincipalAccessGrant
  >,
  'clear' : ActorMethod<[], undefined>,
  'clearRecoveryController' : ActorMethod<[], Principal>,
  'commitExternalBlobUpload' : ActorMethod<
    [CommitExternalBlobUploadArgs],
    undefined
  >,
  'commitExternalThumbnailUpload' : ActorMethod<
    [CommitExternalThumbnailUploadArgs],
    NodeDetails
  >,
  'commitThumbnailUpload' : ActorMethod<
    [CommitThumbnailUploadArguments],
    NodeDetails
  >,
  'configureExternalStorageTarget' : ActorMethod<
    [ConfigureExternalStorageTargetArgs],
    ExternalStorageTargetView
  >,
  'create' : ActorMethod<[CreateArguments], NodeDetails>,
  'createAccessBatch' : ActorMethod<
    [CreateAccessBatchArguments],
    CreateAccessBatchResult
  >,
  'createDurableAccessGrant' : ActorMethod<
    [CreateDurableAccessGrantArguments],
    PrincipalAccessGrant
  >,
  'createDurableAccessPolicy' : ActorMethod<
    [CreateDurableAccessPolicyArguments],
    DurableAccessPolicy
  >,
  'createPendingAccessGrant' : ActorMethod<
    [CreatePendingAccessGrantArguments],
    PendingAccessGrant
  >,
  'delete' : ActorMethod<[DeleteArguments], undefined>,
  'disableExternalStorageTarget' : ActorMethod<
    [DisableExternalStorageTargetArgs],
    ExternalStorageTargetView
  >,
  'disconnectExternalStorageTarget' : ActorMethod<
    [DisableExternalStorageTargetArgs],
    undefined
  >,
  'externalBlobLocatorForTarget' : ActorMethod<
    [ExternalTargetBlobLocatorArgs],
    ExternalTargetBlobLocator
  >,
  'externalStorageHttpTransform' : ActorMethod<
    [ExternalStorageHttpTransformArg],
    {
      'status' : bigint,
      'body' : Uint8Array,
      'headers' : Array<{ 'value' : string, 'name' : string }>,
    }
  >,
  'finishUploadSession' : ActorMethod<
    [FinishUploadSessionArguments],
    undefined
  >,
  'fsTree' : ActorMethod<[], Array<TreeNode>>,
  'getActiveExternalStorageTarget' : ActorMethod<
    [],
    [] | [ExternalStorageTargetView]
  >,
  'getChunk' : ActorMethod<[GetChunkArguments], ChunkContent>,
  'getEncryptedVetkey' : ActorMethod<[KeyId, TransportKey], VetKey>,
  'getExternalStorageCleanupStatus' : ActorMethod<
    [],
    ExternalStorageCleanupStatus
  >,
  'getMyAccessRequest' : ActorMethod<[], [] | [AccessRequest]>,
  'getOwnerActivityState' : ActorMethod<[], OwnerActivityState>,
  'getRecoveryStatus' : ActorMethod<[], RecoveryStatus>,
  'getStorageEventsUnreadCount' : ActorMethod<[], bigint>,
  'getVetkeyVerificationKey' : ActorMethod<[], VetKeyVerificationKey>,
  'hasPermission' : ActorMethod<[HasPermissionArguments], boolean>,
  'list' : ActorMethod<[[] | [Entry]], ListResponse>,
  'listAccessGrants' : ActorMethod<
    [ListAccessGrantsArguments],
    AccessGrantList
  >,
  'listAccessRequests' : ActorMethod<[], Array<AccessRequest>>,
  'listDurableAccessPolicies' : ActorMethod<[], Array<DurableAccessPolicy>>,
  'listExternalBlobReplicas' : ActorMethod<[], Array<ExternalBlobReplica>>,
  'listExternalStorageDeleteTasks' : ActorMethod<
    [],
    Array<ExternalStorageDeleteTaskView>
  >,
  'listExternalStorageTargets' : ActorMethod<
    [],
    Array<ExternalStorageTargetView>
  >,
  'listLatestStorageEvents' : ActorMethod<[bigint], Array<StoredStorageEvent>>,
  'listOwnerEquivalentPrincipals' : ActorMethod<
    [],
    Array<OwnerEquivalentPrincipal>
  >,
  'listPendingAccessGrants' : ActorMethod<[], Array<PendingAccessGrant>>,
  'listStorageEvents' : ActorMethod<
    [[] | [bigint], bigint],
    Array<StoredStorageEvent>
  >,
  'listVersions' : ActorMethod<
    [ListVersionsArguments],
    Array<FileVersionDetails>
  >,
  'markAllVisibleStorageEventsRead' : ActorMethod<[], undefined>,
  'markStorageEventsRead' : ActorMethod<[bigint], undefined>,
  'move' : ActorMethod<[MoveArguments], undefined>,
  'prepareExternalBlobUpload' : ActorMethod<
    [PrepareExternalBlobUploadArgs],
    PrepareExternalBlobUploadResult
  >,
  'prepareThumbnailUpload' : ActorMethod<
    [PrepareThumbnailUploadArguments],
    PrepareThumbnailUploadResult
  >,
  'processDurableAccessPolicies' : ActorMethod<
    [],
    Array<DurablePolicyProcessResult>
  >,
  'recordOwnerActivity' : ActorMethod<
    [RecordOwnerActivityArguments],
    OwnerActivityRecord
  >,
  'registerRecoveryController' : ActorMethod<
    [Principal],
    RegisterRecoveryControllerResult
  >,
  'releaseDurableAccessPolicy' : ActorMethod<
    [ReleaseDurableAccessPolicyArguments],
    DurablePolicyProcessResult
  >,
  'removeRecoveryOwner' : ActorMethod<[Principal], undefined>,
  'rename' : ActorMethod<[RenameArguments], undefined>,
  'requestAccess' : ActorMethod<[CreateAccessRequestArguments], AccessRequest>,
  'resolveAccessRequest' : ActorMethod<
    [ResolveAccessRequestArguments],
    AccessRequest
  >,
  'resolveBlobReadRoute' : ActorMethod<
    [ResolveBlobReadRouteArgs],
    ObjectStorageBlobReadRoute
  >,
  'resolveThumbnailReadRoute' : ActorMethod<
    [ResolveThumbnailReadRouteArgs],
    ObjectStorageBlobReadRoute
  >,
  'resolveUploadRoute' : ActorMethod<
    [ResolveUploadRouteArgs],
    ObjectStorageUploadRoute
  >,
  'restoreVersion' : ActorMethod<[RestoreVersionArguments], undefined>,
  'revalidateExternalStorageTarget' : ActorMethod<
    [ExternalStorageTargetId],
    ExternalStorageTargetView
  >,
  'revokeAccessBatch' : ActorMethod<
    [RevokeAccessBatchArguments],
    RevokeAccessBatchResult
  >,
  'rewrapThumbnail' : ActorMethod<
    [{ 'thumbnailRef' : ThumbnailRef, 'entry' : Entry }],
    NodeDetails
  >,
  'runExternalStorageDeleteTask' : ActorMethod<
    [bigint],
    ExternalStorageDeleteTaskView
  >,
  'runNextExternalStorageDeleteTask' : ActorMethod<
    [],
    ExternalStorageDeleteTaskView
  >,
  'setThumbnail' : ActorMethod<[SetThumbnailArguments], NodeDetails>,
  'showTree' : ActorMethod<[[] | [Entry]], string>,
  'sweepExternalStorageCleanup' : ActorMethod<[], ExternalStorageCleanupStatus>,
  'takeRecoveryOwnership' : ActorMethod<[], OwnerEquivalentPrincipal>,
  'update' : ActorMethod<[UpdateArguments], undefined>,
  'updateDirectoryPolicy' : ActorMethod<
    [UpdateDirectoryPolicyArguments],
    NodeDetails
  >,
}
export type Entry = [{ 'File' : null } | { 'Directory' : null }, string];
export interface ExternalBlobReplica {
  'id' : string,
  'status' : BlobReplicaStatus,
  'pendingDeleteTaskId' : [] | [bigint],
  'rootHashHex' : RootHashHex,
  'sha256' : [] | [Uint8Array],
  'locator' : BlobLocator,
  'createdAt' : Time,
  'size' : bigint,
  'updatedAt' : Time,
  'targetId' : TargetId,
}
export interface ExternalStorageCleanupStatus {
  'doneTasks' : bigint,
  'pendingUploadSessions' : bigint,
  'nextAttemptAt' : [] | [Time],
  'activeReplicas' : bigint,
  'deletePendingReplicas' : bigint,
  'missingReplicas' : bigint,
  'runningTasks' : bigint,
  'credentialBlockedTargetIds' : Array<TargetId>,
  'pendingTasks' : bigint,
  'cancelledTasks' : bigint,
  'deletedReplicas' : bigint,
}
export interface ExternalStorageDeleteTaskView {
  'id' : bigint,
  'status' : DeleteTaskStatus,
  'rootHashHex' : RootHashHex,
  'nextAttemptAt' : Time,
  'keys' : Array<string>,
  'createdAt' : Time,
  'attempts' : bigint,
  'updatedAt' : Time,
  'replicaId' : [] | [string],
  'lastError' : [] | [string],
  'targetId' : TargetId,
}
export interface ExternalStorageHttpTransformArg {
  'context' : Uint8Array,
  'response' : HttpRequestResult,
}
export type ExternalStorageTargetId = string;
export interface ExternalStorageTargetView {
  'id' : TargetId,
  'status' : TargetStatus,
  'displayName' : [] | [string],
  'hasCredential' : boolean,
  'layoutVersion' : bigint,
  'kind' : TargetKind,
  'createdAt' : Time,
  'writeMode' : WriteMode,
  'lastValidatedAt' : [] | [Time],
  'readMode' : ReadMode,
  'version' : bigint,
  'updatedAt' : Time,
}
export interface ExternalTargetBlobLocator {
  'locator' : BlobLocator,
  'target' : TargetView,
}
export interface ExternalTargetBlobLocatorArgs {
  'rootHashHex' : RootHashHex,
  'targetId' : [] | [TargetId],
}
export interface FileMetadata {
  'storageBackend' : StorageBackend,
  'sha256' : [] | [Uint8Array],
  'thumbnailRef' : [] | [ThumbnailRef],
  'contentType' : string,
  'size' : bigint,
  'currentVersion' : bigint,
  'chunkCount' : bigint,
  'versionCount' : bigint,
}
export interface FileVersionDetails {
  'storageBackend' : StorageBackend,
  'sha256' : [] | [Uint8Array],
  'contentType' : string,
  'createdAt' : Time,
  'size' : bigint,
  'index' : bigint,
}
export interface FinishUploadSessionArguments {
  'sha256' : [] | [Uint8Array],
  'contentType' : string,
  'batchId' : BatchId,
}
export interface GetChunkArguments {
  'chunkIndex' : bigint,
  'entry' : Entry,
  'version' : [] | [bigint],
}
export interface HasPermissionArguments {
  'permission' : Permission,
  'user' : Principal,
  'entry' : [] | [Entry],
}
export interface HttpHeader { 'value' : string, 'name' : string }
export interface HttpRequestResult {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export type KeyId = [Owner, KeyName];
export type KeyId__2 = [Principal, Uint8Array];
export type KeyName = Uint8Array;
export interface ListAccessGrantsArguments {
  'mode' : AccessGrantListMode,
  'scope' : [] | [AccessScope],
}
export interface ListResponse {
  'entries' : Array<NodeDetails>,
  'directoryPermission' : [] | [Permission],
}
export interface ListVersionsArguments { 'entry' : Entry }
export interface ListedPendingAccessGrant {
  'inheritedFrom' : [] | [AccessScope],
  'grant' : PendingAccessGrant,
}
export interface ListedPrincipalAccessGrant {
  'inheritedFrom' : [] | [AccessScope],
  'grant' : PrincipalAccessGrant,
}
export interface MoveArguments { 'entry' : Entry, 'target' : [] | [Entry] }
export interface NodeDetails {
  'id' : bigint,
  'modifiedAt' : [] | [Time],
  'metadata' : { 'File' : FileMetadata } |
    { 'Directory' : DirectoryMetadata },
  'name' : string,
  'createdAt' : Time,
  'callerPermission' : [] | [Permission],
  'sharing' : [] | [SharingInfo],
  'parentId' : [] | [bigint],
  'keyId' : KeyId,
}
export type ObjectStorageBlobReadRoute = { 'CaffeineBlobStorage' : null } |
  {
    'ExternalS3PublicEncrypted' : {
      'locator' : BlobLocator,
      'target' : TargetView,
    }
  } |
  { 'OnChain' : null };
export type ObjectStorageUploadRoute = { 'ExternalS3SetupRequired' : null } |
  { 'CaffeineBlobStorage' : null } |
  {
    'ExternalS3' : {
      'layoutVersion' : bigint,
      'writeMode' : WriteMode,
      'readMode' : ReadMode,
      'targetVersion' : bigint,
      'targetId' : TargetId,
    }
  } |
  { 'OnChain' : null };
export type Owner = Principal;
export type OwnerActivityOrigin = { 'storage' : null } |
  { 'rabbithole' : null } |
  { 'backend' : null };
export interface OwnerActivityRecord {
  'principal' : Principal,
  'lastSeenAt' : Time,
  'origin' : OwnerActivityOrigin,
  'role' : OwnerActivityRole,
}
export type OwnerActivityRole = { 'recoveryOwner' : null } |
  { 'accountOwner' : null };
export interface OwnerActivityState {
  'records' : Array<OwnerActivityRecord>,
  'lastOwnerActivityAt' : Time,
  'lastOwnerActivityBy' : Principal,
}
export interface OwnerEquivalentPrincipal {
  'principal' : Principal,
  'rootPermissionBeforeRecovery' : [] | [Permission],
  'kind' : { 'recoveryOwner' : null } |
    { 'accountOwner' : null },
  'controllerRecoveryEnabled' : boolean,
  'addedAt' : Time,
  'addedBy' : Principal,
  'revokedAt' : [] | [Time],
}
export interface PendingAccessGrant {
  'id' : bigint,
  'ref' : AccessRef,
  'permission' : Permission,
  'expiresAt' : [] | [Time],
  'emailClaimState' : EmailClaimState,
  'source' : AccessSource,
  'createdAt' : Time,
  'createdBy' : Principal,
  'claimedAt' : [] | [Time],
  'claimedBy' : [] | [Principal],
  'scope' : AccessScope,
  'cancelledAt' : [] | [Time],
  'accessClass' : AccessClass,
}
export type Permission = { 'Read' : null } |
  { 'ReadWrite' : null } |
  { 'ReadWriteManage' : null };
export interface PrepareExternalBlobUploadArgs {
  'rootHashHex' : string,
  'size' : bigint,
  'entry' : Entry,
  'targetId' : [] | [ExternalStorageTargetId],
  'expiresSeconds' : [] | [bigint],
}
export interface PrepareExternalBlobUploadResult {
  'blobUpload' : PresignedUrl,
  'locator' : BlobLocator,
  'target' : TargetView,
  'treeUpload' : PresignedUrl,
}
export interface PrepareThumbnailUploadArguments {
  'contentType' : string,
  'size' : bigint,
  'entry' : Entry,
}
export interface PrepareThumbnailUploadResult {
  'storageBackend' : StorageBackend,
  'contentType' : string,
  'size' : bigint,
  'encryption' : ThumbnailEncryptionRequirement,
}
export interface PresignedUrl {
  'key' : string,
  'url' : string,
  'method' : string,
  'expiresAt' : Time,
  'signedHeaders' : Array<[string, string]>,
  'requestHeaders' : Array<[string, string]>,
}
export interface PrincipalAccessGrant {
  'id' : bigint,
  'permission' : Permission,
  'principal' : Principal,
  'source' : AccessSource,
  'createdAt' : Time,
  'createdBy' : Principal,
  'scope' : AccessScope,
  'accessClass' : AccessClass,
  'revokedAt' : [] | [Time],
}
export type ReadMode = { 'PublicEncrypted' : null };
export interface RecordOwnerActivityArguments { 'origin' : OwnerActivityOrigin }
export interface RecoveryStatus {
  'recoveryOwner' : [] | [OwnerEquivalentPrincipal],
  'recoveryController' : [] | [Principal],
}
export interface RegisterRecoveryControllerResult {
  'principal' : Principal,
  'previous' : [] | [Principal],
}
export interface ReleaseDurableAccessPolicyArguments { 'policyId' : bigint }
export interface RenameArguments { 'entry' : Entry, 'newName' : string }
export interface ResolveAccessRequestArguments {
  'decision' : AccessRequestDecision,
  'requestId' : bigint,
}
export interface ResolveBlobReadRouteArgs {
  'entry' : Entry,
  'version' : [] | [bigint],
}
export interface ResolveThumbnailReadRouteArgs {
  'entry' : Entry,
  'rootHash' : string,
}
export interface ResolveUploadRouteArgs { 'size' : bigint, 'entry' : Entry }
export interface RestoreVersionArguments { 'entry' : Entry, 'version' : bigint }
export interface RevokeAccessBatchArguments {
  'items' : Array<RevokeAccessBatchItem>,
}
export interface RevokeAccessBatchItem {
  'principal' : Principal,
  'scope' : AccessScope,
}
export interface RevokeAccessBatchResult {
  'revoked' : Array<RevokeAccessBatchItem>,
}
export type RootHashHex = string;
export interface S3CompatibleTargetConfig {
  'region' : string,
  'endpoint' : string,
  'prefix' : string,
  'bucket' : string,
  'forcePathStyle' : boolean,
}
export interface SetThumbnailArguments {
  'thumbnailRef' : [] | [ThumbnailRef],
  'entry' : Entry,
}
export interface SharingInfo { 'sharedWith' : bigint }
export type StorageAccessEvent = {
    'accessRequestResolved' : {
      'status' : AccessRequestStatus,
      'requestId' : bigint,
      'requester' : Principal,
    }
  } |
  {
    'durablePolicyCreated' : {
      'status' : DurablePolicyStatus,
      'trigger' : DurablePolicyTrigger,
      'policyId' : bigint,
    }
  } |
  {
    'accessRequestCreated' : { 'requestId' : bigint, 'requester' : Principal }
  } |
  {
    'recoveryControllerRegistered' : {
      'principal' : Principal,
      'previous' : [] | [Principal],
    }
  } |
  {
    'pendingGrantCreated' : {
      'ref' : AccessRef,
      'source' : AccessSource,
      'grantId' : bigint,
      'accessClass' : AccessClass,
    }
  } |
  {
    'ownerActivityRecorded' : {
      'principal' : Principal,
      'origin' : OwnerActivityOrigin,
      'role' : OwnerActivityRole,
    }
  } |
  { 'durablePolicyReleased' : { 'policyId' : bigint } } |
  { 'recoveryControllerCleared' : { 'principal' : Principal } } |
  { 'durablePolicyMatured' : { 'policyId' : bigint } } |
  { 'recoveryOwnerAdded' : { 'principal' : Principal } } |
  {
    'pendingGrantClaimed' : {
      'principal' : Principal,
      'emailClaimState' : [] | [EmailClaimState],
      'source' : AccessSource,
      'grantId' : bigint,
      'claimOrigin' : [] | [EmailClaimOrigin],
      'accessClass' : AccessClass,
    }
  } |
  { 'durablePolicyCancelled' : { 'policyId' : bigint } } |
  {
    'accessRequestCancelled' : { 'requestId' : bigint, 'requester' : Principal }
  } |
  {
    'principalGrantCreated' : {
      'principal' : Principal,
      'source' : AccessSource,
      'grantId' : [] | [bigint],
      'accessClass' : AccessClass,
    }
  } |
  { 'pendingGrantCancelled' : { 'ref' : AccessRef, 'grantId' : bigint } } |
  { 'durablePolicyGraceStarted' : { 'policyId' : bigint } } |
  {
    'principalGrantRevoked' : {
      'principal' : Principal,
      'accessClass' : [] | [AccessClass],
    }
  } |
  { 'recoveryOwnerRemoved' : { 'principal' : Principal } };
export type StorageBackend = { 'OnChain' : null } |
  { 'BlobStorage' : null };
export type StorageEvent = { 'access' : StorageAccessEvent };
export interface StoredStorageEvent {
  'id' : bigint,
  'visibleTo' : Array<Principal>,
  'event' : StorageEvent,
  'timestamp' : Time,
  'correlationId' : [] | [string],
}
export type TargetId = string;
export type TargetKind = {
    'S3CompatiblePublicEncrypted' : S3CompatibleTargetConfig
  };
export type TargetStatus = { 'Active' : null } |
  { 'Disabled' : null } |
  { 'CredentialFailed' : null };
export interface TargetView {
  'id' : TargetId,
  'status' : TargetStatus,
  'displayName' : [] | [string],
  'hasCredential' : boolean,
  'layoutVersion' : bigint,
  'kind' : TargetKind,
  'createdAt' : Time,
  'writeMode' : WriteMode,
  'lastValidatedAt' : [] | [Time],
  'readMode' : ReadMode,
  'version' : bigint,
  'updatedAt' : Time,
}
export interface ThumbnailEncryptionRef {
  'algorithm' : string,
  'wrappedKey' : Uint8Array,
  'blobIv' : Uint8Array,
  'scopeKeyId' : KeyId,
}
export interface ThumbnailEncryptionRequirement { 'scopeKeyId' : KeyId }
export type ThumbnailRef = {
    'OnChain' : {
      'key' : string,
      'sha256' : [] | [Uint8Array],
      'contentType' : string,
      'size' : bigint,
      'encryption' : ThumbnailEncryptionRef,
    }
  } |
  {
    'BlobStorage' : {
      'sha256' : [] | [Uint8Array],
      'contentType' : string,
      'size' : bigint,
      'encryption' : ThumbnailEncryptionRef,
      'blobId' : Uint8Array,
      'rootHash' : string,
    }
  };
export type ThumbnailStoragePolicy = { 'OnChain' : null } |
  { 'BlobStorage' : null } |
  { 'Inherit' : null };
export type Time = bigint;
export type TransportKey = Uint8Array;
export interface TreeNode {
  'name' : string,
  'children' : [] | [Array<TreeNode>],
}
export type UpdateArguments = {
    'File' : {
      'metadata' : {
        'sha256' : [] | [Uint8Array],
        'contentType' : string,
        'chunkIds' : Array<ChunkId>,
      },
      'path' : string,
    }
  } |
  {
    'Directory' : {
      'metadata' : { 'color' : [] | [DirectoryColor] },
      'path' : string,
    }
  };
export interface UpdateDirectoryPolicyArguments {
  'entry' : Entry,
  'thumbnailStoragePolicy' : [] | [ThumbnailStoragePolicy],
}
export type VetKey = Uint8Array;
export type VetKeyVerificationKey = Uint8Array;
export type WriteMode = { 'CanisterPresigned' : null };
export interface _SERVICE extends EncryptedStorageCanister {}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];