/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AccessClass =
  | { ordinary: null }
  | { ownerEquivalent: null }
  | { durable: null };
export interface AccessGrantList {
  pendingGrants: Array<ListedPendingAccessGrant>;
  principalGrants: Array<ListedPrincipalAccessGrant>;
  mode: AccessGrantListMode;
  scope: AccessScope;
}
export type AccessGrantListMode = { effective: null } | { exact: null };
export type AccessRef =
  | { principal: Principal }
  | { emailCommitment: EmailCommitment }
  | { email: { emailCommitment: EmailCommitment; email: string } };
export interface AccessRequest {
  id: bigint;
  status: AccessRequestStatus;
  requester: Principal;
  createdAt: Time;
  emailCommitment: [] | [EmailCommitment];
  message: [] | [string];
  decidedAt: [] | [Time];
  decidedBy: [] | [Principal];
}
export type AccessRequestDecision =
  | {
      approved: { permission: Permission; scope: AccessScope };
    }
  | { rejected: null };
export type AccessRequestStatus =
  | { cancelled: null }
  | { pending: null }
  | { approved: null }
  | { rejected: null };
export type AccessScope =
  | { root: null }
  | { entry: Entry }
  | { keyId: KeyId__1 };
export type AccessSource =
  | { durablePolicy: bigint }
  | { accessRequest: bigint }
  | { directGrant: null }
  | { ordinaryInvite: bigint }
  | { recoverySetup: null };
export interface AddRecoveryOwnerOptions {
  controllerRecovery: boolean;
}
export type BatchId = bigint;
export interface CancelAccessRequestArguments {
  requestId: bigint;
}
export interface CancelPendingAccessGrantArguments {
  grantId: bigint;
}
export interface ChunkContent {
  content: Uint8Array;
}
export type ChunkId = bigint;
export interface ClaimPendingAccessByBackendAttestationArguments {
  principal: Principal;
  emailCommitments: Array<EmailCommitment>;
}
export interface ClaimPendingAccessGrantArguments {
  grantId: bigint;
}
export interface CreateAccessBatchArguments {
  items: Array<CreateAccessBatchItem>;
}
export interface CreateAccessBatchItem {
  ref: AccessRef;
  permission: Permission;
  expiresAt: [] | [Time];
  source: AccessSource;
  scope: AccessScope;
  accessClass: AccessClass;
}
export interface CreateAccessBatchResult {
  pendingGrants: Array<PendingAccessGrant>;
  revokedPrincipalGrants: Array<PrincipalAccessGrant>;
  principalGrants: Array<PrincipalAccessGrant>;
  cancelledPendingGrants: Array<PendingAccessGrant>;
}
export interface CreateAccessRequestArguments {
  emailCommitment: [] | [EmailCommitment];
  message: [] | [string];
}
export interface CreateArguments {
  createMode: CreateMode;
  entry: Entry;
  encryptionMode: [] | [EncryptionMode];
}
export interface CreateBatchResponse {
  batchId: BatchId;
}
export interface CreateChunkArguments {
  content: Uint8Array;
  batchId: BatchId;
}
export interface CreateChunkResponse {
  chunkId: bigint;
}
export interface CreateDurableAccessGrantArguments {
  permission: Permission;
  principal: Principal;
  source: AccessSource;
  scope: AccessScope;
}
export type CreateMode = { GetOrCreate: null } | { CreateNew: null };
export interface CreatePendingAccessGrantArguments {
  ref: AccessRef;
  permission: Permission;
  expiresAt: [] | [Time];
  source: AccessSource;
  scope: AccessScope;
  accessClass: AccessClass;
}
export interface DeleteArguments {
  recursive: boolean;
  entry: Entry;
}
export type DirectoryColor =
  | { blue: null }
  | { gray: null }
  | { orange: null }
  | { pink: null }
  | { purple: null }
  | { green: null }
  | { yellow: null };
export interface DirectoryMetadata {
  color: [] | [DirectoryColor];
  defaultEncryptionMode: EncryptionMode;
}
export interface EmailClaim {
  principalGrantId: bigint;
  principal: Principal;
  origin: EmailClaimOrigin;
  claimedAt: Time;
}
export type EmailClaimOrigin = { storage: null } | { rabbithole: null };
export interface EmailClaimState {
  storage: [] | [EmailClaim];
  rabbithole: [] | [EmailClaim];
}
export type EmailCommitment = Uint8Array;
export interface EncryptedStorageCanister {
  activateRecoveryOwnership: ActorMethod<[Principal], OwnerEquivalentPrincipal>;
  addRecoveryOwner: ActorMethod<
    [Principal, AddRecoveryOwnerOptions],
    OwnerEquivalentPrincipal
  >;
  cancelAccessRequest: ActorMethod<
    [CancelAccessRequestArguments],
    AccessRequest
  >;
  cancelPendingAccessGrant: ActorMethod<
    [CancelPendingAccessGrantArguments],
    PendingAccessGrant
  >;
  claimPendingAccessByBackendAttestation: ActorMethod<
    [ClaimPendingAccessByBackendAttestationArguments],
    Array<PrincipalAccessGrant>
  >;
  claimPendingAccessGrant: ActorMethod<
    [ClaimPendingAccessGrantArguments],
    PrincipalAccessGrant
  >;
  clear: ActorMethod<[], undefined>;
  clearRecoveryController: ActorMethod<[], Principal>;
  create: ActorMethod<[CreateArguments], NodeDetails>;
  createAccessBatch: ActorMethod<
    [CreateAccessBatchArguments],
    CreateAccessBatchResult
  >;
  createBatch: ActorMethod<[CreateArguments], CreateBatchResponse>;
  createChunk: ActorMethod<[CreateChunkArguments], CreateChunkResponse>;
  createDurableAccessGrant: ActorMethod<
    [CreateDurableAccessGrantArguments],
    PrincipalAccessGrant
  >;
  createPendingAccessGrant: ActorMethod<
    [CreatePendingAccessGrantArguments],
    PendingAccessGrant
  >;
  delete: ActorMethod<[DeleteArguments], undefined>;
  fsTree: ActorMethod<[], Array<TreeNode>>;
  getChunk: ActorMethod<[GetChunkArguments], ChunkContent>;
  getEncryptedVetkey: ActorMethod<[KeyId, TransportKey], VetKey>;
  /**
   * / Get canister module_hash via canister_status.
   * / Only accessible by canister controllers.
   */
  getModuleHash: ActorMethod<[], [] | [Uint8Array]>;
  getMyAccessRequest: ActorMethod<[], [] | [AccessRequest]>;
  getRecoveryStatus: ActorMethod<[], RecoveryStatus>;
  getStorageEventsUnreadCount: ActorMethod<[], bigint>;
  getVetkeyVerificationKey: ActorMethod<[], VetKeyVerificationKey>;
  hasPermission: ActorMethod<[HasPermissionArguments], boolean>;
  list: ActorMethod<[[] | [Entry]], ListResponse>;
  listAccessGrants: ActorMethod<[ListAccessGrantsArguments], AccessGrantList>;
  listAccessRequests: ActorMethod<[], Array<AccessRequest>>;
  listOwnerEquivalentPrincipals: ActorMethod<
    [],
    Array<OwnerEquivalentPrincipal>
  >;
  listPendingAccessGrants: ActorMethod<[], Array<PendingAccessGrant>>;
  listStorageEvents: ActorMethod<
    [[] | [bigint], bigint],
    Array<StoredStorageEvent>
  >;
  listLatestStorageEvents: ActorMethod<[bigint], Array<StoredStorageEvent>>;
  listVersions: ActorMethod<[ListVersionsArguments], Array<FileVersionDetails>>;
  markStorageEventsRead: ActorMethod<[bigint], undefined>;
  markAllVisibleStorageEventsRead: ActorMethod<[], undefined>;
  move: ActorMethod<[MoveArguments], undefined>;
  registerRecoveryController: ActorMethod<
    [Principal],
    RegisterRecoveryControllerResult
  >;
  removeRecoveryOwner: ActorMethod<[Principal], undefined>;
  rename: ActorMethod<[RenameArguments], undefined>;
  requestAccess: ActorMethod<[CreateAccessRequestArguments], AccessRequest>;
  resolveAccessRequest: ActorMethod<
    [ResolveAccessRequestArguments],
    AccessRequest
  >;
  restoreVersion: ActorMethod<[RestoreVersionArguments], undefined>;
  revokeAccessBatch: ActorMethod<
    [RevokeAccessBatchArguments],
    RevokeAccessBatchResult
  >;
  setThumbnail: ActorMethod<[SetThumbnailArguments], NodeDetails>;
  showTree: ActorMethod<[[] | [Entry]], string>;
  takeRecoveryOwnership: ActorMethod<[], OwnerEquivalentPrincipal>;
  update: ActorMethod<[UpdateArguments], undefined>;
}
export type EncryptionMode = { Encrypted: null } | { Plaintext: null };
export type Entry = [{ File: null } | { Directory: null }, string];
export interface FileMetadata {
  storageBackend: StorageBackend;
  sha256: [] | [Uint8Array];
  thumbnailKey: [] | [string];
  contentType: string;
  size: bigint;
  currentVersion: bigint;
  encryptionMode: EncryptionMode;
  chunkCount: bigint;
  versionCount: bigint;
}
export interface FileVersionDetails {
  storageBackend: StorageBackend;
  sha256: [] | [Uint8Array];
  contentType: string;
  createdAt: Time;
  size: bigint;
  index: bigint;
}
export interface GetChunkArguments {
  chunkIndex: bigint;
  entry: Entry;
  version: [] | [bigint];
}
export interface HasPermissionArguments {
  permission: Permission;
  user: Principal;
  entry: [] | [Entry];
}
export type KeyId = [Owner, KeyName];
export type KeyId__1 = [Principal, Uint8Array];
export type KeyName = Uint8Array;
export interface ListAccessGrantsArguments {
  mode: AccessGrantListMode;
  scope: [] | [AccessScope];
}
export interface ListResponse {
  entries: Array<NodeDetails>;
  directoryPermission: [] | [Permission];
}
export interface ListVersionsArguments {
  entry: Entry;
}
export interface ListedPendingAccessGrant {
  inheritedFrom: [] | [AccessScope];
  grant: PendingAccessGrant;
}
export interface ListedPrincipalAccessGrant {
  inheritedFrom: [] | [AccessScope];
  grant: PrincipalAccessGrant;
}
export interface MoveArguments {
  entry: Entry;
  target: [] | [Entry];
}
export interface NodeDetails {
  id: bigint;
  modifiedAt: [] | [Time];
  metadata: { File: FileMetadata } | { Directory: DirectoryMetadata };
  name: string;
  createdAt: Time;
  callerPermission: [] | [Permission];
  sharing: [] | [SharingInfo];
  parentId: [] | [bigint];
  keyId: KeyId;
}
export type Owner = Principal;
export interface OwnerEquivalentPrincipal {
  principal: Principal;
  rootPermissionBeforeRecovery: [] | [Permission];
  kind: { recoveryOwner: null } | { accountOwner: null };
  controllerRecoveryEnabled: boolean;
  addedAt: Time;
  addedBy: Principal;
  revokedAt: [] | [Time];
}
export interface PendingAccessGrant {
  id: bigint;
  ref: AccessRef;
  permission: Permission;
  expiresAt: [] | [Time];
  emailClaimState: EmailClaimState;
  source: AccessSource;
  createdAt: Time;
  createdBy: Principal;
  claimedAt: [] | [Time];
  claimedBy: [] | [Principal];
  scope: AccessScope;
  cancelledAt: [] | [Time];
  accessClass: AccessClass;
}
export type Permission =
  | { Read: null }
  | { ReadWrite: null }
  | { ReadWriteManage: null };
export interface PrincipalAccessGrant {
  id: bigint;
  permission: Permission;
  principal: Principal;
  source: AccessSource;
  createdAt: Time;
  createdBy: Principal;
  scope: AccessScope;
  accessClass: AccessClass;
  revokedAt: [] | [Time];
}
export interface RecoveryStatus {
  recoveryOwner: [] | [OwnerEquivalentPrincipal];
  recoveryController: [] | [Principal];
}
export interface RegisterRecoveryControllerResult {
  principal: Principal;
  previous: [] | [Principal];
}
export interface RenameArguments {
  entry: Entry;
  newName: string;
}
export interface ResolveAccessRequestArguments {
  decision: AccessRequestDecision;
  requestId: bigint;
}
export interface RestoreVersionArguments {
  entry: Entry;
  version: bigint;
}
export interface RevokeAccessBatchArguments {
  items: Array<RevokeAccessBatchItem>;
}
export interface RevokeAccessBatchItem {
  principal: Principal;
  scope: AccessScope;
}
export interface RevokeAccessBatchResult {
  revoked: Array<RevokeAccessBatchItem>;
}
export interface SetThumbnailArguments {
  thumbnailKey: [] | [string];
  entry: Entry;
}
export interface SharingInfo {
  sharedWith: bigint;
}
export type StorageAccessEvent =
  | {
      accessRequestResolved: {
        status: AccessRequestStatus;
        requestId: bigint;
        requester: Principal;
      };
    }
  | {
      accessRequestCreated: { requestId: bigint; requester: Principal };
    }
  | {
      recoveryControllerRegistered: {
        principal: Principal;
        previous: [] | [Principal];
      };
    }
  | {
      pendingGrantCreated: {
        ref: AccessRef;
        source: AccessSource;
        grantId: bigint;
        accessClass: AccessClass;
      };
    }
  | { recoveryControllerCleared: { principal: Principal } }
  | { recoveryOwnerAdded: { principal: Principal } }
  | {
      pendingGrantClaimed: {
        principal: Principal;
        emailClaimState: [] | [EmailClaimState];
        source: AccessSource;
        grantId: bigint;
        claimOrigin: [] | [EmailClaimOrigin];
        accessClass: AccessClass;
      };
    }
  | {
      accessRequestCancelled: { requestId: bigint; requester: Principal };
    }
  | {
      principalGrantCreated: {
        principal: Principal;
        source: AccessSource;
        grantId: [] | [bigint];
        accessClass: AccessClass;
      };
    }
  | { pendingGrantCancelled: { ref: AccessRef; grantId: bigint } }
  | {
      principalGrantRevoked: {
        principal: Principal;
        accessClass: [] | [AccessClass];
      };
    }
  | { recoveryOwnerRemoved: { principal: Principal } };
export type StorageBackend = { OnChain: null } | { BlobStorage: null };
export type StorageEvent = { access: StorageAccessEvent };
export interface StoredStorageEvent {
  id: bigint;
  visibleTo: Array<Principal>;
  event: StorageEvent;
  timestamp: Time;
  correlationId: [] | [string];
}
export type Time = bigint;
export type TransportKey = Uint8Array;
export interface TreeNode {
  name: string;
  children: [] | [Array<TreeNode>];
}
export type UpdateArguments =
  | {
      File: {
        metadata: {
          sha256: [] | [Uint8Array];
          contentType: string;
          chunkIds: Array<ChunkId>;
        };
        path: string;
      };
    }
  | {
      Directory: {
        metadata: { color: [] | [DirectoryColor] };
        path: string;
      };
    };
export type VetKey = Uint8Array;
export type VetKeyVerificationKey = Uint8Array;
export interface _SERVICE extends EncryptedStorageCanister {}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
