/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AccessClass = { 'ordinary' : null } |
  { 'ownerEquivalent' : null } |
  { 'durable' : null };
export interface AccessGrantList {
  'pendingGrants' : Array<ListedPendingAccessGrant>,
  'principalGrants' : Array<ListedPrincipalAccessGrant>,
  'mode' : AccessGrantListMode,
  'scope' : AccessScope,
}
export type AccessGrantListMode = { 'effective' : null } |
  { 'exact' : null };
export type AccessRef = { 'principal' : Principal } |
  { 'emailCommitment' : EmailCommitment } |
  { 'email' : { 'emailCommitment' : EmailCommitment, 'email' : string } };
export interface AccessRequest {
  'id' : bigint,
  'status' : AccessRequestStatus,
  'requester' : Principal,
  'createdAt' : Time,
  'emailCommitment' : [] | [EmailCommitment],
  'message' : [] | [string],
  'decidedAt' : [] | [Time],
  'decidedBy' : [] | [Principal],
}
export type AccessRequestDecision = {
    'approved' : { 'permission' : Permission__1, 'scope' : AccessScope }
  } |
  { 'rejected' : null };
export type AccessRequestStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type AccessScope = { 'root' : null } |
  { 'entry' : Entry } |
  { 'keyId' : KeyId__2 };
export type AccessSource = { 'durablePolicy' : bigint } |
  { 'accessRequest' : bigint } |
  { 'directGrant' : null } |
  { 'ordinaryInvite' : bigint } |
  { 'recoverySetup' : null };
export interface ActiveUploadProjection {
  'uploadedChunkCount' : bigint,
  'reservationBytes' : bigint,
  'uploadedBytes' : bigint,
  'remainingBytes' : bigint,
  'sessionCount' : bigint,
  'remainingChunkCount' : bigint,
  'encryptedSessionCount' : bigint,
}
export interface AddRecoveryOwnerOptions { 'controllerRecovery' : boolean }
export interface AssetDetails {
  'key' : Key,
  'encodings' : Array<AssetEncodingDetails>,
  'content_type' : string,
}
export interface AssetEncodingDetails {
  'modified' : Time,
  'sha256' : [] | [Uint8Array],
  'length' : bigint,
  'content_encoding' : string,
}
export type BatchId = bigint;
export type BatchOperationKind = {
    'SetAssetProperties' : SetAssetPropertiesArguments
  } |
  { 'CreateAsset' : CreateAssetArguments } |
  { 'UnsetAssetContent' : UnsetAssetContentArguments } |
  { 'DeleteAsset' : DeleteAssetArguments } |
  { 'SetAssetContent' : SetAssetContentArguments } |
  { 'Clear' : ClearArguments };
export interface BeginUploadSessionArguments {
  'declaredUploadBytes' : [] | [bigint],
  'createMode' : CreateMode,
  'totalSize' : bigint,
  'expectedChunkCount' : [] | [bigint],
  'entry' : Entry,
  'encryptionMode' : [] | [EncryptionMode],
}
export interface BeginUploadSessionResponse {
  'node' : NodeDetails,
  'batchId' : BatchId,
}
export interface CallbackStreamingStrategy {
  'token' : StreamingToken,
  'callback' : [Principal, string],
}
export interface CancelAccessRequestArguments { 'requestId' : bigint }
export interface CancelDurableAccessPolicyArguments { 'policyId' : bigint }
export interface CancelPendingAccessGrantArguments { 'grantId' : bigint }
export interface CanisterCyclesCardMetrics {
  'memory' : UploadMemoryProjection,
  'safety' : CycleSafetyEnvelope,
  'runtimeMemory' : RuntimeMemoryMetrics,
  'balance' : bigint,
  'cost' : UploadCycleCostEstimate,
  'freezingThresholdSeconds' : bigint,
  'lastCommit' : [] | [LastUploadCommitMetrics],
  'activity' : ActiveUploadProjection,
  'funding' : CanisterCyclesFundingState,
}
export interface CanisterCyclesFundingState {
  'requestedTargetBalance' : bigint,
  'requestedBytes' : bigint,
  'lastRequestedAt' : [] | [Time],
  'lastCompletedAt' : [] | [Time],
  'lastError' : [] | [string],
  'inFlight' : boolean,
}
export interface CertifiedTree {
  'certificate' : Uint8Array,
  'tree' : Uint8Array,
}
export interface ChunkContent { 'content' : Uint8Array }
export type ChunkId = bigint;
export interface ClaimPendingAccessByBackendAttestationArguments {
  'principal' : Principal,
  'emailCommitments' : Array<EmailCommitment>,
}
export interface ClaimPendingAccessGrantArguments { 'grantId' : bigint }
export type ClearArguments = {};
export interface CommitBatchArguments {
  'batch_id' : BatchId,
  'operations' : Array<BatchOperationKind>,
}
export interface CommitCaffeineUploadArgs {
  'sha256' : Uint8Array,
  'contentType' : string,
  'size' : bigint,
  'entry' : Entry,
  'rootHash' : string,
}
export interface CommitProposedBatchArguments {
  'batch_id' : BatchId,
  'evidence' : Uint8Array,
}
export interface CommitThumbnailUploadArguments {
  'sha256' : Uint8Array,
  'contentType' : string,
  'size' : bigint,
  'encryption' : ThumbnailEncryptionRef,
  'entry' : Entry,
  'rootHash' : string,
}
export interface ComputeEvidenceArguments {
  'batch_id' : BatchId,
  'max_iterations' : [] | [number],
}
export interface ConfigurationResponse {
  'max_batches' : [] | [bigint],
  'max_bytes' : [] | [bigint],
  'max_chunks' : [] | [bigint],
}
export interface ConfigureArguments {
  'max_batches' : [] | [[] | [bigint]],
  'max_bytes' : [] | [[] | [bigint]],
  'max_chunks' : [] | [[] | [bigint]],
}
export interface CreateAccessBatchArguments {
  'items' : Array<CreateAccessBatchItem>,
}
export interface CreateAccessBatchItem {
  'ref' : AccessRef,
  'permission' : Permission__1,
  'expiresAt' : [] | [Time],
  'source' : AccessSource,
  'scope' : AccessScope,
  'accessClass' : AccessClass,
}
export interface CreateAccessBatchResult {
  'pendingGrants' : Array<PendingAccessGrant>,
  'revokedPrincipalGrants' : Array<PrincipalAccessGrant>,
  'principalGrants' : Array<PrincipalAccessGrant>,
  'cancelledPendingGrants' : Array<PendingAccessGrant>,
}
export interface CreateAccessRequestArguments {
  'emailCommitment' : [] | [EmailCommitment],
  'message' : [] | [string],
}
export interface CreateArguments {
  'createMode' : CreateMode,
  'entry' : Entry,
  'encryptionMode' : [] | [EncryptionMode],
}
export interface CreateAssetArguments {
  'key' : Key,
  'content_type' : string,
  'headers' : [] | [Array<Header>],
  'allow_raw_access' : [] | [boolean],
  'max_age' : [] | [bigint],
  'enable_aliasing' : [] | [boolean],
}
export interface CreateBatchResponse { 'batch_id' : BatchId }
export interface CreateChunkArguments {
  'content' : Uint8Array,
  'batch_id' : BatchId,
}
export interface CreateChunkArguments__1 {
  'content' : Uint8Array,
  'chunkIndex' : [] | [bigint],
  'batchId' : BatchId,
}
export interface CreateChunkResponse { 'chunk_id' : bigint }
export interface CreateChunkResponse__1 { 'chunkId' : bigint }
export interface CreateChunksArguments {
  'content' : Array<Uint8Array>,
  'batch_id' : BatchId,
}
export interface CreateChunksResponse { 'chunk_ids' : Array<ChunkId> }
export interface CreateDurableAccessGrantArguments {
  'permission' : Permission__1,
  'principal' : Principal,
  'source' : AccessSource,
  'scope' : AccessScope,
}
export interface CreateDurableAccessPolicyArguments {
  'grants' : Array<DurablePolicyGrantTemplate>,
  'trigger' : DurablePolicyTrigger,
  'recipients' : Array<AccessRef>,
}
export type CreateMode = { 'GetOrCreate' : null } |
  { 'CreateNew' : null };
export interface CreatePendingAccessGrantArguments {
  'ref' : AccessRef,
  'permission' : Permission__1,
  'expiresAt' : [] | [Time],
  'source' : AccessSource,
  'scope' : AccessScope,
  'accessClass' : AccessClass,
}
export interface CycleSafetyEnvelope {
  'minimumSafeBalance' : bigint,
  'targetBalance' : bigint,
  'operationFloorBalance' : bigint,
  'postWriteFreezingReserve' : bigint,
  'currentFreezingReserve' : bigint,
}
export interface DeleteArguments { 'recursive' : boolean, 'entry' : Entry }
export interface DeleteAssetArguments { 'key' : Key }
export interface DeleteBatchArguments { 'batch_id' : BatchId }
export type DirectoryColor = { 'blue' : null } |
  { 'gray' : null } |
  { 'orange' : null } |
  { 'pink' : null } |
  { 'purple' : null } |
  { 'green' : null } |
  { 'yellow' : null };
export type DirectoryEncryptionPolicy = { 'Encrypted' : null } |
  { 'Auto' : null } |
  { 'Plaintext' : null };
export interface DirectoryMetadata {
  'color' : [] | [DirectoryColor],
  'thumbnailEncryptionPolicy' : ThumbnailEncryptionPolicy,
  'defaultEncryptionMode' : EncryptionMode,
  'defaultThumbnailStorageBackend' : StorageBackend,
  'thumbnailStoragePolicy' : ThumbnailStoragePolicy,
  'encryptionPolicy' : DirectoryEncryptionPolicy,
}
export interface DurableAccessPolicy {
  'id' : bigint,
  'maturedAt' : [] | [Time],
  'status' : DurablePolicyStatus,
  'grants' : Array<DurablePolicyGrantTemplate>,
  'trigger' : DurablePolicyTrigger,
  'createdAt' : Time,
  'createdBy' : Principal,
  'cancelledAt' : [] | [Time],
  'proVerifiedAt' : Time,
  'recipients' : Array<AccessRef>,
  'releasedAt' : [] | [Time],
  'graceStartedAt' : [] | [Time],
  'principalGrantIds' : Array<bigint>,
  'pendingGrantIds' : Array<bigint>,
}
export interface DurablePolicyGrantTemplate {
  'permission' : Permission__1,
  'scope' : AccessScope,
}
export interface DurablePolicyProcessResult {
  'pendingGrants' : Array<PendingAccessGrant>,
  'principalGrants' : Array<PrincipalAccessGrant>,
  'policy' : DurableAccessPolicy,
}
export type DurablePolicyStatus = { 'cancelled' : null } |
  { 'armed' : null } |
  { 'released' : null } |
  { 'matured' : null } |
  { 'grace' : null };
export type DurablePolicyTrigger = { 'manualRelease' : null } |
  { 'date' : { 'releaseAt' : Time } } |
  {
    'inactivity' : { 'inactiveForNs' : bigint, 'gracePeriodNs' : [] | [bigint] }
  };
export interface EmailClaim {
  'principalGrantId' : bigint,
  'principal' : Principal,
  'origin' : EmailClaimOrigin,
  'claimedAt' : Time,
}
export type EmailClaimOrigin = { 'storage' : null } |
  { 'rabbithole' : null };
export interface EmailClaimState {
  'storage' : [] | [EmailClaim],
  'rabbithole' : [] | [EmailClaim],
}
export type EmailCommitment = Uint8Array;
export interface EncodedAsset {
  'content' : Uint8Array,
  'sha256' : [] | [Uint8Array],
  'content_type' : string,
  'content_encoding' : string,
  'total_length' : bigint,
}
export interface EncryptedStorageCanister {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result_1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'abortUploadSession' : ActorMethod<
    [{ 'batchId' : BatchId }],
    StorageResult_1
  >,
  'activateRecoveryOwnership' : ActorMethod<
    [Principal],
    OwnerEquivalentPrincipal
  >,
  'addRecoveryOwner' : ActorMethod<
    [Principal, AddRecoveryOwnerOptions],
    OwnerEquivalentPrincipal
  >,
  'api_version' : ActorMethod<[], number>,
  'appendUploadChunk' : ActorMethod<[CreateChunkArguments__1], StorageResult_6>,
  'beginUploadSession' : ActorMethod<
    [BeginUploadSessionArguments],
    StorageResult_5
  >,
  'cancelAccessRequest' : ActorMethod<
    [CancelAccessRequestArguments],
    AccessRequest
  >,
  'cancelDurableAccessPolicy' : ActorMethod<
    [CancelDurableAccessPolicyArguments],
    DurableAccessPolicy
  >,
  'cancelPendingAccessGrant' : ActorMethod<
    [CancelPendingAccessGrantArguments],
    PendingAccessGrant
  >,
  'certified_tree' : ActorMethod<[{}], CertifiedTree>,
  'claimPendingAccessByBackendAttestation' : ActorMethod<
    [ClaimPendingAccessByBackendAttestationArguments],
    Array<PrincipalAccessGrant>
  >,
  'claimPendingAccessGrant' : ActorMethod<
    [ClaimPendingAccessGrantArguments],
    PrincipalAccessGrant
  >,
  'claimVerifiedEmailAccess' : ActorMethod<[], IdentityAttributesSyncResult>,
  'clear' : ActorMethod<[ClearArguments], undefined>,
  'clearRecoveryController' : ActorMethod<[], Principal>,
  'clearStorage' : ActorMethod<[], undefined>,
  'commitCaffeineUpload' : ActorMethod<
    [CommitCaffeineUploadArgs],
    StorageResult_1
  >,
  'commitThumbnailUpload' : ActorMethod<
    [CommitThumbnailUploadArguments],
    NodeDetails
  >,
  'commit_batch' : ActorMethod<[CommitBatchArguments], undefined>,
  'commit_proposed_batch' : ActorMethod<
    [CommitProposedBatchArguments],
    undefined
  >,
  'compute_evidence' : ActorMethod<
    [ComputeEvidenceArguments],
    [] | [Uint8Array]
  >,
  'configure' : ActorMethod<[ConfigureArguments], undefined>,
  'create' : ActorMethod<[CreateArguments], StorageResult>,
  'createAccessBatch' : ActorMethod<
    [CreateAccessBatchArguments],
    CreateAccessBatchResult
  >,
  'createDurableAccessGrant' : ActorMethod<
    [CreateDurableAccessGrantArguments],
    PrincipalAccessGrant
  >,
  'createDurableAccessPolicy' : ActorMethod<
    [CreateDurableAccessPolicyArguments],
    DurableAccessPolicy
  >,
  'createPendingAccessGrant' : ActorMethod<
    [CreatePendingAccessGrantArguments],
    PendingAccessGrant
  >,
  'create_asset' : ActorMethod<[CreateAssetArguments], undefined>,
  'create_batch' : ActorMethod<[{}], CreateBatchResponse>,
  'create_chunk' : ActorMethod<[CreateChunkArguments], CreateChunkResponse>,
  'create_chunks' : ActorMethod<[CreateChunksArguments], CreateChunksResponse>,
  'delete' : ActorMethod<[DeleteArguments], undefined>,
  'delete_asset' : ActorMethod<[DeleteAssetArguments], undefined>,
  'delete_batch' : ActorMethod<[DeleteBatchArguments], undefined>,
  'finishUploadSession' : ActorMethod<
    [FinishUploadSessionArguments],
    StorageResult_1
  >,
  'fsTree' : ActorMethod<[], Array<TreeNode>>,
  'get' : ActorMethod<[GetArgs], EncodedAsset>,
  'getCanisterCyclesCardMetrics' : ActorMethod<[], StorageResult_3>,
  'getCycleBalance' : ActorMethod<[], bigint>,
  'getEncryptedVetkey' : ActorMethod<[KeyId, TransportKey], VetKey>,
  'getMyAccessRequest' : ActorMethod<[], [] | [AccessRequest]>,
  'getOwnerActivityState' : ActorMethod<[], OwnerActivityState>,
  'getRecoveryStatus' : ActorMethod<[], RecoveryStatus>,
  'getStatus' : ActorMethod<[], StorageStatus>,
  'getStorageBackendType' : ActorMethod<[], StorageBackend>,
  'getStorageCardMetrics' : ActorMethod<[], StorageResult_2>,
  'getStorageChunk' : ActorMethod<[GetChunkArguments], ChunkContent>,
  'getStorageEventsUnreadCount' : ActorMethod<[], bigint>,
  'getUploadSession' : ActorMethod<[{ 'batchId' : BatchId }], StorageResult_4>,
  'getVetkeyVerificationKey' : ActorMethod<[], VetKeyVerificationKey>,
  'get_chunk' : ActorMethod<[GetChunkArgs], ChunkContent>,
  'get_configuration' : ActorMethod<[], ConfigurationResponse>,
  'grant_permission' : ActorMethod<[GrantPermission], undefined>,
  'hasStoragePermission' : ActorMethod<[HasPermissionArguments], boolean>,
  'http_request' : ActorMethod<[RawQueryHttpRequest], RawQueryHttpResponse>,
  'http_request_streaming_callback' : ActorMethod<
    [StreamingToken],
    StreamingCallbackResponse
  >,
  'http_request_update' : ActorMethod<
    [RawUpdateHttpRequest],
    RawUpdateHttpResponse
  >,
  'invalidateSubscriptionCache' : ActorMethod<[], undefined>,
  'list' : ActorMethod<[{}], Array<AssetDetails>>,
  'listAccessGrants' : ActorMethod<
    [ListAccessGrantsArguments],
    AccessGrantList
  >,
  'listAccessRequests' : ActorMethod<[], Array<AccessRequest>>,
  'listDurableAccessPolicies' : ActorMethod<[], Array<DurableAccessPolicy>>,
  'listLatestStorageEvents' : ActorMethod<[bigint], Array<StoredStorageEvent>>,
  'listOwnerEquivalentPrincipals' : ActorMethod<
    [],
    Array<OwnerEquivalentPrincipal>
  >,
  'listPendingAccessGrants' : ActorMethod<[], Array<PendingAccessGrant>>,
  'listStorage' : ActorMethod<[[] | [Entry]], ListResponse>,
  'listStorageEvents' : ActorMethod<
    [[] | [bigint], bigint],
    Array<StoredStorageEvent>
  >,
  'listStorageVersions' : ActorMethod<
    [ListVersionsArguments],
    Array<FileVersionDetails>
  >,
  'list_permitted' : ActorMethod<[ListPermitted], Array<Principal>>,
  'markAllVisibleStorageEventsRead' : ActorMethod<[], undefined>,
  'markStorageEventsRead' : ActorMethod<[bigint], undefined>,
  'move' : ActorMethod<[MoveArguments], undefined>,
  'preflightCaffeineUpload' : ActorMethod<
    [PreflightCaffeineUploadArgs],
    StorageResult_1
  >,
  'prepareThumbnailUpload' : ActorMethod<
    [PrepareThumbnailUploadArguments],
    PrepareThumbnailUploadResult
  >,
  'processDurableAccessPolicies' : ActorMethod<
    [],
    Array<DurablePolicyProcessResult>
  >,
  'propose_commit_batch' : ActorMethod<[CommitBatchArguments], undefined>,
  'recordOwnerActivity' : ActorMethod<
    [RecordOwnerActivityArguments],
    OwnerActivityRecord
  >,
  'refreshCanisterCyclesCardMetrics' : ActorMethod<[], StorageResult_3>,
  'refreshStorageCardMetrics' : ActorMethod<[], StorageResult_2>,
  'refreshSubscription' : ActorMethod<[], undefined>,
  'registerRecoveryController' : ActorMethod<
    [Principal],
    RegisterRecoveryControllerResult
  >,
  'releaseDurableAccessPolicy' : ActorMethod<
    [ReleaseDurableAccessPolicyArguments],
    DurablePolicyProcessResult
  >,
  'removeRecoveryOwner' : ActorMethod<[Principal], undefined>,
  'rename' : ActorMethod<[RenameArguments], undefined>,
  'requestAccess' : ActorMethod<[CreateAccessRequestArguments], AccessRequest>,
  'resolveAccessRequest' : ActorMethod<
    [ResolveAccessRequestArguments],
    AccessRequest
  >,
  'restoreStorageVersion' : ActorMethod<[RestoreVersionArguments], undefined>,
  'revokeAccessBatch' : ActorMethod<
    [RevokeAccessBatchArguments],
    RevokeAccessBatchResult
  >,
  'revoke_permission' : ActorMethod<[RevokePermission], undefined>,
  'rewrapThumbnail' : ActorMethod<
    [{ 'thumbnailRef' : ThumbnailRef, 'entry' : Entry }],
    NodeDetails
  >,
  'saveThumbnail' : ActorMethod<
    [
      {
        'thumbnail' : {
          'content' : Uint8Array,
          'contentType' : string,
          'encryption' : ThumbnailEncryptionRef,
        },
        'entry' : Entry,
      },
    ],
    NodeDetails
  >,
  'set_asset_content' : ActorMethod<[SetAssetContentArguments], undefined>,
  'set_asset_properties' : ActorMethod<
    [SetAssetPropertiesArguments],
    undefined
  >,
  'showTree' : ActorMethod<[[] | [Entry]], string>,
  'store' : ActorMethod<[StoreArgs], undefined>,
  'takeRecoveryOwnership' : ActorMethod<[], OwnerEquivalentPrincipal>,
  'take_ownership' : ActorMethod<[], undefined>,
  'unset_asset_content' : ActorMethod<[UnsetAssetContentArguments], undefined>,
  'update' : ActorMethod<[UpdateArguments], StorageResult_1>,
  'updateDirectoryPolicy' : ActorMethod<
    [UpdateDirectoryPolicyArguments],
    StorageResult
  >,
  'validate_commit_proposed_batch' : ActorMethod<
    [CommitProposedBatchArguments],
    Result
  >,
  'validate_configure' : ActorMethod<[ConfigureArguments], Result>,
  'validate_grant_permission' : ActorMethod<[GrantPermission], Result>,
  'validate_revoke_permission' : ActorMethod<[RevokePermission], Result>,
  'validate_take_ownership' : ActorMethod<[], Result>,
}
export type EncryptionMode = { 'Encrypted' : null } |
  { 'Plaintext' : null };
export type Entry = [{ 'File' : null } | { 'Directory' : null }, string];
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface FileMetadata {
  'storageBackend' : StorageBackend,
  'sha256' : [] | [Uint8Array],
  'thumbnailRef' : [] | [ThumbnailRef],
  'contentType' : string,
  'size' : bigint,
  'currentVersion' : bigint,
  'encryptionMode' : EncryptionMode,
  'chunkCount' : bigint,
  'versionCount' : bigint,
}
export interface FileVersionDetails {
  'storageBackend' : StorageBackend,
  'sha256' : [] | [Uint8Array],
  'contentType' : string,
  'createdAt' : Time,
  'size' : bigint,
  'index' : bigint,
}
export interface FinishUploadSessionArguments {
  'sha256' : [] | [Uint8Array],
  'contentType' : string,
  'batchId' : BatchId,
}
export interface GetArgs { 'key' : Key, 'accept_encodings' : Array<string> }
export interface GetChunkArgs {
  'key' : Key,
  'sha256' : [] | [Uint8Array],
  'index' : bigint,
  'content_encoding' : string,
}
export interface GetChunkArguments {
  'chunkIndex' : bigint,
  'entry' : Entry,
  'version' : [] | [bigint],
}
export interface GrantPermission {
  'permission' : Permission,
  'to_principal' : Principal,
}
export interface HasPermissionArguments {
  'permission' : Permission__1,
  'user' : Principal,
  'entry' : [] | [Entry],
}
export type Header = [string, string];
export type IdentityAttributesSyncError = { 'expired' : null } |
  { 'malformedPayload' : null } |
  { 'verifiedEmailRequired' : null } |
  { 'attributesNotFound' : null };
export type IdentityAttributesSyncResult = { 'ok' : null } |
  { 'err' : IdentityAttributesSyncError };
export type Key = string;
export type KeyId = [Owner, KeyName];
export type KeyId__2 = [Principal, Uint8Array];
export type KeyName = Uint8Array;
export interface LastUploadCommitMetrics {
  'hashRoundCount' : bigint,
  'chunkCount' : bigint,
  'bytes' : bigint,
  'hashInstructionCycles' : bigint,
}
export interface ListAccessGrantsArguments {
  'mode' : AccessGrantListMode,
  'scope' : [] | [AccessScope],
}
export interface ListPermitted { 'permission' : Permission }
export interface ListResponse {
  'entries' : Array<NodeDetails>,
  'directoryPermission' : [] | [Permission__1],
}
export interface ListVersionsArguments { 'entry' : Entry }
export interface ListedPendingAccessGrant {
  'inheritedFrom' : [] | [AccessScope],
  'grant' : PendingAccessGrant,
}
export interface ListedPrincipalAccessGrant {
  'inheritedFrom' : [] | [AccessScope],
  'grant' : PrincipalAccessGrant,
}
export interface MemoryInfo {
  'allocated' : bigint,
  'size' : bigint,
  'deallocated' : bigint,
  'pages' : bigint,
  'capacity' : bigint,
}
export interface MoveArguments { 'entry' : Entry, 'target' : [] | [Entry] }
export interface NodeDetails {
  'id' : bigint,
  'modifiedAt' : [] | [Time],
  'metadata' : { 'File' : FileMetadata } |
    { 'Directory' : DirectoryMetadata },
  'name' : string,
  'createdAt' : Time,
  'callerPermission' : [] | [Permission__1],
  'sharing' : [] | [SharingInfo],
  'parentId' : [] | [bigint],
  'keyId' : KeyId,
}
export type Owner = Principal;
export type OwnerActivityOrigin = { 'storage' : null } |
  { 'rabbithole' : null } |
  { 'backend' : null };
export interface OwnerActivityRecord {
  'principal' : Principal,
  'lastSeenAt' : Time,
  'origin' : OwnerActivityOrigin,
  'role' : OwnerActivityRole,
}
export type OwnerActivityRole = { 'recoveryOwner' : null } |
  { 'accountOwner' : null };
export interface OwnerActivityState {
  'records' : Array<OwnerActivityRecord>,
  'lastOwnerActivityAt' : Time,
  'lastOwnerActivityBy' : Principal,
}
export interface OwnerEquivalentPrincipal {
  'principal' : Principal,
  'rootPermissionBeforeRecovery' : [] | [Permission__1],
  'kind' : { 'recoveryOwner' : null } |
    { 'accountOwner' : null },
  'controllerRecoveryEnabled' : boolean,
  'addedAt' : Time,
  'addedBy' : Principal,
  'revokedAt' : [] | [Time],
}
export interface PendingAccessGrant {
  'id' : bigint,
  'ref' : AccessRef,
  'permission' : Permission__1,
  'expiresAt' : [] | [Time],
  'emailClaimState' : EmailClaimState,
  'source' : AccessSource,
  'createdAt' : Time,
  'createdBy' : Principal,
  'claimedAt' : [] | [Time],
  'claimedBy' : [] | [Principal],
  'scope' : AccessScope,
  'cancelledAt' : [] | [Time],
  'accessClass' : AccessClass,
}
export type Permission = { 'Prepare' : null } |
  { 'Manage' : null } |
  { 'Commit' : null };
export type Permission__1 = { 'Read' : null } |
  { 'ReadWrite' : null } |
  { 'ReadWriteManage' : null };
export type Plan = { 'Pro' : null } |
  { 'Free' : null } |
  { 'License' : null };
export interface PreflightCaffeineUploadArgs {
  'size' : bigint,
  'entry' : Entry,
}
export interface PrepareThumbnailUploadArguments {
  'contentType' : string,
  'size' : bigint,
  'entry' : Entry,
}
export interface PrepareThumbnailUploadResult {
  'storageBackend' : StorageBackend,
  'contentType' : string,
  'size' : bigint,
  'encryption' : ThumbnailEncryptionRequirement,
}
export interface PrincipalAccessGrant {
  'id' : bigint,
  'permission' : Permission__1,
  'principal' : Principal,
  'source' : AccessSource,
  'createdAt' : Time,
  'createdBy' : Principal,
  'scope' : AccessScope,
  'accessClass' : AccessClass,
  'revokedAt' : [] | [Time],
}
export interface RawQueryHttpRequest {
  'url' : string,
  'method' : string,
  'body' : Uint8Array,
  'headers' : Array<Header>,
  'certificate_version' : [] | [number],
}
export interface RawQueryHttpResponse {
  'body' : Uint8Array,
  'headers' : Array<Header>,
  'upgrade' : [] | [boolean],
  'streaming_strategy' : [] | [StreamingStrategy],
  'status_code' : number,
}
export interface RawUpdateHttpRequest {
  'url' : string,
  'method' : string,
  'body' : Uint8Array,
  'headers' : Array<Header>,
}
export interface RawUpdateHttpResponse {
  'body' : Uint8Array,
  'headers' : Array<Header>,
  'streaming_strategy' : [] | [StreamingStrategy],
  'status_code' : number,
}
export interface RecordOwnerActivityArguments { 'origin' : OwnerActivityOrigin }
export interface RecoveryStatus {
  'recoveryOwner' : [] | [OwnerEquivalentPrincipal],
  'recoveryController' : [] | [Principal],
}
export interface RegisterRecoveryControllerResult {
  'principal' : Principal,
  'previous' : [] | [Principal],
}
export interface ReleaseDurableAccessPolicyArguments { 'policyId' : bigint }
export interface RenameArguments { 'entry' : Entry, 'newName' : string }
export interface ResolveAccessRequestArguments {
  'decision' : AccessRequestDecision,
  'requestId' : bigint,
}
export interface RestoreVersionArguments { 'entry' : Entry, 'version' : bigint }
export type Result = { 'ok' : string } |
  { 'err' : string };
export type Result_1 = { 'ok' : null } |
  { 'err' : Error };
export interface RevokeAccessBatchArguments {
  'items' : Array<RevokeAccessBatchItem>,
}
export interface RevokeAccessBatchItem {
  'principal' : Principal,
  'scope' : AccessScope,
}
export interface RevokeAccessBatchResult {
  'revoked' : Array<RevokeAccessBatchItem>,
}
export interface RevokePermission {
  'permission' : Permission,
  'of_principal' : Principal,
}
export interface RuntimeMemoryMetrics {
  'runtimeStableMemoryBytes' : [] | [bigint],
  'runtimeMemoryBytes' : [] | [bigint],
  'memoryInfo' : MemoryInfo,
}
export interface SetAssetContentArguments {
  'key' : Key,
  'sha256' : [] | [Uint8Array],
  'chunk_ids' : Array<ChunkId>,
  'content_encoding' : string,
}
export interface SetAssetPropertiesArguments {
  'key' : Key,
  'headers' : [] | [[] | [Array<Header>]],
  'is_aliased' : [] | [[] | [boolean]],
  'allow_raw_access' : [] | [[] | [boolean]],
  'max_age' : [] | [[] | [bigint]],
}
export interface SharingInfo { 'sharedWith' : bigint }
export type StorageAccessEvent = {
    'accessRequestResolved' : {
      'status' : AccessRequestStatus,
      'requestId' : bigint,
      'requester' : Principal,
    }
  } |
  {
    'durablePolicyCreated' : {
      'status' : DurablePolicyStatus,
      'trigger' : DurablePolicyTrigger,
      'policyId' : bigint,
    }
  } |
  {
    'accessRequestCreated' : { 'requestId' : bigint, 'requester' : Principal }
  } |
  {
    'recoveryControllerRegistered' : {
      'principal' : Principal,
      'previous' : [] | [Principal],
    }
  } |
  {
    'pendingGrantCreated' : {
      'ref' : AccessRef,
      'source' : AccessSource,
      'grantId' : bigint,
      'accessClass' : AccessClass,
    }
  } |
  {
    'ownerActivityRecorded' : {
      'principal' : Principal,
      'origin' : OwnerActivityOrigin,
      'role' : OwnerActivityRole,
    }
  } |
  { 'durablePolicyReleased' : { 'policyId' : bigint } } |
  { 'recoveryControllerCleared' : { 'principal' : Principal } } |
  { 'durablePolicyMatured' : { 'policyId' : bigint } } |
  { 'recoveryOwnerAdded' : { 'principal' : Principal } } |
  {
    'pendingGrantClaimed' : {
      'principal' : Principal,
      'emailClaimState' : [] | [EmailClaimState],
      'source' : AccessSource,
      'grantId' : bigint,
      'claimOrigin' : [] | [EmailClaimOrigin],
      'accessClass' : AccessClass,
    }
  } |
  { 'durablePolicyCancelled' : { 'policyId' : bigint } } |
  {
    'accessRequestCancelled' : { 'requestId' : bigint, 'requester' : Principal }
  } |
  {
    'principalGrantCreated' : {
      'principal' : Principal,
      'source' : AccessSource,
      'grantId' : [] | [bigint],
      'accessClass' : AccessClass,
    }
  } |
  { 'pendingGrantCancelled' : { 'ref' : AccessRef, 'grantId' : bigint } } |
  { 'durablePolicyGraceStarted' : { 'policyId' : bigint } } |
  {
    'principalGrantRevoked' : {
      'principal' : Principal,
      'accessClass' : [] | [AccessClass],
    }
  } |
  { 'recoveryOwnerRemoved' : { 'principal' : Principal } };
export type StorageBackend = { 'OnChain' : null } |
  { 'BlobStorage' : null };
export interface StorageCardMetrics {
  'runtimeStableMemoryBytes' : [] | [bigint],
  'runtimeMemoryBytes' : [] | [bigint],
  'encryptedBytesUsed' : bigint,
  'subscriptionStatus' : [] | [SubscriptionStatus],
  'backendId' : [] | [Principal],
  'storageBackendType' : StorageBackend,
  'memoryInfo' : MemoryInfo,
}
export interface StorageError { 'code' : StorageErrorCode, 'message' : string }
export type StorageErrorCode = { 'Internal' : null } |
  { 'FundingPending' : null } |
  { 'NotFound' : null } |
  { 'PermissionDenied' : null } |
  { 'InsufficientCycles' : null } |
  { 'Validation' : null } |
  { 'QuotaExceeded' : null } |
  { 'Conflict' : null };
export type StorageEvent = { 'access' : StorageAccessEvent };
export type StorageResult = { 'ok' : NodeDetails } |
  { 'err' : StorageError };
export type StorageResult_1 = { 'ok' : null } |
  { 'err' : StorageError };
export type StorageResult_2 = { 'ok' : StorageCardMetrics } |
  { 'err' : StorageError };
export type StorageResult_3 = { 'ok' : CanisterCyclesCardMetrics } |
  { 'err' : StorageError };
export type StorageResult_4 = { 'ok' : UploadSessionStatus } |
  { 'err' : StorageError };
export type StorageResult_5 = { 'ok' : BeginUploadSessionResponse } |
  { 'err' : StorageError };
export type StorageResult_6 = { 'ok' : CreateChunkResponse__1 } |
  { 'err' : StorageError };
export interface StorageStatus {
  'cycleBalance' : bigint,
  'encryptedBytesUsed' : bigint,
  'subscriptionStatus' : [] | [SubscriptionStatus],
  'backendId' : [] | [Principal],
  'storageBackendType' : StorageBackend,
}
export interface StoreArgs {
  'key' : Key,
  'content' : Uint8Array,
  'sha256' : [] | [Uint8Array],
  'content_type' : string,
  'is_aliased' : [] | [boolean],
  'content_encoding' : string,
}
export interface StoredStorageEvent {
  'id' : bigint,
  'visibleTo' : Array<Principal>,
  'event' : StorageEvent,
  'timestamp' : Time,
  'correlationId' : [] | [string],
}
export type StreamingCallback = ActorMethod<
  [StreamingToken],
  StreamingCallbackResponse
>;
export interface StreamingCallbackResponse {
  'token' : [] | [StreamingToken],
  'body' : Uint8Array,
}
export type StreamingStrategy = { 'Callback' : CallbackStreamingStrategy };
export type StreamingToken = Uint8Array;
export type SubscriptionStatus = { 'active' : { 'plan' : Plan } } |
  { 'expired' : null } |
  { 'licensed' : { 'includedBytes' : bigint, 'maxFileBytes' : bigint } } |
  { 'free' : null } |
  { 'unknownCanister' : null } |
  { 'invalidWasm' : null };
export type ThumbnailEncryptionPolicy = { 'FollowFile' : null } |
  { 'Inherit' : null };
export type ThumbnailEncryptionRef = {
    'Encrypted' : {
      'algorithm' : string,
      'wrappedKey' : Uint8Array,
      'blobIv' : Uint8Array,
      'scopeKeyId' : KeyId,
    }
  } |
  { 'Plaintext' : null };
export type ThumbnailEncryptionRequirement = {
    'Encrypted' : { 'scopeKeyId' : KeyId }
  } |
  { 'Plaintext' : null };
export type ThumbnailRef = {
    'OnChain' : {
      'key' : string,
      'sha256' : [] | [Uint8Array],
      'contentType' : string,
      'size' : bigint,
      'encryption' : ThumbnailEncryptionRef,
    }
  } |
  {
    'BlobStorage' : {
      'sha256' : [] | [Uint8Array],
      'contentType' : string,
      'size' : bigint,
      'encryption' : ThumbnailEncryptionRef,
      'blobId' : Uint8Array,
      'rootHash' : string,
    }
  };
export type ThumbnailStoragePolicy = { 'OnChain' : null } |
  { 'BlobStorage' : null } |
  { 'Inherit' : null };
export type Time = bigint;
export type TransportKey = Uint8Array;
export interface TreeNode {
  'name' : string,
  'children' : [] | [Array<TreeNode>],
}
export interface UnsetAssetContentArguments {
  'key' : Key,
  'content_encoding' : string,
}
export type UpdateArguments = {
    'File' : {
      'metadata' : {
        'sha256' : [] | [Uint8Array],
        'contentType' : string,
        'chunkIds' : Array<ChunkId>,
      },
      'path' : string,
    }
  } |
  {
    'Directory' : {
      'metadata' : { 'color' : [] | [DirectoryColor] },
      'path' : string,
    }
  };
export interface UpdateDirectoryPolicyArguments {
  'entry' : Entry,
  'thumbnailEncryptionPolicy' : [] | [ThumbnailEncryptionPolicy],
  'thumbnailStoragePolicy' : [] | [ThumbnailStoragePolicy],
  'encryptionPolicy' : [] | [DirectoryEncryptionPolicy],
}
export interface UploadCycleCostEstimate {
  'vetKeyDerivation' : bigint,
  'remainingWrite' : bigint,
  'operation' : bigint,
  'commit' : bigint,
  'remainingHashInstructions' : bigint,
  'commitMetadata' : bigint,
}
export interface UploadMemoryProjection {
  'projectedAllocatedBytes' : bigint,
  'projectedCapacityDeltaBytes' : bigint,
  'projectedCapacityBytes' : bigint,
}
export interface UploadSessionStatus {
  'declaredUploadBytes' : bigint,
  'expiresAt' : Time,
  'owner' : Principal,
  'uploadedBytes' : bigint,
  'chunkIds' : Array<ChunkId>,
  'batchId' : BatchId,
}
export type VetKey = Uint8Array;
export type VetKeyVerificationKey = Uint8Array;
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE extends EncryptedStorageCanister {}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];