/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlFactory = ({ IDL }) => {
  const TreeNode = IDL.Rec();
  const StorageBackend = IDL.Variant({
    'OnChain' : IDL.Null,
    'BlobStorage' : IDL.Null,
  });
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result_1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const BatchId = IDL.Nat;
  const StorageErrorCode = IDL.Variant({
    'Internal' : IDL.Null,
    'FundingPending' : IDL.Null,
    'NotFound' : IDL.Null,
    'PermissionDenied' : IDL.Null,
    'InsufficientCycles' : IDL.Null,
    'Validation' : IDL.Null,
    'QuotaExceeded' : IDL.Null,
    'Conflict' : IDL.Null,
  });
  const StorageError = IDL.Record({
    'code' : StorageErrorCode,
    'message' : IDL.Text,
  });
  const StorageResult_1 = IDL.Variant({
    'ok' : IDL.Null,
    'err' : StorageError,
  });
  const Permission__1 = IDL.Variant({
    'Read' : IDL.Null,
    'ReadWrite' : IDL.Null,
    'ReadWriteManage' : IDL.Null,
  });
  const Time = IDL.Int;
  const OwnerEquivalentPrincipal = IDL.Record({
    'principal' : IDL.Principal,
    'rootPermissionBeforeRecovery' : IDL.Opt(Permission__1),
    'kind' : IDL.Variant({
      'recoveryOwner' : IDL.Null,
      'accountOwner' : IDL.Null,
    }),
    'controllerRecoveryEnabled' : IDL.Bool,
    'addedAt' : Time,
    'addedBy' : IDL.Principal,
    'revokedAt' : IDL.Opt(Time),
  });
  const AddRecoveryOwnerOptions = IDL.Record({
    'controllerRecovery' : IDL.Bool,
  });
  const AppendUploadChunkArguments = IDL.Record({
    'content' : IDL.Vec(IDL.Nat8),
    'chunkIndex' : IDL.Opt(IDL.Nat),
    'batchId' : BatchId,
  });
  const AppendUploadChunkResponse = IDL.Record({ 'chunkId' : IDL.Nat });
  const StorageResult_6 = IDL.Variant({
    'ok' : AppendUploadChunkResponse,
    'err' : StorageError,
  });
  const CreateMode = IDL.Variant({
    'GetOrCreate' : IDL.Null,
    'CreateNew' : IDL.Null,
  });
  const Entry = IDL.Tuple(
    IDL.Variant({ 'File' : IDL.Null, 'Directory' : IDL.Null }),
    IDL.Text,
  );
  const BeginUploadSessionArguments = IDL.Record({
    'declaredUploadBytes' : IDL.Opt(IDL.Nat),
    'createMode' : CreateMode,
    'totalSize' : IDL.Nat,
    'expectedChunkCount' : IDL.Opt(IDL.Nat),
    'entry' : Entry,
  });
  const Owner = IDL.Principal;
  const KeyName = IDL.Vec(IDL.Nat8);
  const KeyId = IDL.Tuple(Owner, KeyName);
  const ThumbnailEncryptionRef = IDL.Record({
    'algorithm' : IDL.Text,
    'wrappedKey' : IDL.Vec(IDL.Nat8),
    'blobIv' : IDL.Vec(IDL.Nat8),
    'scopeKeyId' : KeyId,
  });
  const ThumbnailRef = IDL.Variant({
    'OnChain' : IDL.Record({
      'key' : IDL.Text,
      'sha256' : IDL.Opt(IDL.Vec(IDL.Nat8)),
      'contentType' : IDL.Text,
      'size' : IDL.Nat,
      'encryption' : ThumbnailEncryptionRef,
    }),
    'BlobStorage' : IDL.Record({
      'sha256' : IDL.Opt(IDL.Vec(IDL.Nat8)),
      'contentType' : IDL.Text,
      'size' : IDL.Nat,
      'encryption' : ThumbnailEncryptionRef,
      'blobId' : IDL.Vec(IDL.Nat8),
      'rootHash' : IDL.Text,
    }),
  });
  const FileMetadata = IDL.Record({
    'storageBackend' : StorageBackend,
    'sha256' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'thumbnailRef' : IDL.Opt(ThumbnailRef),
    'contentType' : IDL.Text,
    'size' : IDL.Nat,
    'currentVersion' : IDL.Nat,
    'chunkCount' : IDL.Nat,
    'versionCount' : IDL.Nat,
  });
  const DirectoryColor = IDL.Variant({
    'blue' : IDL.Null,
    'gray' : IDL.Null,
    'orange' : IDL.Null,
    'pink' : IDL.Null,
    'purple' : IDL.Null,
    'green' : IDL.Null,
    'yellow' : IDL.Null,
  });
  const ThumbnailStoragePolicy = IDL.Variant({
    'OnChain' : IDL.Null,
    'BlobStorage' : IDL.Null,
    'Inherit' : IDL.Null,
  });
  const DirectoryMetadata = IDL.Record({
    'color' : IDL.Opt(DirectoryColor),
    'defaultThumbnailStorageBackend' : StorageBackend,
    'thumbnailStoragePolicy' : ThumbnailStoragePolicy,
  });
  const SharingInfo = IDL.Record({ 'sharedWith' : IDL.Nat });
  const NodeDetails = IDL.Record({
    'id' : IDL.Nat64,
    'modifiedAt' : IDL.Opt(Time),
    'metadata' : IDL.Variant({
      'File' : FileMetadata,
      'Directory' : DirectoryMetadata,
    }),
    'name' : IDL.Text,
    'createdAt' : Time,
    'callerPermission' : IDL.Opt(Permission__1),
    'sharing' : IDL.Opt(SharingInfo),
    'parentId' : IDL.Opt(IDL.Nat64),
    'keyId' : KeyId,
  });
  const BeginUploadSessionResponse = IDL.Record({
    'node' : NodeDetails,
    'batchId' : BatchId,
  });
  const StorageResult_5 = IDL.Variant({
    'ok' : BeginUploadSessionResponse,
    'err' : StorageError,
  });
  const CancelAccessRequestArguments = IDL.Record({ 'requestId' : IDL.Nat });
  const AccessRequestStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const EmailCommitment = IDL.Vec(IDL.Nat8);
  const AccessRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : AccessRequestStatus,
    'requester' : IDL.Principal,
    'createdAt' : Time,
    'emailCommitment' : IDL.Opt(EmailCommitment),
    'message' : IDL.Opt(IDL.Text),
    'decidedAt' : IDL.Opt(Time),
    'decidedBy' : IDL.Opt(IDL.Principal),
  });
  const CancelDurableAccessPolicyArguments = IDL.Record({
    'policyId' : IDL.Nat,
  });
  const DurablePolicyStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'armed' : IDL.Null,
    'released' : IDL.Null,
    'matured' : IDL.Null,
    'grace' : IDL.Null,
  });
  const KeyId__2 = IDL.Tuple(IDL.Principal, IDL.Vec(IDL.Nat8));
  const AccessScope = IDL.Variant({
    'root' : IDL.Null,
    'entry' : Entry,
    'keyId' : KeyId__2,
  });
  const DurablePolicyGrantTemplate = IDL.Record({
    'permission' : Permission__1,
    'scope' : AccessScope,
  });
  const DurablePolicyTrigger = IDL.Variant({
    'manualRelease' : IDL.Null,
    'date' : IDL.Record({ 'releaseAt' : Time }),
    'inactivity' : IDL.Record({
      'inactiveForNs' : IDL.Nat,
      'gracePeriodNs' : IDL.Opt(IDL.Nat),
    }),
  });
  const AccessRef = IDL.Variant({
    'principal' : IDL.Principal,
    'emailCommitment' : EmailCommitment,
    'email' : IDL.Record({
      'emailCommitment' : EmailCommitment,
      'email' : IDL.Text,
    }),
  });
  const DurableAccessPolicy = IDL.Record({
    'id' : IDL.Nat,
    'maturedAt' : IDL.Opt(Time),
    'status' : DurablePolicyStatus,
    'grants' : IDL.Vec(DurablePolicyGrantTemplate),
    'trigger' : DurablePolicyTrigger,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'cancelledAt' : IDL.Opt(Time),
    'proVerifiedAt' : Time,
    'recipients' : IDL.Vec(AccessRef),
    'releasedAt' : IDL.Opt(Time),
    'graceStartedAt' : IDL.Opt(Time),
    'principalGrantIds' : IDL.Vec(IDL.Nat),
    'pendingGrantIds' : IDL.Vec(IDL.Nat),
  });
  const CancelPendingAccessGrantArguments = IDL.Record({ 'grantId' : IDL.Nat });
  const EmailClaimOrigin = IDL.Variant({
    'storage' : IDL.Null,
    'rabbithole' : IDL.Null,
  });
  const EmailClaim = IDL.Record({
    'principalGrantId' : IDL.Nat,
    'principal' : IDL.Principal,
    'origin' : EmailClaimOrigin,
    'claimedAt' : Time,
  });
  const EmailClaimState = IDL.Record({
    'storage' : IDL.Opt(EmailClaim),
    'rabbithole' : IDL.Opt(EmailClaim),
  });
  const AccessSource = IDL.Variant({
    'durablePolicy' : IDL.Nat,
    'accessRequest' : IDL.Nat,
    'directGrant' : IDL.Null,
    'ordinaryInvite' : IDL.Nat,
    'recoverySetup' : IDL.Null,
  });
  const AccessClass = IDL.Variant({
    'ordinary' : IDL.Null,
    'ownerEquivalent' : IDL.Null,
    'durable' : IDL.Null,
  });
  const PendingAccessGrant = IDL.Record({
    'id' : IDL.Nat,
    'ref' : AccessRef,
    'permission' : Permission__1,
    'expiresAt' : IDL.Opt(Time),
    'emailClaimState' : EmailClaimState,
    'source' : AccessSource,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'claimedAt' : IDL.Opt(Time),
    'claimedBy' : IDL.Opt(IDL.Principal),
    'scope' : AccessScope,
    'cancelledAt' : IDL.Opt(Time),
    'accessClass' : AccessClass,
  });
  const CertifiedTree = IDL.Record({
    'certificate' : IDL.Vec(IDL.Nat8),
    'tree' : IDL.Vec(IDL.Nat8),
  });
  const ClaimPendingAccessByBackendAttestationArguments = IDL.Record({
    'principal' : IDL.Principal,
    'emailCommitments' : IDL.Vec(EmailCommitment),
  });
  const PrincipalAccessGrant = IDL.Record({
    'id' : IDL.Nat,
    'permission' : Permission__1,
    'principal' : IDL.Principal,
    'source' : AccessSource,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'scope' : AccessScope,
    'accessClass' : AccessClass,
    'revokedAt' : IDL.Opt(Time),
  });
  const ClaimPendingAccessGrantArguments = IDL.Record({ 'grantId' : IDL.Nat });
  const IdentityAttributesSyncError = IDL.Variant({
    'expired' : IDL.Null,
    'malformedPayload' : IDL.Null,
    'verifiedEmailRequired' : IDL.Null,
    'attributesNotFound' : IDL.Null,
  });
  const IdentityAttributesSyncResult = IDL.Variant({
    'ok' : IDL.Null,
    'err' : IdentityAttributesSyncError,
  });
  const ClearArguments = IDL.Record({});
  const CommitCaffeineUploadArgs = IDL.Record({
    'sha256' : IDL.Vec(IDL.Nat8),
    'contentType' : IDL.Text,
    'size' : IDL.Nat,
    'entry' : Entry,
    'rootHash' : IDL.Text,
  });
  const CommitThumbnailUploadArguments = IDL.Record({
    'sha256' : IDL.Vec(IDL.Nat8),
    'contentType' : IDL.Text,
    'size' : IDL.Nat,
    'encryption' : ThumbnailEncryptionRef,
    'entry' : Entry,
    'rootHash' : IDL.Text,
  });
  const Key = IDL.Text;
  const Header = IDL.Tuple(IDL.Text, IDL.Text);
  const SetAssetPropertiesArguments = IDL.Record({
    'key' : Key,
    'headers' : IDL.Opt(IDL.Opt(IDL.Vec(Header))),
    'is_aliased' : IDL.Opt(IDL.Opt(IDL.Bool)),
    'allow_raw_access' : IDL.Opt(IDL.Opt(IDL.Bool)),
    'max_age' : IDL.Opt(IDL.Opt(IDL.Nat64)),
  });
  const CreateAssetArguments = IDL.Record({
    'key' : Key,
    'content_type' : IDL.Text,
    'headers' : IDL.Opt(IDL.Vec(Header)),
    'allow_raw_access' : IDL.Opt(IDL.Bool),
    'max_age' : IDL.Opt(IDL.Nat64),
    'enable_aliasing' : IDL.Opt(IDL.Bool),
  });
  const UnsetAssetContentArguments = IDL.Record({
    'key' : Key,
    'content_encoding' : IDL.Text,
  });
  const DeleteAssetArguments = IDL.Record({ 'key' : Key });
  const ChunkId = IDL.Nat;
  const SetAssetContentArguments = IDL.Record({
    'key' : Key,
    'sha256' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'chunk_ids' : IDL.Vec(ChunkId),
    'content_encoding' : IDL.Text,
  });
  const BatchOperationKind = IDL.Variant({
    'SetAssetProperties' : SetAssetPropertiesArguments,
    'CreateAsset' : CreateAssetArguments,
    'UnsetAssetContent' : UnsetAssetContentArguments,
    'DeleteAsset' : DeleteAssetArguments,
    'SetAssetContent' : SetAssetContentArguments,
    'Clear' : ClearArguments,
  });
  const CommitBatchArguments = IDL.Record({
    'batch_id' : BatchId,
    'operations' : IDL.Vec(BatchOperationKind),
  });
  const CommitProposedBatchArguments = IDL.Record({
    'batch_id' : BatchId,
    'evidence' : IDL.Vec(IDL.Nat8),
  });
  const ComputeEvidenceArguments = IDL.Record({
    'batch_id' : BatchId,
    'max_iterations' : IDL.Opt(IDL.Nat16),
  });
  const ConfigureArguments = IDL.Record({
    'max_batches' : IDL.Opt(IDL.Opt(IDL.Nat64)),
    'max_bytes' : IDL.Opt(IDL.Opt(IDL.Nat64)),
    'max_chunks' : IDL.Opt(IDL.Opt(IDL.Nat64)),
  });
  const CreateArguments = IDL.Record({
    'createMode' : CreateMode,
    'entry' : Entry,
  });
  const StorageResult = IDL.Variant({
    'ok' : NodeDetails,
    'err' : StorageError,
  });
  const CreateAccessBatchItem = IDL.Record({
    'ref' : AccessRef,
    'permission' : Permission__1,
    'expiresAt' : IDL.Opt(Time),
    'source' : AccessSource,
    'scope' : AccessScope,
    'accessClass' : AccessClass,
  });
  const CreateAccessBatchArguments = IDL.Record({
    'items' : IDL.Vec(CreateAccessBatchItem),
  });
  const CreateAccessBatchResult = IDL.Record({
    'pendingGrants' : IDL.Vec(PendingAccessGrant),
    'revokedPrincipalGrants' : IDL.Vec(PrincipalAccessGrant),
    'principalGrants' : IDL.Vec(PrincipalAccessGrant),
    'cancelledPendingGrants' : IDL.Vec(PendingAccessGrant),
  });
  const CreateDurableAccessGrantArguments = IDL.Record({
    'permission' : Permission__1,
    'principal' : IDL.Principal,
    'source' : AccessSource,
    'scope' : AccessScope,
  });
  const CreateDurableAccessPolicyArguments = IDL.Record({
    'grants' : IDL.Vec(DurablePolicyGrantTemplate),
    'trigger' : DurablePolicyTrigger,
    'recipients' : IDL.Vec(AccessRef),
  });
  const CreatePendingAccessGrantArguments = IDL.Record({
    'ref' : AccessRef,
    'permission' : Permission__1,
    'expiresAt' : IDL.Opt(Time),
    'source' : AccessSource,
    'scope' : AccessScope,
    'accessClass' : AccessClass,
  });
  const CreateBatchResponse = IDL.Record({ 'batch_id' : BatchId });
  const CreateChunkArguments = IDL.Record({
    'content' : IDL.Vec(IDL.Nat8),
    'batch_id' : BatchId,
  });
  const CreateChunkResponse = IDL.Record({ 'chunk_id' : IDL.Nat });
  const CreateChunksArguments = IDL.Record({
    'content' : IDL.Vec(IDL.Vec(IDL.Nat8)),
    'batch_id' : BatchId,
  });
  const CreateChunksResponse = IDL.Record({ 'chunk_ids' : IDL.Vec(ChunkId) });
  const DeleteArguments = IDL.Record({
    'recursive' : IDL.Bool,
    'entry' : Entry,
  });
  const DeleteBatchArguments = IDL.Record({ 'batch_id' : BatchId });
  const FinishUploadSessionArguments = IDL.Record({
    'sha256' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'contentType' : IDL.Text,
    'batchId' : BatchId,
  });
  TreeNode.fill(
    IDL.Record({ 'name' : IDL.Text, 'children' : IDL.Opt(IDL.Vec(TreeNode)) })
  );
  const GetArgs = IDL.Record({
    'key' : Key,
    'accept_encodings' : IDL.Vec(IDL.Text),
  });
  const EncodedAsset = IDL.Record({
    'content' : IDL.Vec(IDL.Nat8),
    'sha256' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'content_type' : IDL.Text,
    'content_encoding' : IDL.Text,
    'total_length' : IDL.Nat,
  });
  const UploadMemoryProjection = IDL.Record({
    'projectedAllocatedBytes' : IDL.Nat,
    'projectedCapacityDeltaBytes' : IDL.Nat,
    'projectedCapacityBytes' : IDL.Nat,
  });
  const CycleSafetyEnvelope = IDL.Record({
    'minimumSafeBalance' : IDL.Nat,
    'targetBalance' : IDL.Nat,
    'operationFloorBalance' : IDL.Nat,
    'postWriteFreezingReserve' : IDL.Nat,
    'currentFreezingReserve' : IDL.Nat,
  });
  const MemoryInfo = IDL.Record({
    'allocated' : IDL.Nat,
    'size' : IDL.Nat,
    'deallocated' : IDL.Nat,
    'pages' : IDL.Nat,
    'capacity' : IDL.Nat,
  });
  const RuntimeMemoryMetrics = IDL.Record({
    'runtimeStableMemoryBytes' : IDL.Opt(IDL.Nat),
    'runtimeMemoryBytes' : IDL.Opt(IDL.Nat),
    'memoryInfo' : MemoryInfo,
  });
  const UploadCycleCostEstimate = IDL.Record({
    'vetKeyDerivation' : IDL.Nat,
    'remainingWrite' : IDL.Nat,
    'operation' : IDL.Nat,
    'commit' : IDL.Nat,
    'remainingHashInstructions' : IDL.Nat,
    'commitMetadata' : IDL.Nat,
  });
  const LastUploadCommitMetrics = IDL.Record({
    'hashRoundCount' : IDL.Nat,
    'chunkCount' : IDL.Nat,
    'bytes' : IDL.Nat,
    'hashInstructionCycles' : IDL.Nat,
  });
  const ActiveUploadProjection = IDL.Record({
    'uploadedChunkCount' : IDL.Nat,
    'reservationBytes' : IDL.Nat,
    'uploadedBytes' : IDL.Nat,
    'remainingBytes' : IDL.Nat,
    'sessionCount' : IDL.Nat,
    'remainingChunkCount' : IDL.Nat,
  });
  const CanisterCyclesFundingState = IDL.Record({
    'requestedTargetBalance' : IDL.Nat,
    'requestedBytes' : IDL.Nat,
    'lastRequestedAt' : IDL.Opt(Time),
    'lastCompletedAt' : IDL.Opt(Time),
    'lastError' : IDL.Opt(IDL.Text),
    'inFlight' : IDL.Bool,
  });
  const CanisterCyclesCardMetrics = IDL.Record({
    'memory' : UploadMemoryProjection,
    'safety' : CycleSafetyEnvelope,
    'runtimeMemory' : RuntimeMemoryMetrics,
    'balance' : IDL.Nat,
    'cost' : UploadCycleCostEstimate,
    'freezingThresholdSeconds' : IDL.Nat,
    'lastCommit' : IDL.Opt(LastUploadCommitMetrics),
    'activity' : ActiveUploadProjection,
    'funding' : CanisterCyclesFundingState,
  });
  const StorageResult_3 = IDL.Variant({
    'ok' : CanisterCyclesCardMetrics,
    'err' : StorageError,
  });
  const TransportKey = IDL.Vec(IDL.Nat8);
  const VetKey = IDL.Vec(IDL.Nat8);
  const OwnerActivityOrigin = IDL.Variant({
    'storage' : IDL.Null,
    'rabbithole' : IDL.Null,
    'backend' : IDL.Null,
  });
  const OwnerActivityRole = IDL.Variant({
    'recoveryOwner' : IDL.Null,
    'accountOwner' : IDL.Null,
  });
  const OwnerActivityRecord = IDL.Record({
    'principal' : IDL.Principal,
    'lastSeenAt' : Time,
    'origin' : OwnerActivityOrigin,
    'role' : OwnerActivityRole,
  });
  const OwnerActivityState = IDL.Record({
    'records' : IDL.Vec(OwnerActivityRecord),
    'lastOwnerActivityAt' : Time,
    'lastOwnerActivityBy' : IDL.Principal,
  });
  const RecoveryStatus = IDL.Record({
    'recoveryOwner' : IDL.Opt(OwnerEquivalentPrincipal),
    'recoveryController' : IDL.Opt(IDL.Principal),
  });
  const Plan = IDL.Variant({
    'Pro' : IDL.Null,
    'Free' : IDL.Null,
    'License' : IDL.Null,
  });
  const SubscriptionStatus = IDL.Variant({
    'active' : IDL.Record({ 'plan' : Plan }),
    'expired' : IDL.Null,
    'licensed' : IDL.Record({
      'includedBytes' : IDL.Nat,
      'maxFileBytes' : IDL.Nat,
    }),
    'free' : IDL.Null,
    'unknownCanister' : IDL.Null,
    'invalidWasm' : IDL.Null,
  });
  const StorageStatus = IDL.Record({
    'cycleBalance' : IDL.Nat,
    'subscriptionStatus' : IDL.Opt(SubscriptionStatus),
    'storedBytesUsed' : IDL.Nat,
    'backendId' : IDL.Opt(IDL.Principal),
    'storageBackendType' : StorageBackend,
  });
  const StorageCardMetrics = IDL.Record({
    'runtimeStableMemoryBytes' : IDL.Opt(IDL.Nat),
    'runtimeMemoryBytes' : IDL.Opt(IDL.Nat),
    'subscriptionStatus' : IDL.Opt(SubscriptionStatus),
    'storedBytesUsed' : IDL.Nat,
    'backendId' : IDL.Opt(IDL.Principal),
    'storageBackendType' : StorageBackend,
    'memoryInfo' : MemoryInfo,
  });
  const StorageResult_2 = IDL.Variant({
    'ok' : StorageCardMetrics,
    'err' : StorageError,
  });
  const GetChunkArguments = IDL.Record({
    'chunkIndex' : IDL.Nat,
    'entry' : Entry,
    'version' : IDL.Opt(IDL.Nat),
  });
  const ChunkContent = IDL.Record({ 'content' : IDL.Vec(IDL.Nat8) });
  const UploadSessionStatus = IDL.Record({
    'declaredUploadBytes' : IDL.Nat,
    'expiresAt' : Time,
    'owner' : IDL.Principal,
    'uploadedBytes' : IDL.Nat,
    'chunkIds' : IDL.Vec(ChunkId),
    'batchId' : BatchId,
  });
  const StorageResult_4 = IDL.Variant({
    'ok' : UploadSessionStatus,
    'err' : StorageError,
  });
  const VetKeyVerificationKey = IDL.Vec(IDL.Nat8);
  const GetChunkArgs = IDL.Record({
    'key' : Key,
    'sha256' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'index' : IDL.Nat,
    'content_encoding' : IDL.Text,
  });
  const ConfigurationResponse = IDL.Record({
    'max_batches' : IDL.Opt(IDL.Nat64),
    'max_bytes' : IDL.Opt(IDL.Nat64),
    'max_chunks' : IDL.Opt(IDL.Nat64),
  });
  const Permission = IDL.Variant({
    'Prepare' : IDL.Null,
    'Manage' : IDL.Null,
    'Commit' : IDL.Null,
  });
  const GrantPermission = IDL.Record({
    'permission' : Permission,
    'to_principal' : IDL.Principal,
  });
  const HasPermissionArguments = IDL.Record({
    'permission' : Permission__1,
    'user' : IDL.Principal,
    'entry' : IDL.Opt(Entry),
  });
  const RawQueryHttpRequest = IDL.Record({
    'url' : IDL.Text,
    'method' : IDL.Text,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(Header),
    'certificate_version' : IDL.Opt(IDL.Nat16),
  });
  const StreamingToken = IDL.Vec(IDL.Nat8);
  const StreamingCallbackResponse = IDL.Record({
    'token' : IDL.Opt(StreamingToken),
    'body' : IDL.Vec(IDL.Nat8),
  });
  const StreamingCallback = IDL.Func(
      [StreamingToken],
      [StreamingCallbackResponse],
      ['query'],
    );
  const CallbackStreamingStrategy = IDL.Record({
    'token' : StreamingToken,
    'callback' : StreamingCallback,
  });
  const StreamingStrategy = IDL.Variant({
    'Callback' : CallbackStreamingStrategy,
  });
  const RawQueryHttpResponse = IDL.Record({
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(Header),
    'upgrade' : IDL.Opt(IDL.Bool),
    'streaming_strategy' : IDL.Opt(StreamingStrategy),
    'status_code' : IDL.Nat16,
  });
  const RawUpdateHttpRequest = IDL.Record({
    'url' : IDL.Text,
    'method' : IDL.Text,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(Header),
  });
  const RawUpdateHttpResponse = IDL.Record({
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(Header),
    'streaming_strategy' : IDL.Opt(StreamingStrategy),
    'status_code' : IDL.Nat16,
  });
  const AssetEncodingDetails = IDL.Record({
    'modified' : Time,
    'sha256' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'length' : IDL.Nat,
    'content_encoding' : IDL.Text,
  });
  const AssetDetails = IDL.Record({
    'key' : Key,
    'encodings' : IDL.Vec(AssetEncodingDetails),
    'content_type' : IDL.Text,
  });
  const AccessGrantListMode = IDL.Variant({
    'effective' : IDL.Null,
    'exact' : IDL.Null,
  });
  const ListAccessGrantsArguments = IDL.Record({
    'mode' : AccessGrantListMode,
    'scope' : IDL.Opt(AccessScope),
  });
  const ListedPendingAccessGrant = IDL.Record({
    'inheritedFrom' : IDL.Opt(AccessScope),
    'grant' : PendingAccessGrant,
  });
  const ListedPrincipalAccessGrant = IDL.Record({
    'inheritedFrom' : IDL.Opt(AccessScope),
    'grant' : PrincipalAccessGrant,
  });
  const AccessGrantList = IDL.Record({
    'pendingGrants' : IDL.Vec(ListedPendingAccessGrant),
    'principalGrants' : IDL.Vec(ListedPrincipalAccessGrant),
    'mode' : AccessGrantListMode,
    'scope' : AccessScope,
  });
  const StorageAccessEvent = IDL.Variant({
    'accessRequestResolved' : IDL.Record({
      'status' : AccessRequestStatus,
      'requestId' : IDL.Nat,
      'requester' : IDL.Principal,
    }),
    'durablePolicyCreated' : IDL.Record({
      'status' : DurablePolicyStatus,
      'trigger' : DurablePolicyTrigger,
      'policyId' : IDL.Nat,
    }),
    'accessRequestCreated' : IDL.Record({
      'requestId' : IDL.Nat,
      'requester' : IDL.Principal,
    }),
    'recoveryControllerRegistered' : IDL.Record({
      'principal' : IDL.Principal,
      'previous' : IDL.Opt(IDL.Principal),
    }),
    'pendingGrantCreated' : IDL.Record({
      'ref' : AccessRef,
      'source' : AccessSource,
      'grantId' : IDL.Nat,
      'accessClass' : AccessClass,
    }),
    'ownerActivityRecorded' : IDL.Record({
      'principal' : IDL.Principal,
      'origin' : OwnerActivityOrigin,
      'role' : OwnerActivityRole,
    }),
    'durablePolicyReleased' : IDL.Record({ 'policyId' : IDL.Nat }),
    'recoveryControllerCleared' : IDL.Record({ 'principal' : IDL.Principal }),
    'durablePolicyMatured' : IDL.Record({ 'policyId' : IDL.Nat }),
    'recoveryOwnerAdded' : IDL.Record({ 'principal' : IDL.Principal }),
    'pendingGrantClaimed' : IDL.Record({
      'principal' : IDL.Principal,
      'emailClaimState' : IDL.Opt(EmailClaimState),
      'source' : AccessSource,
      'grantId' : IDL.Nat,
      'claimOrigin' : IDL.Opt(EmailClaimOrigin),
      'accessClass' : AccessClass,
    }),
    'durablePolicyCancelled' : IDL.Record({ 'policyId' : IDL.Nat }),
    'accessRequestCancelled' : IDL.Record({
      'requestId' : IDL.Nat,
      'requester' : IDL.Principal,
    }),
    'principalGrantCreated' : IDL.Record({
      'principal' : IDL.Principal,
      'source' : AccessSource,
      'grantId' : IDL.Opt(IDL.Nat),
      'accessClass' : AccessClass,
    }),
    'pendingGrantCancelled' : IDL.Record({
      'ref' : AccessRef,
      'grantId' : IDL.Nat,
    }),
    'durablePolicyGraceStarted' : IDL.Record({ 'policyId' : IDL.Nat }),
    'principalGrantRevoked' : IDL.Record({
      'principal' : IDL.Principal,
      'accessClass' : IDL.Opt(AccessClass),
    }),
    'recoveryOwnerRemoved' : IDL.Record({ 'principal' : IDL.Principal }),
  });
  const StorageEvent = IDL.Variant({ 'access' : StorageAccessEvent });
  const StoredStorageEvent = IDL.Record({
    'id' : IDL.Nat,
    'visibleTo' : IDL.Vec(IDL.Principal),
    'event' : StorageEvent,
    'timestamp' : Time,
    'correlationId' : IDL.Opt(IDL.Text),
  });
  const ListResponse = IDL.Record({
    'entries' : IDL.Vec(NodeDetails),
    'directoryPermission' : IDL.Opt(Permission__1),
  });
  const ListVersionsArguments = IDL.Record({ 'entry' : Entry });
  const FileVersionDetails = IDL.Record({
    'storageBackend' : StorageBackend,
    'sha256' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'contentType' : IDL.Text,
    'createdAt' : Time,
    'size' : IDL.Nat,
    'index' : IDL.Nat,
  });
  const ListPermitted = IDL.Record({ 'permission' : Permission });
  const MoveArguments = IDL.Record({
    'entry' : Entry,
    'target' : IDL.Opt(Entry),
  });
  const PreflightCaffeineUploadArgs = IDL.Record({
    'size' : IDL.Nat,
    'entry' : Entry,
  });
  const PrepareThumbnailUploadArguments = IDL.Record({
    'contentType' : IDL.Text,
    'size' : IDL.Nat,
    'entry' : Entry,
  });
  const ThumbnailEncryptionRequirement = IDL.Record({ 'scopeKeyId' : KeyId });
  const PrepareThumbnailUploadResult = IDL.Record({
    'storageBackend' : StorageBackend,
    'contentType' : IDL.Text,
    'size' : IDL.Nat,
    'encryption' : ThumbnailEncryptionRequirement,
  });
  const DurablePolicyProcessResult = IDL.Record({
    'pendingGrants' : IDL.Vec(PendingAccessGrant),
    'principalGrants' : IDL.Vec(PrincipalAccessGrant),
    'policy' : DurableAccessPolicy,
  });
  const RecordOwnerActivityArguments = IDL.Record({
    'origin' : OwnerActivityOrigin,
  });
  const RegisterRecoveryControllerResult = IDL.Record({
    'principal' : IDL.Principal,
    'previous' : IDL.Opt(IDL.Principal),
  });
  const ReleaseDurableAccessPolicyArguments = IDL.Record({
    'policyId' : IDL.Nat,
  });
  const RenameArguments = IDL.Record({ 'entry' : Entry, 'newName' : IDL.Text });
  const CreateAccessRequestArguments = IDL.Record({
    'emailCommitment' : IDL.Opt(EmailCommitment),
    'message' : IDL.Opt(IDL.Text),
  });
  const AccessRequestDecision = IDL.Variant({
    'approved' : IDL.Record({
      'permission' : Permission__1,
      'scope' : AccessScope,
    }),
    'rejected' : IDL.Null,
  });
  const ResolveAccessRequestArguments = IDL.Record({
    'decision' : AccessRequestDecision,
    'requestId' : IDL.Nat,
  });
  const RestoreVersionArguments = IDL.Record({
    'entry' : Entry,
    'version' : IDL.Nat,
  });
  const RevokeAccessBatchItem = IDL.Record({
    'principal' : IDL.Principal,
    'scope' : AccessScope,
  });
  const RevokeAccessBatchArguments = IDL.Record({
    'items' : IDL.Vec(RevokeAccessBatchItem),
  });
  const RevokeAccessBatchResult = IDL.Record({
    'revoked' : IDL.Vec(RevokeAccessBatchItem),
  });
  const RevokePermission = IDL.Record({
    'permission' : Permission,
    'of_principal' : IDL.Principal,
  });
  const StoreArgs = IDL.Record({
    'key' : Key,
    'content' : IDL.Vec(IDL.Nat8),
    'sha256' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'content_type' : IDL.Text,
    'is_aliased' : IDL.Opt(IDL.Bool),
    'content_encoding' : IDL.Text,
  });
  const UpdateArguments = IDL.Variant({
    'File' : IDL.Record({
      'metadata' : IDL.Record({
        'sha256' : IDL.Opt(IDL.Vec(IDL.Nat8)),
        'contentType' : IDL.Text,
        'chunkIds' : IDL.Vec(ChunkId),
      }),
      'path' : IDL.Text,
    }),
    'Directory' : IDL.Record({
      'metadata' : IDL.Record({ 'color' : IDL.Opt(DirectoryColor) }),
      'path' : IDL.Text,
    }),
  });
  const UpdateDirectoryPolicyArguments = IDL.Record({
    'entry' : Entry,
    'thumbnailStoragePolicy' : IDL.Opt(ThumbnailStoragePolicy),
  });
  const Result = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const EncryptedStorageCanister = IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result_1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'abortUploadSession' : IDL.Func(
        [IDL.Record({ 'batchId' : BatchId })],
        [StorageResult_1],
        [],
      ),
    'activateRecoveryOwnership' : IDL.Func(
        [IDL.Principal],
        [OwnerEquivalentPrincipal],
        [],
      ),
    'addRecoveryOwner' : IDL.Func(
        [IDL.Principal, AddRecoveryOwnerOptions],
        [OwnerEquivalentPrincipal],
        [],
      ),
    'api_version' : IDL.Func([], [IDL.Nat16], ['query']),
    'appendUploadChunk' : IDL.Func(
        [AppendUploadChunkArguments],
        [StorageResult_6],
        [],
      ),
    'beginUploadSession' : IDL.Func(
        [BeginUploadSessionArguments],
        [StorageResult_5],
        [],
      ),
    'cancelAccessRequest' : IDL.Func(
        [CancelAccessRequestArguments],
        [AccessRequest],
        [],
      ),
    'cancelDurableAccessPolicy' : IDL.Func(
        [CancelDurableAccessPolicyArguments],
        [DurableAccessPolicy],
        [],
      ),
    'cancelPendingAccessGrant' : IDL.Func(
        [CancelPendingAccessGrantArguments],
        [PendingAccessGrant],
        [],
      ),
    'certified_tree' : IDL.Func([IDL.Record({})], [CertifiedTree], []),
    'claimPendingAccessByBackendAttestation' : IDL.Func(
        [ClaimPendingAccessByBackendAttestationArguments],
        [IDL.Vec(PrincipalAccessGrant)],
        [],
      ),
    'claimPendingAccessGrant' : IDL.Func(
        [ClaimPendingAccessGrantArguments],
        [PrincipalAccessGrant],
        [],
      ),
    'claimVerifiedEmailAccess' : IDL.Func(
        [],
        [IdentityAttributesSyncResult],
        [],
      ),
    'clear' : IDL.Func([ClearArguments], [], []),
    'clearRecoveryController' : IDL.Func([], [IDL.Principal], []),
    'clearStorage' : IDL.Func([], [], []),
    'commitCaffeineUpload' : IDL.Func(
        [CommitCaffeineUploadArgs],
        [StorageResult_1],
        [],
      ),
    'commitThumbnailUpload' : IDL.Func(
        [CommitThumbnailUploadArguments],
        [NodeDetails],
        [],
      ),
    'commit_batch' : IDL.Func([CommitBatchArguments], [], []),
    'commit_proposed_batch' : IDL.Func([CommitProposedBatchArguments], [], []),
    'compute_evidence' : IDL.Func(
        [ComputeEvidenceArguments],
        [IDL.Opt(IDL.Vec(IDL.Nat8))],
        [],
      ),
    'configure' : IDL.Func([ConfigureArguments], [], []),
    'create' : IDL.Func([CreateArguments], [StorageResult], []),
    'createAccessBatch' : IDL.Func(
        [CreateAccessBatchArguments],
        [CreateAccessBatchResult],
        [],
      ),
    'createDurableAccessGrant' : IDL.Func(
        [CreateDurableAccessGrantArguments],
        [PrincipalAccessGrant],
        [],
      ),
    'createDurableAccessPolicy' : IDL.Func(
        [CreateDurableAccessPolicyArguments],
        [DurableAccessPolicy],
        [],
      ),
    'createPendingAccessGrant' : IDL.Func(
        [CreatePendingAccessGrantArguments],
        [PendingAccessGrant],
        [],
      ),
    'create_asset' : IDL.Func([CreateAssetArguments], [], []),
    'create_batch' : IDL.Func([IDL.Record({})], [CreateBatchResponse], []),
    'create_chunk' : IDL.Func(
        [CreateChunkArguments],
        [CreateChunkResponse],
        [],
      ),
    'create_chunks' : IDL.Func(
        [CreateChunksArguments],
        [CreateChunksResponse],
        [],
      ),
    'delete' : IDL.Func([DeleteArguments], [], []),
    'delete_asset' : IDL.Func([DeleteAssetArguments], [], []),
    'delete_batch' : IDL.Func([DeleteBatchArguments], [], []),
    'finishUploadSession' : IDL.Func(
        [FinishUploadSessionArguments],
        [StorageResult_1],
        [],
      ),
    'fsTree' : IDL.Func([], [IDL.Vec(TreeNode)], ['query']),
    'get' : IDL.Func([GetArgs], [EncodedAsset], ['query']),
    'getCanisterCyclesCardMetrics' : IDL.Func([], [StorageResult_3], ['query']),
    'getCycleBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getEncryptedVetkey' : IDL.Func([KeyId, TransportKey], [VetKey], []),
    'getMyAccessRequest' : IDL.Func([], [IDL.Opt(AccessRequest)], ['query']),
    'getOwnerActivityState' : IDL.Func([], [OwnerActivityState], ['query']),
    'getRecoveryStatus' : IDL.Func([], [RecoveryStatus], ['query']),
    'getStatus' : IDL.Func([], [StorageStatus], ['query']),
    'getStorageBackendType' : IDL.Func([], [StorageBackend], ['query']),
    'getStorageCardMetrics' : IDL.Func([], [StorageResult_2], ['query']),
    'getStorageChunk' : IDL.Func(
        [GetChunkArguments],
        [ChunkContent],
        ['query'],
      ),
    'getStorageEventsUnreadCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUploadSession' : IDL.Func(
        [IDL.Record({ 'batchId' : BatchId })],
        [StorageResult_4],
        ['query'],
      ),
    'getVetkeyVerificationKey' : IDL.Func([], [VetKeyVerificationKey], []),
    'get_chunk' : IDL.Func([GetChunkArgs], [ChunkContent], ['query']),
    'get_configuration' : IDL.Func([], [ConfigurationResponse], []),
    'grant_permission' : IDL.Func([GrantPermission], [], []),
    'hasStoragePermission' : IDL.Func(
        [HasPermissionArguments],
        [IDL.Bool],
        ['query'],
      ),
    'http_request' : IDL.Func(
        [RawQueryHttpRequest],
        [RawQueryHttpResponse],
        ['query'],
      ),
    'http_request_streaming_callback' : IDL.Func(
        [StreamingToken],
        [StreamingCallbackResponse],
        ['query'],
      ),
    'http_request_update' : IDL.Func(
        [RawUpdateHttpRequest],
        [RawUpdateHttpResponse],
        [],
      ),
    'invalidateSubscriptionCache' : IDL.Func([], [], []),
    'list' : IDL.Func([IDL.Record({})], [IDL.Vec(AssetDetails)], ['query']),
    'listAccessGrants' : IDL.Func(
        [ListAccessGrantsArguments],
        [AccessGrantList],
        ['query'],
      ),
    'listAccessRequests' : IDL.Func([], [IDL.Vec(AccessRequest)], ['query']),
    'listDurableAccessPolicies' : IDL.Func(
        [],
        [IDL.Vec(DurableAccessPolicy)],
        ['query'],
      ),
    'listLatestStorageEvents' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(StoredStorageEvent)],
        ['query'],
      ),
    'listOwnerEquivalentPrincipals' : IDL.Func(
        [],
        [IDL.Vec(OwnerEquivalentPrincipal)],
        ['query'],
      ),
    'listPendingAccessGrants' : IDL.Func(
        [],
        [IDL.Vec(PendingAccessGrant)],
        ['query'],
      ),
    'listStorage' : IDL.Func([IDL.Opt(Entry)], [ListResponse], ['query']),
    'listStorageEvents' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Nat],
        [IDL.Vec(StoredStorageEvent)],
        ['query'],
      ),
    'listStorageVersions' : IDL.Func(
        [ListVersionsArguments],
        [IDL.Vec(FileVersionDetails)],
        ['query'],
      ),
    'list_permitted' : IDL.Func([ListPermitted], [IDL.Vec(IDL.Principal)], []),
    'markAllVisibleStorageEventsRead' : IDL.Func([], [], []),
    'markStorageEventsRead' : IDL.Func([IDL.Nat], [], []),
    'move' : IDL.Func([MoveArguments], [], []),
    'preflightCaffeineUpload' : IDL.Func(
        [PreflightCaffeineUploadArgs],
        [StorageResult_1],
        [],
      ),
    'prepareThumbnailUpload' : IDL.Func(
        [PrepareThumbnailUploadArguments],
        [PrepareThumbnailUploadResult],
        [],
      ),
    'processDurableAccessPolicies' : IDL.Func(
        [],
        [IDL.Vec(DurablePolicyProcessResult)],
        [],
      ),
    'propose_commit_batch' : IDL.Func([CommitBatchArguments], [], []),
    'recordOwnerActivity' : IDL.Func(
        [RecordOwnerActivityArguments],
        [OwnerActivityRecord],
        [],
      ),
    'refreshCanisterCyclesCardMetrics' : IDL.Func([], [StorageResult_3], []),
    'refreshStorageCardMetrics' : IDL.Func([], [StorageResult_2], []),
    'refreshSubscription' : IDL.Func([], [], []),
    'registerRecoveryController' : IDL.Func(
        [IDL.Principal],
        [RegisterRecoveryControllerResult],
        [],
      ),
    'releaseDurableAccessPolicy' : IDL.Func(
        [ReleaseDurableAccessPolicyArguments],
        [DurablePolicyProcessResult],
        [],
      ),
    'removeRecoveryOwner' : IDL.Func([IDL.Principal], [], []),
    'rename' : IDL.Func([RenameArguments], [], []),
    'requestAccess' : IDL.Func(
        [CreateAccessRequestArguments],
        [AccessRequest],
        [],
      ),
    'resolveAccessRequest' : IDL.Func(
        [ResolveAccessRequestArguments],
        [AccessRequest],
        [],
      ),
    'restoreStorageVersion' : IDL.Func([RestoreVersionArguments], [], []),
    'revokeAccessBatch' : IDL.Func(
        [RevokeAccessBatchArguments],
        [RevokeAccessBatchResult],
        [],
      ),
    'revoke_permission' : IDL.Func([RevokePermission], [], []),
    'rewrapThumbnail' : IDL.Func(
        [IDL.Record({ 'thumbnailRef' : ThumbnailRef, 'entry' : Entry })],
        [NodeDetails],
        [],
      ),
    'saveThumbnail' : IDL.Func(
        [
          IDL.Record({
            'thumbnail' : IDL.Record({
              'content' : IDL.Vec(IDL.Nat8),
              'contentType' : IDL.Text,
              'encryption' : ThumbnailEncryptionRef,
            }),
            'entry' : Entry,
          }),
        ],
        [NodeDetails],
        [],
      ),
    'set_asset_content' : IDL.Func([SetAssetContentArguments], [], []),
    'set_asset_properties' : IDL.Func([SetAssetPropertiesArguments], [], []),
    'showTree' : IDL.Func([IDL.Opt(Entry)], [IDL.Text], ['query']),
    'store' : IDL.Func([StoreArgs], [], []),
    'takeRecoveryOwnership' : IDL.Func([], [OwnerEquivalentPrincipal], []),
    'take_ownership' : IDL.Func([], [], []),
    'unset_asset_content' : IDL.Func([UnsetAssetContentArguments], [], []),
    'update' : IDL.Func([UpdateArguments], [StorageResult_1], []),
    'updateDirectoryPolicy' : IDL.Func(
        [UpdateDirectoryPolicyArguments],
        [StorageResult],
        [],
      ),
    'validate_commit_proposed_batch' : IDL.Func(
        [CommitProposedBatchArguments],
        [Result],
        [],
      ),
    'validate_configure' : IDL.Func([ConfigureArguments], [Result], []),
    'validate_grant_permission' : IDL.Func([GrantPermission], [Result], []),
    'validate_revoke_permission' : IDL.Func([RevokePermission], [Result], []),
    'validate_take_ownership' : IDL.Func([], [Result], []),
  });
  
  return EncryptedStorageCanister;
};

export const init = ({ IDL }) => {
  const StorageBackend = IDL.Variant({
    'OnChain' : IDL.Null,
    'BlobStorage' : IDL.Null,
  });
  
  return [
    IDL.Record({
      'owner' : IDL.Principal,
      'storageBackendType' : IDL.Opt(StorageBackend),
    }),
  ];
};