name: treasury

services:
  replica:
    build:
      context: .
      dockerfile: Dockerfile
      pull: true
    platform: linux/amd64
    working_dir: /app
    tty: true
    stdin_open: true
    ports:
      - 4943
    volumes:
      - ./:/app:rw
      - ../..:/workspace:ro
      - ../../mops-patches:/mops-patches:ro
      - treasury_node_modules:/app/node_modules
    environment:
      - TREASURY_ADMIN=${TREASURY_ADMIN:-aaaaa-aa}
    healthcheck:
      test: ['CMD', 'dfx', 'ping']
      interval: 10s
      timeout: 30s
      retries: 12
    command: ['bash', '-lc', 'bash ./docker-entrypoint.sh']

volumes:
  treasury_node_modules:
