export type {
  AccessClass,
  AccessGrantList,
  AccessGrantListMode,
  AccessRequest,
  AccessRequestStatus,
  AccessScope,
  AccessSource,
  BatchOperationKind,
  BlobLocator,
  CommitCaffeineUploadArgs,
  CommitThumbnailUploadArguments,
  ConfigureExternalStorageTargetArgs,
  CreateAccessBatchArguments,
  DeleteTaskStatus,
  DirectoryColor,
  EmailClaim,
  Entry,
  ExternalBlobReplica,
  ExternalStorageCleanupStatus,
  ExternalStorageTargetId,
  ExternalStorageDeleteTaskView,
  ExternalStorageTargetView,
  ListedPendingAccessGrant,
  ObjectStorageStatus,
  StorageReleaseState,
  StorageStatus,
  ListedPrincipalAccessGrant,
  ListAccessGrantsArguments,
  ListResponse,
  NodeDetails,
  ObjectStorageBlobReadRoute,
  ObjectStorageUploadRoute,
  PendingAccessGrant,
  Permission as EncryptedStorageHttpPermission,
  Permission__1,
  PrepareExternalBlobUploadArgs,
  PrepareExternalBlobUploadResult,
  PrepareThumbnailUploadArguments,
  PrepareThumbnailUploadResult,
  Permission__1 as StoragePermission,
  StorageBackend,
  StorageAccessEvent,
  StorageEvent,
  S3CompatibleTargetConfig,
  StoredStorageEvent,
  TargetKind,
  TargetStatus,
  TargetView,
  ThumbnailEncryptionRef,
  ThumbnailEncryptionRequirement,
  ThumbnailRef,
  ThumbnailStoragePolicy,
  Time,
  TreeNode,
  _SERVICE as EncryptedStorageActorService,
} from './encrypted-storage/encrypted-storage.did';
export {
  idlFactory as encryptedStorageIdlFactory,
  init as initEncryptedStorage,
} from './encrypted-storage/encrypted-storage.did';
