/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AssetLocator = { 'Contract' : string } |
  { 'Mint' : string } |
  { 'Native' : null };
export interface BalanceEntry { 'tokenId' : TokenId, 'balance' : bigint }
export type ChainConfig = { 'Evm' : EvmChainConfig } |
  { 'Solana' : SolanaChainConfig };
export interface ChargeAndDistributeArgs {
  'tokenId' : TokenId,
  'metadata' : [] | [string],
  'userId' : Principal,
  'ambassadorL1' : [] | [Principal],
  'ambassadorL2' : [] | [Principal],
  'totalAmount' : bigint,
  'paymentId' : string,
}
export type ChargeAndDistributeResult = { 'ok' : DistributionRecord } |
  { 'err' : DistributePaymentError };
export interface DistributePaymentArgs {
  'tokenId' : TokenId,
  'metadata' : [] | [string],
  'ambassadorL1' : [] | [Principal],
  'ambassadorL2' : [] | [Principal],
  'paymentId' : string,
  'payer' : Principal,
  'amount' : bigint,
}
export type DistributePaymentError = { 'InvalidAmount' : null } |
  { 'AlreadyProcessed' : null } |
  { 'PartiallyCompleted' : DistributionRecord } |
  { 'TransferFailed' : { 'recipient' : string, 'error' : string } } |
  { 'EvmNotConfigured' : null } |
  { 'SolNotConfigured' : null };
export type DistributePaymentResult = { 'ok' : DistributionRecord } |
  { 'err' : DistributePaymentError };
export interface DistributionConfig {
  'l1Bps' : bigint,
  'l2Bps' : bigint,
  'minWithdraw' : MinWithdrawConfig,
}
export interface DistributionLogOptions { 'offset' : bigint, 'limit' : bigint }
export interface DistributionRecord {
  'id' : bigint,
  'status' : DistributionStatus,
  'tokenId' : TokenId,
  'l1Amount' : bigint,
  'transfers' : Array<TransferRecord>,
  'l2Amount' : bigint,
  'ambassadorL1' : [] | [Principal],
  'ambassadorL2' : [] | [Principal],
  'totalAmount' : bigint,
  'paymentId' : string,
  'timestamp' : bigint,
  'payer' : Principal,
  'treasuryAmount' : bigint,
}
export type DistributionStatus = { 'completed' : null } |
  { 'partial' : null };
export interface EvmChainConfig {
  'evmRpcCanisterId' : string,
  'assets' : Array<SupportedAsset>,
  'rpcUrls' : Array<string>,
  'chainId' : bigint,
  'networkId' : string,
}
export interface InitArgs {
  'thresholdKeyName' : ThresholdKeyName,
  'distributionConfig' : [] | [DistributionConfig],
  'chains' : Array<ChainConfig>,
}
export interface MinWithdrawConfig {
  'icp' : bigint,
  'sol' : bigint,
  'baseUsdc' : bigint,
  'baseUsdt' : bigint,
  'baseEth' : bigint,
  'ckEth' : bigint,
  'ckUsdc' : bigint,
  'ckUsdt' : bigint,
  'solUsdc' : bigint,
  'solUsdt' : bigint,
}
export interface SolanaChainConfig {
  'solRpcCanisterId' : string,
  'assets' : Array<SupportedAsset>,
  'rpcUrl' : [] | [string],
  'networkId' : string,
}
export interface SupportedAsset {
  'decimals' : number,
  'tokenId' : TokenId,
  'locator' : AssetLocator,
  'symbol' : string,
}
export type ThresholdKeyName = string;
export type TokenId = { 'ICP' : null } |
  { 'SOL' : null } |
  { 'SolUSDC' : null } |
  { 'SolUSDT' : null } |
  { 'ckETH' : null } |
  { 'ckUSDC' : null } |
  { 'ckUSDT' : null } |
  { 'BaseUSDC' : null } |
  { 'BaseUSDT' : null } |
  { 'BaseETH' : null };
export type TransferOnChainStatus = { 'pending' : null } |
  { 'error' : string } |
  { 'reverted' : null } |
  { 'confirmed' : null } |
  { 'notApplicable' : null };
export interface TransferRecord {
  'tokenId' : TokenId,
  'solSignature' : [] | [string],
  'subaccount' : [] | [Uint8Array],
  'recipient' : Principal,
  'solAddress' : [] | [string],
  'error' : [] | [string],
  'blockIndex' : [] | [bigint],
  'txHash' : [] | [string],
  'amount' : bigint,
  'evmAddress' : [] | [string],
}
export interface TransferVerification {
  'status' : TransferOnChainStatus,
  'txHash' : string,
}
export interface TreasuryCanister {
  'chargeAndDistribute' : ActorMethod<
    [ChargeAndDistributeArgs],
    ChargeAndDistributeResult
  >,
  'distributePayment' : ActorMethod<
    [DistributePaymentArgs],
    DistributePaymentResult
  >,
  'getBalance' : ActorMethod<[TokenId], bigint>,
  'getBalances' : ActorMethod<[], Array<BalanceEntry>>,
  'getDistributionLog' : ActorMethod<
    [DistributionLogOptions],
    Array<DistributionRecord>
  >,
  'getEvmAddress' : ActorMethod<[], [] | [string]>,
  'getSolAddress' : ActorMethod<[], [] | [string]>,
  'getTreasuryBalances' : ActorMethod<[], Array<BalanceEntry>>,
  'getTreasurySigningAddress' : ActorMethod<[], [] | [string]>,
  'getTreasurySolSigningAddress' : ActorMethod<[], [] | [string]>,
  'getUserBalances' : ActorMethod<[Principal], Array<BalanceEntry>>,
  'getUserDistributions' : ActorMethod<[Principal], Array<DistributionRecord>>,
  'verifyDistribution' : ActorMethod<[string], VerifyDistributionResult>,
  'withdraw' : ActorMethod<[WithdrawArgs], WithdrawResult>,
  'withdrawFromTreasury' : ActorMethod<[WithdrawArgs], WithdrawResult>,
}
export type VerifyDistributionError = { 'NotFound' : null } |
  { 'Unauthorized' : null } |
  { 'EvmNotConfigured' : null } |
  { 'SolNotConfigured' : null };
export type VerifyDistributionResult = { 'ok' : Array<TransferVerification> } |
  { 'err' : VerifyDistributionError };
export interface WithdrawArgs {
  'to' : WithdrawDestination,
  'tokenId' : TokenId,
  'amount' : bigint,
}
export type WithdrawDestination = {
    'IC' : { 'owner' : Principal, 'subaccount' : [] | [Uint8Array] }
  } |
  { 'EVM' : { 'address' : string } } |
  { 'SOL' : { 'address' : string } };
export type WithdrawError = { 'BelowMinimum' : { 'minimum' : bigint } } |
  { 'InsufficientBalance' : { 'available' : bigint } } |
  { 'TransferFailed' : string } |
  { 'EvmNotConfigured' : null } |
  { 'SolNotConfigured' : null };
export interface WithdrawReceipt {
  'tx' : WithdrawTx,
  'tokenId' : TokenId,
  'amount' : bigint,
}
export type WithdrawResult = { 'ok' : WithdrawReceipt } |
  { 'err' : WithdrawError };
export type WithdrawTx = { 'IC' : { 'blockIndex' : bigint } } |
  { 'EVM' : { 'txHash' : string } } |
  { 'SOL' : { 'signature' : string } };
/**
 * / Standalone Treasury canister. The `installer` (deployer principal) is the
 * / sole admin — access control to privileged methods is enforced at this
 * / actor's boundary. Treasury library itself trusts its caller (this canister).
 * /
 * / Primary use-case is Rabbithole backend that embeds Treasury as a mixin
 * / (see apps/backend/src/Treasury/mixin.mo); this standalone canister is
 * / retained for isolated testing and hypothetical standalone deployments.
 */
export interface _SERVICE extends TreasuryCanister {}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];